import { it, expect, vi, afterEach } from 'vitest';
import { notificationClient } from './client';
import { id, otherId, json, metadata, context } from './test-fixtures';
const auth = vi.hoisted(() => ({ context: vi.fn(), changed: vi.fn() }));
vi.mock('../auth/client', () => ({ getAuthContext: auth.context, notifyAuthChanged: auth.changed }));
afterEach(() => { vi.unstubAllGlobals(); vi.useRealTimers(); vi.resetAllMocks(); });
it('marks read with fixed empty input and one exact key; never retries automatically', async () => { auth.context.mockResolvedValue(context()); const fetcher = vi.fn<typeof fetch>(async () => json({ status: 200, notificationId: id, readAt: metadata().createdAt })); vi.stubGlobal('fetch', fetcher); await notificationClient.markRead(id, { actorId: id, key: otherId }); expect(fetcher).toHaveBeenCalledTimes(1); expect(fetcher.mock.calls[0]?.[1]?.body).toBe('{}'); expect(new Headers(fetcher.mock.calls[0]?.[1]?.headers).get('Idempotency-Key')).toBe(otherId); });
it('rejects another account before read and after receiving metadata', async () => { const fetcher = vi.fn<typeof fetch>(async () => json(metadata(), 200, otherId)); vi.stubGlobal('fetch', fetcher); auth.context.mockResolvedValue(context(otherId)); await expect(notificationClient.list({}, { actorId: id })).rejects.toMatchObject({ code: 'AUTHENTICATION_REQUIRED' }); expect(fetcher).not.toHaveBeenCalled(); auth.context.mockResolvedValue(context()); await expect(notificationClient.read(id, { actorId: id })).rejects.toMatchObject({ code: 'AUTHENTICATION_REQUIRED' }); });
it('notification identity is inside the total ten-second deadline', async () => { vi.useFakeTimers(); auth.context.mockReturnValue(new Promise(() => { })); const fetcher = vi.fn(); vi.stubGlobal('fetch', fetcher); const observed = notificationClient.markRead(id, { actorId: id, key: otherId }).catch(e => e); await vi.advanceTimersByTimeAsync(10001); expect(await observed).toMatchObject({ code: 'SERVICE_UNAVAILABLE' }); expect(fetcher).not.toHaveBeenCalled(); });
