import {it,expect,vi,afterEach} from 'vitest';
import {proxyFeedback} from './feedback-proxy';
import {json,metadata,id,otherId} from '../feedback/test-fixtures';
vi.mock('server-only',()=>({}));afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();vi.useRealTimers()});
function setup(fetcher:typeof fetch){vi.stubGlobal('fetch',fetcher);vi.stubEnv('GO_API_INTERNAL_URL','http://127.0.0.1:18080');vi.stubEnv('AUTH_PUBLIC_ORIGIN','http://127.0.0.1:3000');vi.stubEnv('APP_ENV','development')}
function req(body?:string,extra:Record<string,string>={}){return new Request('http://127.0.0.1:3000/api/v1/feedback/tickets',{method:body===undefined?'GET':'POST',headers:{Cookie:'other=private; mm_session_dev='+'A'.repeat(43),'Origin':'http://127.0.0.1:3000','X-CSRF-Token':'A'.repeat(43),'Idempotency-Key':otherId,'Content-Type':'application/json',...extra},...(body===undefined?{}:{body})})}
const input=()=>({target:metadata().target,source:{kind:'publication',publicationId:id,attemptId:null,position:null},category:'math_error',title:'title',message:'details',location:''});
it('forwards raw bytes and only selected proof headers',async()=>{const fetcher=vi.fn<typeof fetch>(async()=>json({status:201,ticket:metadata()},201));setup(fetcher as typeof fetch);const raw=' \n'+JSON.stringify(input())+' \t';const r=await proxyFeedback(req(raw),['tickets']);expect(r.status).toBe(201);expect(r.headers.get('cache-control')).toBe('private, no-store');expect(new TextDecoder().decode(fetcher.mock.calls[0]?.[1]?.body as Uint8Array)).toBe(raw);expect(new Headers(fetcher.mock.calls[0]?.[1]?.headers).get('Cookie')).toBe('mm_session_dev='+'A'.repeat(43))});
it('enforces exact body bytes and sanitizes overlimit or truncated responses',async()=>{for(const n of [65536,65537]){const fetcher=vi.fn<typeof fetch>(async()=>json({status:201,ticket:metadata()},201));setup(fetcher as typeof fetch);const raw=JSON.stringify(input());expect((await proxyFeedback(req(raw+' '.repeat(n-raw.length)),['tickets'])).status).toBe(n===65536?201:400)};for(const response of [new Response('x'.repeat(2097153)),new Response('{}',{headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','X-Request-ID':'a'.repeat(32),'Content-Length':'3'}})]){setup(vi.fn(async()=>response) as typeof fetch);expect((await proxyFeedback(req(),['tickets'])).status).toBe(503)}});
it('rejects extra fields, merged unique headers and mismatched route segments before Go',async()=>{const fetcher=vi.fn();setup(fetcher);for(const request of [req(JSON.stringify({...input(),extra:'private'})),req(JSON.stringify(input()),{'Idempotency-Key':id+', '+id}),req(JSON.stringify(input()),{'X-CSRF-Token':'A'.repeat(43)+', '+'A'.repeat(43)})])expect((await proxyFeedback(request,['tickets'])).status).toBeGreaterThanOrEqual(400);expect((await proxyFeedback(req(),['auth','context'])).status).toBe(400);expect(fetcher).not.toHaveBeenCalled()});
it('ten seconds covers an upstream fetch that ignores abort',async()=>{vi.useFakeTimers();setup(vi.fn(()=>new Promise(()=>{})) as typeof fetch);const pending=proxyFeedback(req(),['tickets']);await vi.advanceTimersByTimeAsync(10001);expect((await pending).status).toBe(503)});
