/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDomains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/domains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDomainDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getKnowledgeView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/paths/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPathView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublishedAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head: operations["headPublishedAsset"];
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ref: {
            id: string;
            version: number;
        };
        source: {
            /** @enum {unknown} */
            kind: "original" | "external";
            author: string;
            title: string;
            url: string;
            accessedAt: string;
            license: string;
            attribution: string;
        };
        relation: {
            /** @enum {unknown} */
            kind: "prerequisite" | "derivation" | "related";
            target: components["schemas"]["ref"];
        };
        knowledge: {
            id: string;
            version: number;
            domainIds: string[];
            topicIds: string[];
            /** @enum {unknown} */
            type: "concept" | "definition" | "axiom" | "theorem" | "corollary" | "method" | "mathematical-thinking";
            title: string;
            titleZh: string;
            statement: string;
            scope: string;
            system: string;
            proof: string;
            objectives: string[];
            conditions: string[];
            sources: components["schemas"]["source"][];
            relations: components["schemas"]["relation"][];
        };
        angle: {
            kind: string;
            body: string;
        };
        unit: {
            id: string;
            version: number;
            knowledge: components["schemas"]["ref"];
            angles: components["schemas"]["angle"][];
            examples: string[];
            counterexamples: string[];
            assetIds: string[];
        };
        path: {
            id: string;
            version: number;
            domainIds: string[];
            title: string;
            titleZh: string;
            nodes: components["schemas"]["ref"][];
        };
        asset: {
            id: string;
            path: string;
            sha256: string;
            author: string;
            license: string;
            attribution: string;
            knowledge: components["schemas"]["ref"];
        };
        DomainSummary: {
            id: string;
            order: number;
            name: string;
            nameZh: string;
            topics: {
                id: string;
                name: string;
                nameZh: string;
            }[];
            relatedDomainIds: string[];
            /** @enum {string} */
            contentStatus: "planned" | "published";
            publishedKnowledgeCount: number;
        };
        DomainDetail: {
            id: string;
            order: number;
            name: string;
            nameZh: string;
            topics: {
                id: string;
                name: string;
                nameZh: string;
            }[];
            relatedDomainIds: string[];
            /** @enum {string} */
            contentStatus: "planned" | "published";
            publishedKnowledgeCount: number;
            paths: components["schemas"]["PathSummary"][];
        };
        PathSummary: {
            id: string;
            version: number;
            title: string;
            titleZh: string;
        };
        AssetMetadata: {
            id: string;
            sha256: string;
            author: string;
            license: string;
            attribution: string;
            knowledge: components["schemas"]["ref"];
        };
        KnowledgeView: {
            knowledge: components["schemas"]["knowledge"];
            units: components["schemas"]["unit"][];
            assets: components["schemas"]["AssetMetadata"][];
        };
        PathView: {
            path: components["schemas"]["path"];
            knowledge: components["schemas"]["KnowledgeView"][];
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "INVALID_QUERY" | "NOT_FOUND" | "SERVICE_UNAVAILABLE" | "INTERNAL_ERROR";
                message: string;
                requestId: string;
            };
        };
        DomainList: {
            items: components["schemas"]["DomainSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listDomains: {
        parameters: {
            query?: {
                /** @description Literal English or Chinese name/topic search; maximum 512 UTF-8 bytes. Unknown or duplicate parameters are rejected. */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domains ordered by catalogue order. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainList"];
                };
            };
            /** @description Invalid query parameters. */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service temporarily unavailable. */
            503: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getDomainDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail from one valid publication snapshot. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DomainDetail"];
                    };
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service temporarily unavailable. */
            503: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getKnowledgeView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail from one valid publication snapshot. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KnowledgeView"];
                    };
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service temporarily unavailable. */
            503: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPathView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail from one valid publication snapshot. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PathView"];
                    };
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service temporarily unavailable. */
            503: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ready";
                    };
                };
            };
            /** @description unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "unavailable";
                    };
                };
            };
        };
    };
    getPublishedAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invalid, draft-only or no longer effective digests return NOT_FOUND. */
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original SVG bytes referenced by an effective published unit; authorization is rechecked for each read. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "Content-Length"?: number;
                    "X-Content-Type-Options"?: "nosniff";
                    "Content-Security-Policy"?: "sandbox; default-src 'none'";
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": string;
                };
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Service temporarily unavailable. */
            503: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    headPublishedAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invalid, draft-only or no longer effective digests return NOT_FOUND. */
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original SVG bytes referenced by an effective published unit; authorization is rechecked for each read. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "Content-Length"?: number;
                    "X-Content-Type-Options"?: "nosniff";
                    "Content-Security-Policy"?: "sandbox; default-src 'none'";
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found. */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error. */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service temporarily unavailable. */
            503: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
