import 'server-only';
import {parseGoOrigin} from './server-config';import {parseAuthOrigin} from '../auth/config';import {selectAuthCookies} from '../auth/cookies';
const max=64*1024*1024;
export function managedProxyError(status=503,code='CONTENT_NOT_READY'){return Response.json({error:{code,message:'Knowledge is temporarily unavailable.',requestId:'unavailable'}},{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
function allowedPath(path:string){return /^\/api\/v3\/(?:content-mode|knowledge(?:\/k-[0-9a-f]{56})?|topics(?:\/[A-Za-z0-9:-]+)?|admin\/knowledge(?:\/imports(?:\/[0-9a-f-]{36}(?:\/apply)?)?|\/k-[0-9a-f]{56}(?:\/(?:publish|unpublish|restore))?)?|study\/(?:overview|topics|knowledge(?:\/k-[0-9a-f]{56}(?:\/(?:begin|complete|start-review|finish-review|note))?)?|history))$/.test(path)}
async function boundedBody(request:Request|Response,limit:number,signal:AbortSignal){
 if(Number(request.headers.get('Content-Length')??'0')>limit)throw new Error('INPUT_TOO_LARGE');if(signal.aborted)throw Error('REQUEST_INTERRUPTED');if(!request.body)return new Uint8Array();
 const reader=request.body.getReader(),parts:Uint8Array[]=[];let total=0,rejectAbort!:(error:Error)=>void;const aborted=new Promise<never>((_,reject)=>{rejectAbort=reject});
 const cancel=()=>{rejectAbort(Error('REQUEST_INTERRUPTED'));void reader.cancel().catch(()=>{})};signal.addEventListener('abort',cancel,{once:true});
 try{if(signal.aborted)cancel();while(true){const{done,value}=await Promise.race([reader.read(),aborted]);if(done)break;total+=value.length;if(total>limit){await reader.cancel();throw Error('INPUT_TOO_LARGE')};parts.push(value)}}finally{signal.removeEventListener('abort',cancel);reader.releaseLock()};const all=new Uint8Array(total);let offset=0;for(const p of parts){all.set(p,offset);offset+=p.length};return all;
}
export function createKnowledgeAdminProxy(raw:string,options:{publicOrigin:string;production:boolean},fetcher:typeof fetch=fetch){const origin=parseGoOrigin(raw),publicOrigin=parseAuthOrigin(options.publicOrigin,options.production);return async(request:Request):Promise<Response>=>{
 const u=new URL(request.url),path=u.pathname;if(!allowedPath(path)||u.hash||u.pathname.includes('%'))return managedProxyError(404,'NOT_FOUND');if(!['GET','POST','PUT','DELETE'].includes(request.method))return managedProxyError(405,'METHOD_NOT_ALLOWED');const write=request.method!=='GET',privateRoute=path.includes('/admin/')||path.includes('/study/'),upload=request.method==='POST'&&path==='/api/v3/admin/knowledge/imports';
 if(write&&(request.headers.get('Origin')!==publicOrigin||request.headers.get('Sec-Fetch-Site')==='cross-site'))return managedProxyError(403,'CSRF_FAILED');const cookie=selectAuthCookies(request.headers.get('Cookie')??'',options.production);if(privateRoute&&!cookie)return managedProxyError(401,'AUTHENTICATION_REQUIRED');
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),upload?60000:10000);const cancel=()=>controller.abort();request.signal.addEventListener('abort',cancel,{once:true});try{
 if(upload){const auth=await fetcher(origin+'/api/v1/auth/session',{method:'GET',cache:'no-store',redirect:'error',headers:{Cookie:cookie,Accept:'application/json'},signal:controller.signal});if(!auth.ok)return managedProxyError(auth.status,'AUTHENTICATION_REQUIRED');const raw=await auth.json() as {data?:{user?:{roles?:string[];mustChangePassword?:boolean}}};if(!raw.data?.user?.roles?.includes('admin'))return managedProxyError(403,'FORBIDDEN');if(raw.data.user.mustChangePassword)return managedProxyError(403,'PASSWORD_CHANGE_REQUIRED')}
 const headers=new Headers({Accept:'application/json'});if(cookie&&privateRoute)headers.set('Cookie',cookie);for(const key of ['Origin','X-CSRF-Token','Idempotency-Key','If-Match','Content-Type','Sec-Fetch-Site']){const value=request.headers.get(key);if(value)headers.set(key,value)};const body=write?await boundedBody(request,upload||path.includes('/admin/knowledge')?max:131072,controller.signal):undefined;
 const response=await fetcher(origin+path+u.search,{method:request.method,cache:'no-store',redirect:'error',signal:controller.signal,headers,...(body?{body:body as BodyInit}:{})});const bytes=await boundedBody(response,max,controller.signal);const selected=new Headers({'Content-Type':'application/json','Cache-Control':privateRoute?'private, no-store':'no-store','X-Content-Type-Options':'nosniff'});for(const key of ['X-Request-ID','Retry-After','Allow']){const value=response.headers.get(key);if(value)selected.set(key,value)};return new Response(bytes,{status:response.status,headers:selected})
 }catch(e){return managedProxyError(e instanceof Error&&e.message==='INPUT_TOO_LARGE'?413:503,e instanceof Error&&e.message==='INPUT_TOO_LARGE'?'INPUT_TOO_LARGE':'REQUEST_INTERRUPTED')}finally{clearTimeout(timer);request.signal.removeEventListener('abort',cancel)}}}
