import "server-only";
import {parseGoOrigin} from "./server-config";
import {parseAuthOrigin} from "../auth/config";
import {selectAuthCookies} from "../auth/cookies";
import {secretPattern} from "../auth/schemas";
import {contentUUID} from "../content/schemas";
import {readContentBytes,ContentByteLimitError} from "../content/bytes";
import {parseContentJSON} from "../content/raw-json";
import {studyRouteRequest,resolveStudyRoute,readStudyResponse,studyFailure,studyInputError} from "../study/protocol";
import type {StudyRoute,StudyErrorCode} from "../study/types";
const headers=()=>new Headers({"Cache-Control":"private, no-store","Content-Type":"application/json","X-Content-Type-Options":"nosniff","X-Request-ID":"unavailable"});
export function studyProxyError(code:StudyErrorCode="SERVICE_UNAVAILABLE"):Response{const error=studyFailure(code);return Response.json({error:{code:error.code,message:error.message,requestId:error.requestId}},{status:error.status,headers:headers()})}
export function createStudyProxy(rawGoOrigin:string,config:{publicOrigin:string;production:boolean},fetcher:typeof fetch=fetch){const origin=parseGoOrigin(rawGoOrigin),publicOrigin=parseAuthOrigin(config.publicOrigin,config.production);return async(request:Request):Promise<Response>=>{
 const route=resolveStudyRoute(request);if(typeof route==="string")return studyProxyError(route);const target=studyRouteRequest(route as StudyRoute)!;if(request.method!==target.method){const response=studyProxyError("METHOD_NOT_ALLOWED");response.headers.set("Allow",target.method);return response};const write=target.method!=="GET";
 if(request.headers.get("Sec-Fetch-Site")==="cross-site"||write&&request.headers.get("Origin")!==publicOrigin||!write&&request.headers.has("Origin")&&request.headers.get("Origin")!==publicOrigin||request.headers.get("X-CSRF-Token")?.includes(",")||write&&!secretPattern.test(request.headers.get("X-CSRF-Token")??""))return studyProxyError("CSRF_FAILED");if(request.headers.get("Idempotency-Key")?.includes(",")||write&&!contentUUID.test(request.headers.get("Idempotency-Key")??""))return studyProxyError("INVALID_REQUEST");if(!write&&request.body!==null)return studyProxyError("INVALID_REQUEST");
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000),abort=()=>controller.abort();request.signal.addEventListener("abort",abort,{once:true});try{if(request.signal.aborted)return studyProxyError();const forwarded=new Headers({Accept:"application/json"}),cookie=selectAuthCookies(request.headers.get("Cookie")??"",config.production,true);if(cookie)forwarded.set("Cookie",cookie);for(const key of["Origin","X-CSRF-Token","Sec-Fetch-Site"]){const value=request.headers.get(key);if(value!==null)forwarded.set(key,value)};let body:Uint8Array|undefined;if(write){if(!/^application\/json(?:;\s*charset=(?:utf-8|"utf-8"))?$/i.test(request.headers.get("Content-Type")??""))return studyProxyError("INVALID_REQUEST");const bytes=await readContentBytes(new Response(request.body,{headers:request.headers}),target.kind==="saveNote"?131072:8192,controller.signal);let parsed:unknown;try{parsed=parseContentJSON(bytes)}catch{return studyProxyError("INVALID_REQUEST")};const error=studyInputError(target.kind,parsed);if(error)return studyProxyError(error);body=bytes;forwarded.set("Content-Type","application/json");forwarded.set("Idempotency-Key",request.headers.get("Idempotency-Key")!)}
 const response=await fetcher(origin+target.path,{method:target.method,headers:forwarded,...(body?{body:body as BodyInit}:{}),cache:"no-store",redirect:"error",signal:controller.signal});const parsed=await readStudyResponse(response,target.kind,controller.signal),out=headers();out.set("X-Request-ID",response.headers.get("X-Request-ID")!);if(!parsed.result.ok&&parsed.result.retryAfter!==undefined)out.set("Retry-After",String(parsed.result.retryAfter));return Response.json(parsed.payload,{status:response.status,headers:out});
 }catch(error){return studyProxyError(error instanceof ContentByteLimitError?"PAYLOAD_TOO_LARGE":"SERVICE_UNAVAILABLE")}finally{clearTimeout(timer);request.signal.removeEventListener("abort",abort)}
}}
