"use client";
import {useContext,useEffect,useRef,useState} from "react";
import {StudyAccountContext} from "./account-boundary";
import {useStudyCommand} from "./pending-command";
import {StudyCommandFeedback} from "./feedback";
import {NoteEditor} from "./note-editor";
import {useUiI18n} from "@/lib/i18n/provider";
import type {StudyDetail,NoteView,CommandInput} from "@/lib/study/types";
export function KnowledgeStudyControls({detail,initialNote,readingKnowledge}:{detail:StudyDetail;initialNote?:NoteView;readingKnowledge?:{id:string;version:number}}){
 const{t}=useUiI18n(),account=useContext(StudyAccountContext),[value,setValue]=useState(detail),started=useRef(false),command=useStudyCommand<StudyDetail>(setValue);
 const matchesReading=!readingKnowledge||readingKnowledge.id===detail.currentKnowledge?.id&&readingKnowledge.version===detail.currentKnowledge?.version;
 const input=():CommandInput|null=>value.currentKnowledge&&value.pair.knowledgeHead?{knowledge:{id:value.currentKnowledge.id,version:value.currentKnowledge.version,sha256:value.currentKnowledge.sha256},expectedKnowledgeHead:value.pair.knowledgeHead,expectedSequence:value.record.sequence}:null;
 useEffect(()=>{if(!matchesReading||started.current||!account||account.actorId!==detail.actorId||!detail.available||!detail.currentKnowledge||!detail.pair.knowledgeHead)return;started.current=true;void command.run({kind:"begin",id:detail.record.knowledgeId},{knowledge:{id:detail.currentKnowledge.id,version:detail.currentKnowledge.version,sha256:detail.currentKnowledge.sha256},expectedKnowledgeHead:detail.pair.knowledgeHead,expectedSequence:detail.record.sequence})},[matchesReading,account?.actorId,detail.actorId,detail.available,detail.record.knowledgeId,detail.currentKnowledge?.version,detail.currentKnowledge?.sha256,detail.pair.knowledgeHead]);
 const stateKey={unlearned:"study.state.unlearned",learning:"study.state.learning",completed:"study.state.completed",reviewing:"study.state.reviewing"} as const,enabled=!!account&&account.actorId===value.actorId&&value.available&&matchesReading&&!command.busy&&!command.pending;
 const note:NoteView=initialNote??{actorId:value.actorId,knowledgeId:value.record.knowledgeId,revision:0,body:"",knowledge:value.currentKnowledge?{id:value.currentKnowledge.id,version:value.currentKnowledge.version,sha256:value.currentKnowledge.sha256}:value.record.completedRef,updatedAt:null};
 return <section className="panel"><p data-study-state={value.record.state}>{t(stateKey[value.record.state],{})}</p>{(value.materialChanged||!matchesReading)&&<p>{t("study.materialChanged",{})}</p>}{!value.available&&<p>{t("study.withdrawn",{})}</p>}<div className="actions">{value.record.state==="learning"&&<button type="button" className="button" disabled={!enabled} onClick={()=>{const data=input();if(data)void command.run({kind:"complete",id:value.record.knowledgeId},data)}}>{t("study.complete",{})}</button>}{value.record.state==="completed"&&<button type="button" className="button" disabled={!enabled} onClick={()=>{const data=input();if(data)void command.run({kind:"startReview",id:value.record.knowledgeId},data)}}>{t("study.review.start",{})}</button>}{value.record.state==="reviewing"&&<button type="button" className="button" disabled={!enabled} onClick={()=>{const data=input();if(data&&value.record.activeReviewId)void command.run({kind:"finishReview",id:value.record.knowledgeId},{...data,reviewId:value.record.activeReviewId})}}>{t("study.review.finish",{})}</button>}</div><StudyCommandFeedback command={command}/><NoteEditor knowledgeId={value.record.knowledgeId} initialNote={note} disabled={value.record.firstStartedAt===null||command.busy}/></section>;
}
