'use client';
import {useState,useEffect,useContext,useCallback,useRef} from 'react';
import {useUiI18n} from '@/lib/i18n/provider';import {managedRequest} from '@/lib/knowledge-admin/client';
import {KnowledgeError,type StudyDetail,type Note,type StudyInput} from '@/lib/knowledge-admin/types';
import {ManagedReadingContext} from '@/features/reading/current-knowledge-view';import {ManagedNoteEditor} from './managed-note-editor';
export function ManagedControls({initial,note}:{initial:StudyDetail;note?:Note}){
 const{t}=useUiI18n(),reading=useContext(ManagedReadingContext);const[detail,setDetail]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[lastAction,setLastAction]=useState('begin');const pending=useRef<{action:string;input:StudyInput;key:string}|null>(null);
 const replace=reading?.replace;useEffect(()=>{setDetail(initial);if(initial.currentKnowledge)replace?.(initial.currentKnowledge)},[initial,replace]);
 const refresh=useCallback(async()=>{const next=await managedRequest<StudyDetail>(`/api/v3/study/knowledge/${initial.record.knowledgeId}`);setDetail(next);if(next.currentKnowledge)replace?.(next.currentKnowledge);return next.currentKnowledge?.ref},[initial.record.knowledgeId,replace]);
 const shown=reading?.knowledge.ref??detail.currentKnowledge?.ref;const synchronized=!!shown&&shown.contentSha256===detail.currentKnowledge?.ref.contentSha256&&shown.id===detail.record.knowledgeId;
 useEffect(()=>{if(detail.currentKnowledge&&replace&&!synchronized)replace(detail.currentKnowledge)},[detail.currentKnowledge,replace,synchronized,reading?.knowledge.ref.contentSha256]);
 async function run(action:string){if(!detail.currentKnowledge||!shown||!synchronized)return;setLastAction(action);const job=pending.current??{action,input:{knowledge:shown,expectedSequence:detail.record.sequence,...(action==='finish-review'&&detail.record.activeReviewId?{reviewId:detail.record.activeReviewId}:{})},key:crypto.randomUUID()};pending.current=job;setBusy(true);setError('');try{const next=await managedRequest<StudyDetail>(`/api/v3/study/knowledge/${detail.record.knowledgeId}/${job.action}`,'POST',job.input,job.key);setDetail(next);if(next.currentKnowledge)replace?.(next.currentKnowledge);pending.current=null}catch(e){if(e instanceof KnowledgeError&&e.status===409){pending.current=null;try{await refresh()}catch{};setError(t('managed.conflict',{}))}else setError(t('managed.uncertain',{}))}finally{setBusy(false)}}
 return <section className="panel"><p>{t(`managed.${detail.record.state==='unlearned'?'unlearned':detail.record.state==='learning'?'learning':detail.record.state==='completed'?'learned':'reviewing'}`,{})}</p>{detail.materialChanged&&<p role="status">{t('managed.changed',{})}</p>}{!detail.available&&<p>{t('managed.unavailable',{})}</p>}{detail.available&&<div className="button-row">{detail.record.state==='unlearned'&&<button className="button" disabled={busy||!synchronized} onClick={()=>void run('begin')}>{t('managed.begin',{})}</button>}{detail.record.state==='learning'&&<button className="button" disabled={busy||!synchronized} onClick={()=>void run('complete')}>{t('managed.complete',{})}</button>}{detail.record.state==='completed'&&<button className="button" disabled={busy||!synchronized} onClick={()=>void run('start-review')}>{t('managed.startReview',{})}</button>}{detail.record.state==='reviewing'&&<button className="button" disabled={busy||!synchronized} onClick={()=>void run('finish-review')}>{t('managed.finishReview',{})}</button>}</div>}{error&&<><p role="alert">{error}</p><button className="button secondary" disabled={busy||!synchronized} onClick={()=>void run(pending.current?.action??lastAction)}>{t('managed.retry',{})}</button></>}{note&&<ManagedNoteEditor initial={note} knowledge={synchronized?shown:undefined} onKnowledgeConflict={refresh}/>}</section>
}
