import {webcrypto} from 'node:crypto';
import {it,expect,vi} from 'vitest';import {render,screen} from '@testing-library/react';import {ManagedNoteEditor} from './managed-note-editor';
vi.mock('@/lib/i18n/provider',()=>({useUiI18n:()=>({t:(key:string)=>key})}));
it('retains private note body while knowledge is unavailable and disables new saves',()=>{render(<ManagedNoteEditor initial={{actorId:'51390b7d-a8e9-4e98-a3ae-22101c20b309',knowledgeId:'k-'+'a'.repeat(56),body:'Own retained note',revision:1,knowledge:null,deleted:false,available:false,updatedAt:null}}/>);expect(screen.getByRole('textbox')).toHaveValue('Own retained note');expect(screen.getByRole('textbox')).toBeDisabled();expect(screen.queryByRole('button',{name:'managed.saveNote'})).toBeNull()});
import {ManagedHistory} from './managed-history';
it('combines truthful legacy and current timeline without a version label',()=>{const id='51390b7d-a8e9-4e98-a3ae-22101c20b309';render(<ManagedHistory page={{actorId:id,items:[],nextCursor:null}} legacy={{actorId:id,limit:50,nextCursor:null,items:[{id,knowledge:{id:'fractions',version:2,sha256:'b'.repeat(64)},taxonomyVersionId:'a'.repeat(64),taxonomyHead:id,kind:'completed',occurredAt:'2026-10-06T10:00:00Z',noteRevision:null,reviewId:null,sourceKind:'native',originEventId:null}]}}/>);expect(screen.getByText(/fractions/)).toBeVisible();expect(document.body.textContent).not.toContain('v2')});

import {fireEvent,waitFor} from '@testing-library/react';import {CurrentKnowledgeView} from '@/features/reading/current-knowledge-view';import {ManagedControls} from './managed-controls';import {KnowledgeError,type PublicKnowledge,type StudyDetail,type Note} from '@/lib/knowledge-admin/types';
const requests=vi.hoisted(()=>({call:vi.fn()}));vi.mock('@/lib/knowledge-admin/client',()=>({managedRequest:requests.call}));vi.mock('@/features/reading/safe-markdown',()=>({SafeMarkdown:({source}:{source:string})=><div>{source}</div>}));vi.mock('@/features/feedback/report-link',()=>({ReportLink:()=>null}));
const kid='k-'+'a'.repeat(56),actor='51390b7d-a8e9-4e98-a3ae-22101c20b309';
function reading(sha='a',statement='数学正文 A'):PublicKnowledge{return {id:kid,externalId:'raw-id',topicKeys:['97F40'],point:{title:'Original mathematics',title_zh:'自制数学知识',type:'definition',statement,conditions:[],scope:'有理数',learning_difficulty:{difficulty_level:1,rationale:'可直接理解。',prerequisites:[],review_status:'body_assessed',rubric_version:'learning-foundation-v1-20261008',proof_scope_note:'此定义不需要证明。'}},sources:[],ref:{id:kid,contentSha256:sha.repeat(64),sourceKind:'managed'},updatedAt:'2026-10-09T00:00:00Z'}}
function detail(k=reading()):StudyDetail{return {actorId:actor,currentKnowledge:k,available:true,materialChanged:false,record:{knowledgeId:kid,state:'unlearned',sequence:0,firstStartedAt:null,firstCompletedAt:null,lastCompletedAt:null,lastReadAt:null,lastReviewedAt:null,completedRef:null,lastReviewRef:null,lastReviewId:null,activeReviewId:null}}}
const emptyNote=():Note=>({actorId:actor,knowledgeId:kid,body:'',revision:0,knowledge:null,available:true,deleted:false,updatedAt:null});
it('shows corrected mathematics before enabling a retried learning action',async()=>{const a=reading(),b=reading('b','数学正文 B');requests.call.mockReset();requests.call.mockImplementation(async(path:string,method?:string)=>{if(method==='POST')throw new KnowledgeError('CONTENT_STALE',409);return detail(b)});render(<CurrentKnowledgeView knowledge={a} personal={<ManagedControls initial={detail(a)}/>}/>);fireEvent.click(screen.getByRole('button',{name:'managed.begin'}));await screen.findByRole('alert');await waitFor(()=>expect(screen.getByText('数学正文 B')).toBeVisible());expect(screen.queryByText('数学正文 A')).toBeNull()});
it('retains a draft and updates its source reference after a knowledge conflict',async()=>{const a=reading(),b=reading('b','数学正文 B');requests.call.mockReset();let saves=0;requests.call.mockImplementation(async(path:string,method?:string,input?:unknown)=>{if(method==='PUT'){if(++saves===1)throw new KnowledgeError('CONTENT_STALE',409);return {...emptyNote(),body:'保留我的笔记草稿',revision:2,knowledge:b.ref}};if(path.endsWith('/note'))return {...emptyNote(),body:'另一个窗口的笔记',revision:1};return detail(b)});render(<CurrentKnowledgeView knowledge={a} personal={<ManagedControls initial={detail(a)} note={emptyNote()}/>}/>);fireEvent.change(screen.getByRole('textbox'),{target:{value:'保留我的笔记草稿'}});fireEvent.click(screen.getByRole('button',{name:'managed.saveNote'}));await screen.findByRole('status');await waitFor(()=>expect(screen.getByRole('textbox')).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'managed.saveNote'}));await waitFor(()=>expect(requests.call.mock.calls.filter(c=>c[1]==='PUT')).toHaveLength(2));expect(requests.call.mock.calls.filter(c=>c[1]==='PUT')[1][2]).toMatchObject({knowledge:b.ref,expectedRevision:1,body:'保留我的笔记草稿'});expect(screen.getByRole('textbox')).toHaveValue('保留我的笔记草稿')});
it('links only published relation targets and keeps missing targets as text',async()=>{vi.stubGlobal('crypto',webcrypto);requests.call.mockReset();requests.call.mockImplementation(async(path:string)=>{const id=path.split('/').at(-1)!;const digest=await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode('published-target'));const expected='k-'+Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('').slice(0,56);if(id!==expected)throw new KnowledgeError('NOT_FOUND',404);return {...reading(),id,externalId:'published-target',ref:{...reading().ref,id}}});const k=reading();k.point.relations=[{kind:'related',target_source_id:'source',target_id:'published-target',target_version:1,status:'confirmed',reason:'已核实的相关知识'},{kind:'related',target_source_id:'source',target_id:'missing-target',target_version:1,status:'confirmed',reason:'当前未导入的相关知识'}];render(<CurrentKnowledgeView knowledge={k}/>);await waitFor(()=>expect(screen.getByRole('link',{name:'published-target'})).toHaveAttribute('href',expect.stringMatching(/^\/knowledge\/k-[a-f0-9]{56}$/)));expect(screen.queryByRole('link',{name:'missing-target'})).toBeNull()});
it('aligns initial private detail and displayed body before starting learning',async()=>{const a=reading(),b=reading('b','数学正文 B');requests.call.mockReset();render(<CurrentKnowledgeView knowledge={a} personal={<ManagedControls initial={detail(b)}/>}/>);await waitFor(()=>expect(screen.getByText('数学正文 B')).toBeVisible());expect(screen.getByRole('button',{name:'managed.begin'})).toBeEnabled()});
