import {render,screen,fireEvent,waitFor} from "@testing-library/react";
import {it,expect,vi,beforeEach} from "vitest";
import {NoteEditor} from "./note-editor";
import {StudyAccountContext,StudyAccountBoundary} from "./account-boundary";
import {UiLocaleProvider,useUiI18n} from "@/lib/i18n/provider";
import type {NoteView} from "@/lib/study/types";
const mocks=vi.hoisted(()=>({request:vi.fn(),context:vi.fn(),refresh:vi.fn()}));vi.mock("@/lib/study/client",()=>({studyRequest:mocks.request}));vi.mock("@/lib/auth/client",()=>({getAuthContext:mocks.context}));vi.mock("next/navigation",()=>({useRouter:()=>mocks}));
const actor="11111111-1111-4111-8111-111111111111",other="22222222-2222-4222-8222-222222222222";
const note:NoteView={actorId:actor,knowledgeId:"fractions",revision:1,body:"Private original input.",knowledge:{id:"fractions",version:1,sha256:"a".repeat(64)},updatedAt:"2026-10-06T10:00:00Z"};
beforeEach(()=>{Object.values(mocks).forEach(m=>m.mockReset());mocks.context.mockResolvedValue({ok:true,data:{user:{id:actor,mustChangePassword:false}}})});
function Switch(){const{setLocale}=useUiI18n();return <button onClick={()=>setLocale("zh-CN")}>switch</button>}
it("dirty_note_survives_locale_switch and failure keeps input",async()=>{mocks.request.mockResolvedValue({ok:false,status:409,code:"STUDY_NOTE_CONFLICT",message:"This note has changed. Read the latest revision before saving.",requestId:"unavailable"});render(<UiLocaleProvider initialLocale="en"><StudyAccountContext.Provider value={{actorId:actor,invalidate:()=>{}}}><Switch/><NoteEditor knowledgeId="fractions" initialNote={note}/></StudyAccountContext.Provider></UiLocaleProvider>);fireEvent.change(screen.getByLabelText("Personal note"),{target:{value:"Unsaved personal derivation."}});fireEvent.click(screen.getByRole("button",{name:"switch"}));expect(screen.getByLabelText("私人笔记")).toHaveValue("Unsaved personal derivation.");fireEvent.click(screen.getByRole("button",{name:"保存笔记"}));await waitFor(()=>expect(mocks.request).toHaveBeenCalled());expect(screen.getByLabelText("私人笔记")).toHaveValue("Unsaved personal derivation.")});
it("note_switch_actor_hides_old_input",async()=>{const view=render(<StudyAccountBoundary actorId={actor}><NoteEditor knowledgeId="fractions" initialNote={note}/></StudyAccountBoundary>);await screen.findByDisplayValue(note.body);mocks.context.mockResolvedValue({ok:true,data:{user:{id:other,mustChangePassword:false}}});window.dispatchEvent(new Event("math-master:auth-change"));await waitFor(()=>expect(screen.queryByDisplayValue(note.body)).not.toBeInTheDocument());view.unmount()});
it("late_response_is_ignored after actor invalidation",async()=>{let resolve!:(value:unknown)=>void;mocks.request.mockReturnValue(new Promise(r=>{resolve=r}));const view=render(<StudyAccountBoundary actorId={actor}><NoteEditor knowledgeId="fractions" initialNote={note}/></StudyAccountBoundary>);await screen.findByDisplayValue(note.body);fireEvent.change(screen.getByLabelText("Personal note"),{target:{value:"Late private input."}});fireEvent.click(screen.getByRole("button",{name:"Save note"}));await waitFor(()=>expect(mocks.request).toHaveBeenCalledTimes(1));mocks.context.mockResolvedValue({ok:true,data:{user:{id:other,mustChangePassword:false}}});window.dispatchEvent(new Event("math-master:auth-change"));resolve({ok:true,data:{actorId:actor,knowledgeId:"fractions",revision:2,deleted:false,updatedAt:"2026-10-06T11:00:00Z"}});await waitFor(()=>expect(screen.queryByDisplayValue("Late private input.")).not.toBeInTheDocument());expect(screen.queryByText("Note saved.")).not.toBeInTheDocument();view.unmount()});
