import {render,screen,fireEvent,waitFor,act} from "@testing-library/react";
import {it,expect,vi,beforeEach} from "vitest";
import {NoteEditor} from "./note-editor";
import {StudyAccountContext,StudyAccountBoundary} from "./account-boundary";
import {UiLocaleProvider,useUiI18n} from "@/lib/i18n/provider";
import type {NoteView} from "@/lib/study/types";
const mocks=vi.hoisted(()=>({request:vi.fn(),context:vi.fn(),refresh:vi.fn()}));vi.mock("@/lib/study/client",()=>({studyRequest:mocks.request}));vi.mock("@/lib/auth/client",()=>({getAuthContext:mocks.context}));vi.mock("next/navigation",()=>({useRouter:()=>mocks}));
const actor="11111111-1111-4111-8111-111111111111",other="22222222-2222-4222-8222-222222222222";
const note:NoteView={actorId:actor,knowledgeId:"fractions",revision:1,body:"Private original input.",knowledge:{id:"fractions",version:1,sha256:"a".repeat(64)},updatedAt:"2026-10-06T10:00:00Z"};
beforeEach(()=>{Object.values(mocks).forEach(m=>m.mockReset());mocks.context.mockResolvedValue({ok:true,data:{user:{id:actor,mustChangePassword:false}}})});
function Switch(){const{setLocale}=useUiI18n();return <button onClick={()=>setLocale("zh-CN")}>switch</button>}
it("dirty_note_survives_locale_switch and failure keeps input",async()=>{mocks.request.mockResolvedValue({ok:false,status:409,code:"STUDY_NOTE_CONFLICT",message:"This note has changed. Read the latest revision before saving.",requestId:"unavailable"});render(<UiLocaleProvider initialLocale="en"><StudyAccountContext.Provider value={{actorId:actor,invalidate:()=>{}}}><Switch/><NoteEditor knowledgeId="fractions" initialNote={note}/></StudyAccountContext.Provider></UiLocaleProvider>);fireEvent.change(screen.getByLabelText("Personal note"),{target:{value:"Unsaved personal derivation."}});fireEvent.click(screen.getByRole("button",{name:"switch"}));expect(screen.getByLabelText("私人笔记")).toHaveValue("Unsaved personal derivation.");fireEvent.click(screen.getByRole("button",{name:"保存笔记"}));await waitFor(()=>expect(mocks.request).toHaveBeenCalled());expect(screen.getByLabelText("私人笔记")).toHaveValue("Unsaved personal derivation.")});
it("note_switch_actor_hides_old_input",async()=>{const view=render(<StudyAccountBoundary actorId={actor}><NoteEditor knowledgeId="fractions" initialNote={note}/></StudyAccountBoundary>);await screen.findByDisplayValue(note.body);mocks.context.mockResolvedValue({ok:true,data:{user:{id:other,mustChangePassword:false}}});window.dispatchEvent(new Event("math-master:auth-change"));await waitFor(()=>expect(screen.queryByDisplayValue(note.body)).not.toBeInTheDocument());view.unmount()});
it("late_response_is_ignored after actor invalidation",async()=>{let resolve!:(value:unknown)=>void;mocks.request.mockReturnValue(new Promise(r=>{resolve=r}));const view=render(<StudyAccountBoundary actorId={actor}><NoteEditor knowledgeId="fractions" initialNote={note}/></StudyAccountBoundary>);await screen.findByDisplayValue(note.body);fireEvent.change(screen.getByLabelText("Personal note"),{target:{value:"Late private input."}});fireEvent.click(screen.getByRole("button",{name:"Save note"}));await waitFor(()=>expect(mocks.request).toHaveBeenCalledTimes(1));mocks.context.mockResolvedValue({ok:true,data:{user:{id:other,mustChangePassword:false}}});window.dispatchEvent(new Event("math-master:auth-change"));resolve({ok:true,data:{actorId:actor,knowledgeId:"fractions",revision:2,deleted:false,updatedAt:"2026-10-06T11:00:00Z"}});await waitFor(()=>expect(screen.queryByDisplayValue("Late private input.")).not.toBeInTheDocument());expect(screen.queryByText("Note saved.")).not.toBeInTheDocument();view.unmount()});

function mountEditor(){return render(<StudyAccountContext.Provider value={{actorId:actor,invalidate:()=>{}}}><NoteEditor knowledgeId="fractions" initialNote={note}/></StudyAccountContext.Provider>)}
it("reading latest preserves edits typed during the request",async()=>{let finish!:(v:unknown)=>void;mocks.request.mockReturnValue(new Promise(r=>{finish=r}));mountEditor();fireEvent.click(screen.getByRole("button",{name:"Read latest note"}));fireEvent.change(screen.getByLabelText("Personal note"),{target:{value:"New private derivation typed during reading."}});await act(async()=>finish({ok:true,data:{...note,revision:2,body:"Server copy."}}));expect(screen.getByLabelText("Personal note")).toHaveValue("New private derivation typed during reading.");expect(screen.getByText("You have unsaved note edits.")).toBeVisible()});
it("confirming a timed out delete preserves later input and unsaved notice",async()=>{mocks.request.mockResolvedValueOnce({ok:false,status:503,code:"SERVICE_UNAVAILABLE",message:"Service temporarily unavailable.",requestId:"unavailable"}).mockResolvedValueOnce({ok:true,data:{actorId:actor,knowledgeId:"fractions",revision:2,deleted:true,updatedAt:"2026-10-06T11:00:00Z"}});mountEditor();fireEvent.click(screen.getByRole("button",{name:"Delete note"}));await screen.findByRole("button",{name:"Retry same request"});fireEvent.change(screen.getByLabelText("Personal note"),{target:{value:"New note after the uncertain deletion."}});fireEvent.click(screen.getByRole("button",{name:"Retry same request"}));await waitFor(()=>expect(mocks.request).toHaveBeenCalledTimes(2));expect(screen.getByLabelText("Personal note")).toHaveValue("New note after the uncertain deletion.");expect(screen.getByText("You have unsaved note edits.")).toBeVisible();expect(screen.getByText("The earlier request is confirmed. Your new edits are still unsaved.")).toBeVisible()});
it("successful deletion clears the latest comparison",async()=>{mocks.request.mockResolvedValueOnce({ok:true,data:{...note,revision:2,body:"Private latest comparison."}}).mockResolvedValueOnce({ok:true,data:{actorId:actor,knowledgeId:"fractions",revision:3,deleted:true,updatedAt:"2026-10-06T11:00:00Z"}});mountEditor();fireEvent.click(screen.getByRole("button",{name:"Read latest note"}));await screen.findByRole("button",{name:"Use latest note"});fireEvent.click(screen.getByRole("button",{name:"Delete note"}));await screen.findByText("Note deleted.");expect(screen.queryByText("Private latest comparison.")).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Use latest note"})).not.toBeInTheDocument()});
it("late read cannot restore a comparison after successful deletion",async()=>{let finish!:(v:unknown)=>void;mocks.request.mockReturnValueOnce(new Promise(r=>{finish=r})).mockResolvedValueOnce({ok:true,data:{actorId:actor,knowledgeId:"fractions",revision:2,deleted:true,updatedAt:"2026-10-06T11:00:00Z"}});mountEditor();fireEvent.click(screen.getByRole("button",{name:"Read latest note"}));fireEvent.click(screen.getByRole("button",{name:"Delete note"}));await screen.findByText("Note deleted.");await act(async()=>finish({ok:true,data:{...note,body:"Deleted private old copy."}}));expect(screen.getByLabelText("Personal note")).toHaveValue("");expect(screen.queryByText("Deleted private old copy.")).not.toBeInTheDocument()});
