"use client";
import {useContext,useEffect,useRef,useState} from "react";
import {StudyAccountContext} from "./account-boundary";
import {useStudyCommand} from "./pending-command";
import {StudyCommandFeedback} from "./feedback";
import {studyRequest} from "@/lib/study/client";
import {useUiI18n} from "@/lib/i18n/provider";
import {SafeMarkdown} from "@/features/reading/safe-markdown";
import type {NoteView,NoteReceipt} from "@/lib/study/types";
export function NoteEditor({knowledgeId,initialNote,disabled=false}:{knowledgeId:string;initialNote:NoteView;disabled?:boolean}){
 const{t}=useUiI18n(),account=useContext(StudyAccountContext),[body,setBody]=useState(initialNote.body),[revision,setRevision]=useState(initialNote.revision),[ref,setRef]=useState(initialNote.knowledge),[dirty,setDirty]=useState(false),[notice,setNotice]=useState<"saved"|"deleted"|"pendingEdits"|null>(null),[latest,setLatest]=useState<NoteView|null>(null),[reading,setReading]=useState(false),bodyRef=useRef(body),submitted=useRef(body),live=useRef(true),generation=useRef(0);bodyRef.current=body;
 const command=useStudyCommand<NoteReceipt>(receipt=>{setRevision(receipt.revision);if(receipt.deleted){setBody("");bodyRef.current="";setDirty(false);setNotice("deleted")}else if(bodyRef.current===submitted.current){setDirty(false);setNotice("saved")}else{setDirty(true);setNotice("pendingEdits")}});
 useEffect(()=>{live.current=true;const changed=()=>{generation.current++;setBody("");bodyRef.current="";setLatest(null);setDirty(false);setNotice(null)};window.addEventListener("math-master:auth-change",changed);return()=>{live.current=false;generation.current++;window.removeEventListener("math-master:auth-change",changed)}},[]);
 useEffect(()=>{if(!dirty)return;const leave=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=""},navigate=(event:MouseEvent)=>{const target=event.target instanceof Element?event.target.closest("a"):null;if(!target||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey||target.target==="_blank")return;const href=target.getAttribute("href");if(href&&!href.startsWith("#")&&!window.confirm(t("study.note.leave",{}))){event.preventDefault();event.stopPropagation()}};window.addEventListener("beforeunload",leave);document.addEventListener("click",navigate,true);return()=>{window.removeEventListener("beforeunload",leave);document.removeEventListener("click",navigate,true)}},[dirty,t]);
 async function readLatest(){if(!account||reading)return;setReading(true);const g=generation.current;try{const result=await studyRequest<NoteView>({kind:"readNote",id:knowledgeId},undefined,undefined,account.actorId);if(live.current&&g===generation.current&&result.ok&&result.data.actorId===account.actorId){setLatest(result.data);setRevision(result.data.revision);setRef(result.data.knowledge);if(!dirty){setBody(result.data.body);setNotice(null)}}}finally{if(live.current&&g===generation.current)setReading(false)}}
 const editable=!!account&&account.actorId===initialNote.actorId&&!disabled;
 return <section className="panel"><h2>{t("study.note.label",{})}</h2><label>{t("study.note.label",{})}<textarea rows={8} value={body} disabled={!editable||command.busy} onChange={event=>{setBody(event.target.value);setDirty(true);setNotice(null)}}/></label>{dirty&&<p>{t("study.note.unsaved",{})}</p>}<div className="actions"><button type="button" className="button" disabled={!editable||!ref||command.busy||!!command.pending} onClick={()=>{submitted.current=body;void command.run({kind:"saveNote",id:knowledgeId},{expectedRevision:revision,knowledge:ref,body})}}>{t("study.note.save",{})}</button><button type="button" className="button secondary" disabled={!editable||revision===0||command.busy||!!command.pending} onClick={()=>void command.run({kind:"deleteNote",id:knowledgeId},{expectedRevision:revision})}>{t("study.note.delete",{})}</button><button type="button" className="button secondary" disabled={!editable||reading||command.busy||!!command.pending} onClick={()=>void readLatest()}>{t("study.note.latest",{})}</button></div><StudyCommandFeedback command={command}/>{notice&&<p role="status">{t(notice==="saved"?"study.note.saved":notice==="deleted"?"study.note.deleted":"study.note.pendingEdits",{})}</p>}{latest&&<section><h3>{t("study.note.latest",{})}</h3><SafeMarkdown source={latest.body} assets={[]}/><button type="button" className="button secondary" onClick={()=>{setBody(latest.body);setDirty(false);setNotice(null);setLatest(null)}}>{t("study.note.useLatest",{})}</button></section>}<details><summary>{t("study.note.preview",{})}</summary><SafeMarkdown source={body} assets={[]}/></details></section>;
}
