import {validContentString} from "@/lib/content/raw-json";
import type {State} from "@/lib/study/types";
export type StudyPageQuery={mode:"learn"|"review";topicId?:string;state?:State;q?:string;cursor?:string;knowledgeId?:string;kind?:string;from?:string;to?:string;fromDate?:string;toDate?:string;limit:number;offset:number};
const id=/^[a-z][a-z0-9-]{0,63}$/;
export function parseStudyQuery(params:Record<string,string|string[]|undefined>,scope:"learn"|"history"="learn"):StudyPageQuery|null{
 const out:StudyPageQuery={mode:"learn",limit:20,offset:0};const history=scope==="history"||["cursor","from","to","knowledgeId","kind"].some(key=>params[key]!==undefined);const allowed=["mode","topicId","state","q","cursor","knowledgeId","kind","from","to","limit","offset"];
 for(const[key,value]of Object.entries(params)){if(value===undefined)continue;if(!allowed.includes(key)||typeof value!=="string"||!validContentString(value) )return null;if(value===""&&["q","topicId","state","cursor","knowledgeId","kind","from","to"].includes(key))continue;if(value==="")return null;
 switch(key){case "mode":if(value!=="learn"&&value!=="review")return null;out.mode=value;break;case"state":if(!["unlearned","learning","completed","reviewing"].includes(value))return null;out.state=value as State;break;case"q":if(new TextEncoder().encode(value).byteLength>512)return null;out.q=value;break;case"topicId":case"knowledgeId":if(!id.test(value)||key==="topicId"&&!value.startsWith("msc-"))return null;out[key]=value;break;case"cursor":if(value.length>512||!/^[\x20-\x7e]*$/.test(value))return null;out.cursor=value;break;case"kind":if(!["started","completed","review-started","review-finished","note-saved","note-deleted"].includes(value))return null;out.kind=value;break;case"limit":case"offset":if(!/^[0-9]+$/.test(value)||!Number.isSafeInteger(Number(value))||Number(value)<(key==="limit"?1:0)||Number(value)>(key==="limit"?(history?50:100):100000))return null;out[key]=Number(value);break;case"from":case"to":if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const at=new Date(value+"T00:00:00.000Z");if(!Number.isFinite(at.getTime())||at.toISOString().slice(0,10)!==value)return null;out[key+"Date" as "fromDate"|"toDate"]=value;if(key==="to")at.setUTCDate(at.getUTCDate()+1);out[key]=at.toISOString();break;}}
 if(out.from&&out.to&&Date.parse(out.from)>=Date.parse(out.to))return null;return out;
}
export function studyPageURL(base:string,filters:Record<string,string|number|undefined>):string{const q=new URLSearchParams();for(const[k,v]of Object.entries(filters)){if(v!==undefined&&v!=="")q.set(k,String(v))};return base+(q.size?"?"+q:"")}
