"use client";
import {ReportLink} from "@/features/feedback/report-link";
import Link from "next/link";
import {useState} from "react";
import {useRouter} from "next/navigation";
import type {AttemptView,ResultView,Answer} from "@/lib/learning/types";
import {useLearningCommand} from "@/features/learning/pending-command";
import {CommandFeedback} from "@/features/learning/learning-status";
import {AnswerFields,emptyAnswer} from "./answer-fields";
import styles from "@/styles/assessment.module.css";
export function AssessmentPanel({view}:{view:AttemptView}){const router=useRouter(),[summary,setSummary]=useState(view.summary),[values,setValues]=useState<Answer[]>(()=>view.questions.map(emptyAnswer));const submit=useLearningCommand<ResultView>(r=>router.push(`/assessments/${r.summary.id}/result`)),abandon=useLearningCommand<AttemptView>(r=>{setSummary(r.summary);submit.clear();router.refresh()});const active=summary.state==="active",busy=submit.busy||abandon.busy;const edit=(n:number,value:Answer)=>{submit.clear();setValues(v=>v.map((a,i)=>i===n?value:a))};return <section className={styles.panel}><h1>Five-question assessment</h1><p>{summary.mode==="diagnostic"?"Diagnostic assessment":summary.mode==="review"?"Review assessment":"Learning check"} · {summary.state}</p><p>Expires at <time dateTime={summary.expiresAt}>{new Date(summary.expiresAt).toISOString().replace("T"," ").replace(".000Z"," UTC")}</time></p>{!active?<><p>This assessment is {summary.state}.</p>{summary.state==="submitted"&&<Link prefetch={false} href={`/assessments/${summary.id}/result`}>View result</Link>}<p><Link prefetch={false} href={"/knowledge/"+summary.knowledge.id}>Return to the lesson</Link></p></>:<><p>Submit all five answers together. Select Skip for any question you leave unanswered. Refreshing clears unsent answers; the attempt remains available.</p><form onSubmit={e=>{e.preventDefault();void submit.run({kind:"submitAssessment",id:summary.id},{answers:view.questions.map((q,i)=>({position:q.position,instance:q.instance,answer:values[i]}))})}}>{view.questions.map((q,i)=><div key={q.instance.id}><p><ReportLink source={{kind:'assessment',id:summary.id,position:q.position}}/></p>{q.assets.map(a=><p key={a.id}>Illustration {a.id} <ReportLink source={{kind:'assessment',id:summary.id,position:q.position,partKind:'asset',partId:a.id}}/></p>)}<AnswerFields attemptId={summary.id} question={q} value={values[i]} onChange={a=>edit(i,a)} disabled={busy||values[i].kind==="skipped"}/><label className={styles.skip}><input type="checkbox" checked={values[i].kind==="skipped"} disabled={busy} onChange={e=>edit(i,e.target.checked?{kind:"skipped"}:emptyAnswer(q))}/>Skip question {q.position}</label></div>)}<div className={styles.actions}><button type="submit" className="button" disabled={busy||!!submit.pending}>Submit five answers</button><button type="button" className="button secondary" disabled={busy} onClick={()=>void abandon.run({kind:"abandonAssessment",id:summary.id},{})}>Abandon assessment</button></div></form>{submit.pending&&submit.error?.code==="SERVICE_UNAVAILABLE"&&<h2>Result not confirmed</h2>}<CommandFeedback command={submit}/><CommandFeedback command={abandon}/></>}</section>}
