import {test,expect,TEST_PASSWORD,fitsViewport} from './fixtures';import {resolve} from 'node:path';
async function login(page:import('../../frontend/node_modules/@playwright/test').Page,name:string){await page.goto('/login');await page.getByLabel('Username',{exact:true}).fill(name);await page.getByLabel('Password',{exact:true}).fill(TEST_PASSWORD);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/learn$/)}
test('admin uploads and corrects current knowledge without review or versions',async({page,scene})=>{await scene('managed-knowledge');await login(page,'auth_admin');await page.goto('/admin/knowledge');await expect(page.getByRole('banner').getByRole('link',{name:'auth_admin',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Knowledge management',exact:true})).toBeVisible();await expect(page.locator('input[type=file]')).toBeEnabled();await page.locator('input[type=file]').setInputFiles(resolve('../backend/internal/knowledgeadmin/testdata/valid-source.json'));await page.getByRole('button',{name:'Upload and publish',exact:true}).click();await expect(page.getByRole('heading',{name:'Import preview',exact:true})).toBeVisible();await page.getByRole('button',{name:'Apply selected knowledge',exact:true}).click();await expect(page.getByRole('status')).toContainText('Duplicates skipped');await page.getByRole('link',{name:'有理分数',exact:true}).click();await page.getByLabel('Statement',{exact:true}).fill('管理员通过浏览器修正后的知识正文。');await page.getByRole('button',{name:'Save correction',exact:true}).click();await expect(page.getByRole('status')).toContainText('Saved.');const id=page.url().split('/').at(-1)!;await page.goto('/knowledge/'+id);await expect(page.getByText('管理员通过浏览器修正后的知识正文。',{exact:true})).toBeVisible();await expect(page.getByText(/v[0-9]+/)).toHaveCount(0)});
test('ordinary learner cannot open administrator or retired management pages',async({page,scene})=>{await scene('managed-knowledge');await login(page,'auth_learner');await page.goto('/admin/knowledge');await expect(page.locator('input[type=file]')).toHaveCount(0);await page.goto('/editor');await expect(page).toHaveURL(/\/account$/)});
test('uncertain upload retries and recovers the committed receipt',async({page,scene},info)=>{
 await scene('managed-knowledge');await login(page,'auth_admin');await page.goto('/admin/knowledge');await expect(page.getByRole('banner').getByRole('link',{name:'auth_admin',exact:true})).toBeVisible();await expect(page.locator('input[type=file]')).toBeEnabled();await page.locator('input[type=file]').setInputFiles(resolve('../backend/internal/knowledgeadmin/testdata/valid-source.json'));await page.getByRole('button',{name:'Upload and publish',exact:true}).click();await expect(page.getByRole('heading',{name:'Import preview',exact:true})).toBeVisible();
 let key='';await page.route('**/api/v3/admin/knowledge/imports/*/apply',async route=>{key=route.request().headers()['idempotency-key'];const response=await route.fetch();expect(response.status()).toBe(200);await route.abort('failed')},{times:1});
 await page.getByRole('button',{name:'Apply selected knowledge',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'No confirmation'})).toBeVisible();expect(key).not.toBe('');
 await page.getByRole('button',{name:'Retry original request',exact:true}).click();await expect(page.getByRole('status')).toContainText('Duplicates skipped');await expect(page.getByRole('heading',{name:'Import preview',exact:true})).toHaveCount(0);
 await expect(page.locator('input[type=file]')).toBeEnabled();await page.locator('input[type=file]').setInputFiles(resolve('../backend/internal/knowledgeadmin/testdata/valid-source.json'));await page.getByRole('button',{name:'Upload and publish',exact:true}).click();await expect(page.getByRole('heading',{name:'Import preview',exact:true})).toBeVisible();await page.route('**/api/v3/admin/knowledge/imports/*/apply',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);await route.abort('failed')},{times:1});await page.getByRole('button',{name:'Apply selected knowledge',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'No confirmation'})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Check previous import result',exact:true}).click();await expect(page.getByRole('status')).toContainText('Duplicates skipped');
 await expect(page.getByRole('link',{name:'有理分数',exact:true})).toHaveCount(1);await fitsViewport(page);await page.screenshot({path:info.outputPath('knowledge-admin.png'),fullPage:true,mask:[page.locator('input,textarea')]});
});
test('administrator combines topic and difficulty filters',async({page,scene})=>{await scene('managed-knowledge');await login(page,'auth_admin');await page.goto('/admin/knowledge');await expect(page.getByRole('banner').getByRole('link',{name:'auth_admin',exact:true})).toBeVisible();await page.getByLabel('Topics',{exact:true}).fill('97F40');await page.getByLabel('Difficulty',{exact:true}).selectOption('1');await page.getByRole('button',{name:'Search knowledge',exact:true}).click();await expect(page.getByRole('link',{name:'有理分数',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'等值分数',exact:true})).toHaveCount(0);await expect(page.getByLabel('Topics',{exact:true})).toHaveValue('97F40');await expect(page.getByLabel('Difficulty',{exact:true})).toHaveValue('1')});
