import { test, expect, fitsViewport } from "./fixtures";
import { submitDraft, approve, prepare, verifyPassword, actor, wireContent, contentKnowledge, contentPath, originalInput } from "./content-helpers";
import type { PublicationPage, DraftView, SubmissionView } from "../../frontend/src/lib/content/types";
test("contentPublicationReauthCancelActivationAndWithdrawal", async ({ page, scene }) => { await scene("content"); const { submissionID } = await submitDraft(page); await approve(page, submissionID); const candidate = await prepare(page, submissionID); expect((await page.request.get("/api/v1/knowledge/" + contentKnowledge)).status()).toBe(404); await page.getByRole("button", { name: "Activate snapshot" }).click(); await expect(page.getByRole("dialog")).toBeVisible(); await page.getByRole("button", { name: "Cancel", exact: true }).click(); expect((await wireContent<PublicationPage>(page, "/api/v1/content/publications")).data.head).toBe(null); await page.getByRole("button", { name: "Activate snapshot" }).click(); await verifyPassword(page); expect((await wireContent<PublicationPage>(page, "/api/v1/content/publications")).data.head).toBe(null); await page.getByRole("button", { name: "Activate snapshot" }).click(); await expect(page.getByRole("status")).toHaveText(/Snapshot activated/); expect((await wireContent<PublicationPage>(page, "/api/v1/content/publications")).data.head).toBe(candidate.id); await page.context().clearCookies(); await page.goto("/knowledge/" + contentKnowledge); await expect(page.getByRole("heading", { name: "Fractions as rational numbers", exact: true })).toBeVisible(); await page.goto("/paths/" + contentPath); await expect(page.getByRole("heading", { name: "Original rational fractions route", exact: true })).toBeVisible(); await actor(page, "content_admin"); await page.goto("/admin/withdrawals"); await page.getByLabel("Published member").selectOption({ label: "knowledge: " + contentKnowledge + " v1" }); await page.getByLabel("Withdrawal reason").fill("Withdraw this technical fixture and its dependent route."); await page.getByRole("button", { name: "Preview withdrawal" }).click(); await expect(page.getByRole("heading", { name: "Withdrawal preview" })).toBeVisible(); await page.getByRole("button", { name: "Withdraw version", exact: true }).click(); await verifyPassword(page); await page.getByRole("button", { name: "Withdraw version", exact: true }).click(); await expect(page.getByRole("status")).toHaveText(/Withdrawal complete/); await fitsViewport(page); await page.context().clearCookies(); expect((await page.request.get("/api/v1/knowledge/" + contentKnowledge)).status()).toBe(404); expect((await page.request.get("/api/v1/paths/" + contentPath)).status()).toBe(404); });

test("contentLargeHistoryKeepsPublicationPaginationAndWithdrawalUsable",async({page,scene})=>{
 await scene("content");await actor(page,"content_editor");const input=await originalInput();
 for(let i=2;i<100;i++){
  const k=structuredClone(input.package.knowledge[0]);k.id="history-k-"+"x".repeat(50)+String(i).padStart(4,"0");k.title="Technical history node "+i;k.statement="Original technical history-volume definition.";k.relations=[];
  const u=structuredClone(input.package.units[1]);u.id="history-u-"+"x".repeat(50)+String(i).padStart(4,"0");u.knowledge.id=k.id;
  input.package.knowledge.push(k);input.package.units.push(u);input.package.paths[0].nodes.push({id:k.id,version:1});
 }
 const draft=await wireContent<DraftView>(page,"/api/v1/content/drafts","POST",input);expect(draft.status).toBe(201);
 const submission=await wireContent<SubmissionView>(page,"/api/v1/content/drafts/"+draft.data.id+"/submit","POST",{expectedRevision:draft.data.revision,expectedDigest:draft.data.gate.digest});expect(submission.status).toBe(201);
 await approve(page,submission.data.id);const published=await prepare(page,submission.data.id);await page.getByRole("button",{name:"Activate snapshot"}).click();await verifyPassword(page);await page.getByRole("button",{name:"Activate snapshot"}).click();await expect(page.getByRole("status")).toHaveText(/Snapshot activated/);
 await scene("content-expand-history");
 const history=await wireContent<PublicationPage>(page,"/api/v1/content/publications?limit=100");expect(history.status).toBe(200);expect(history.data.items.length).toBeGreaterThan(0);expect(history.data.items.length).toBeLessThan(100);expect(history.data.limit).toBe(history.data.items.length);expect(history.data.total).toBe(101);expect(history.data.head).toBe(published.id);
 await page.goto("/admin/publications");await expect(page.getByRole("heading",{name:"Reviewed publication snapshots"})).toBeVisible();await page.getByRole("button",{name:"Next snapshots"}).click();await expect(page.getByText(/Manifest SHA:/)).toBeVisible();
 await page.goto("/admin/withdrawals");await expect(page.getByLabel("Published member")).toContainText("knowledge: "+contentKnowledge+" v1");await page.getByLabel("Published member").selectOption({label:"knowledge: "+contentKnowledge+" v1"});await page.getByRole("button",{name:"Preview withdrawal"}).click();await expect(page.getByRole("heading",{name:"Withdrawal preview"})).toBeVisible();
 await page.goto("/admin/publications");await page.getByRole("checkbox").check();await page.getByLabel("Publication reason").fill("Prepare an updated technical snapshot after large history.");await page.getByRole("button",{name:"Prepare snapshot"}).click();await expect(page.getByRole("status")).toHaveText(/Snapshot prepared/);await fitsViewport(page);
});
