import { test, expect, fitsViewport } from "./fixtures";
import { submitDraft, approve, actor, wireContent } from "./content-helpers";
import type { DraftView, SubmissionView } from "../../frontend/src/lib/content/types";
test("contentIndependentAccountApprovesFixedBody", async ({ page, scene }) => { await scene("content"); const { submissionID } = await submitDraft(page); await actor(page, "content_reviewer"); await page.goto("/review"); await expect(page.getByRole("link", { name: "e2e-content-math · Version 1" })).toBeVisible(); await page.getByRole("link", { name: "e2e-content-math · Version 1" }).click(); await expect(page.getByRole("button", { name: "Approve submission" })).toBeDisabled(); await expect(page.getByLabel("Knowledge 1 statement")).toHaveCount(0); await expect(page.getByRole("link",{name:"Technical external source"})).toHaveAttribute("href","https://example.org/original-math");
 await expect(page.getByText("prerequisite: e2e-parts-of-a-whole v1",{exact:true})).toBeVisible();
 await expect(page.getByRole("heading",{name:/Original rational fractions route/})).toBeVisible();
 await expect(page.getByRole("heading",{name:"Counterexamples",exact:true}).first()).toBeVisible();
 await approve(page, submissionID); await fitsViewport(page); const fixed = await wireContent<SubmissionView>(page, "/api/v1/content/submissions/" + submissionID); expect(fixed.data.status).toBe("approved"); expect(fixed.data.review?.frozenDigest).toBe(fixed.data.frozen.frozenDigest); });
test("contentReturnRestoresWorkspaceAndPreservesFrozenBody", async ({ page, scene }) => { await scene("content"); const { id, submissionID } = await submitDraft(page); await actor(page, "content_reviewer"); await page.goto("/review/" + submissionID); await page.getByLabel("Review note").fill("Please improve the explanation of nonzero denominators."); await page.getByRole("button", { name: "Return for changes" }).click(); await expect(page.getByRole("heading", { name: "Final review decision" })).toBeVisible(); const before = await wireContent<SubmissionView>(page, "/api/v1/content/submissions/" + submissionID); await actor(page, "content_editor"); await page.goto("/editor/drafts/" + id); await page.getByLabel("Knowledge 1 scope").fill("Changed after the immutable review return."); await page.getByRole("button", { name: "Save draft", exact: true }).click(); await expect(page.getByRole("status")).toHaveText(/Draft saved/); const after = await wireContent<SubmissionView>(page, "/api/v1/content/submissions/" + submissionID); expect(after.data.frozen).toEqual(before.data.frozen); expect(after.data.status).toBe("returned"); });
