import {test,expect,fitsViewport,safeScreenshot} from './fixtures';
import {actor,wireLearning,knowledgeDetail,beginAssessment,beginPractice} from './learning-helpers';
import {apiReport} from './feedback-helpers';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import type {Page} from '../../frontend/node_modules/@playwright/test/index.js';
import type {AttemptView,ResultView,SubmitInput} from '../../frontend/src/lib/learning/types';
const root='natural-numbers';
async function correctAnswers(a:AttemptView,n=5):Promise<SubmitInput>{const bank=JSON.parse(await readFile(resolve(__dirname,'../../content/questions/elementary-foundations-numbers.v1.json'),'utf8'));return {answers:a.questions.map((q,i)=>{if(i>=n)return {position:q.position,instance:q.instance,answer:{kind:'skipped' as const}};const fixed=bank.fixedQuestions.find((f:{id:string})=>f.id===q.instance.id);let choice=fixed?.body.correctChoiceId;if(!choice){const m=/Compare (\d+) and (\d+)/.exec(q.prompt);if(!m)throw Error('Original root prompt mismatch');choice=+m[1]<+m[2]?'lt':+m[1]>+m[2]?'gt':'eq'}return {position:q.position,instance:q.instance,answer:{kind:'choice' as const,choiceId:choice}}})}}
async function submit(page:Page,a:AttemptView,n:number){const input=await correctAnswers(a,n);for(const item of input.answers){if(item.answer.kind==='skipped')await page.getByLabel('Skip question '+item.position,{exact:true}).check();else if(item.answer.kind==='choice') await page.getByRole('group',{name:'Answer for question '+item.position,exact:true}).locator('input[value="'+item.answer.choiceId+'"]').check();else await page.getByLabel('Answer for question '+item.position,{exact:true}).fill(item.answer.raw)}await page.getByRole('button',{name:'Submit five answers',exact:true}).click();await expect(page).toHaveURL(/\/result$/);return wireLearning<ResultView>(page,'/api/v1/learning/assessments/'+a.summary.id+'/result')}
test('three fails, four passes, and exact prerequisites unlock only their descendants',async({page,scene})=>{await scene('content-acceptance');await actor(page,'auth_learner');expect((await knowledgeDetail(page,'factors',2)).state.canEnter).toBe(false);const a=await beginAssessment(page,root);const fail=await submit(page,a,3);expect(fail.data.score).toBe(3);await expect(page.getByText('Failed',{exact:true})).toBeVisible();const b=await beginAssessment(page,root);expect(b.questions.every(q=>!a.questions.some(x=>x.instance.id===q.instance.id))).toBe(true);const pass=await submit(page,b,4);expect(pass.data.score).toBe(4);await expect(page.getByText('Passed',{exact:true})).toBeVisible();expect((await knowledgeDetail(page,'zero')).state.canEnter).toBe(true);expect((await knowledgeDetail(page,'factors',2)).state.canEnter).toBe(false);await fitsViewport(page)});
test('one practice exposure leaves a different five-question assessment available',async({page,scene},info)=>{await scene('content-acceptance');await actor(page,'auth_learner');const p=await beginPractice(page,root);expect((await wireLearning(page,'/api/v1/learning/practice/'+p.summary.id+'/reveal','POST',{})).status).toBe(200);const a=await beginAssessment(page,root);expect(a.questions).toHaveLength(5);expect(a.questions.every(q=>q.instance.id!==p.question.instance.id)).toBe(true);await submit(page,a,4);await fitsViewport(page);await safeScreenshot(page,info,'p6a-practice-pass')});
test('learned state, fixed-version review and explicit retake keep current qualification',async({page,scene},info)=>{await scene('content-acceptance');await actor(page,'auth_learner');await page.goto('/knowledge/'+root);await page.getByRole('button',{name:'Start learning',exact:true}).click();await page.getByRole('button',{name:'Mark as learned',exact:true}).click();await expect(page.getByText('Reading completion recorded.')).toBeVisible();await submit(page,await beginAssessment(page,root),4);const a=await beginAssessment(page,root,'review');await submit(page,a,4);expect((await knowledgeDetail(page,root)).state.qualification).not.toBeNull();await page.goto('/knowledge/equivalent-fractions?version=2');await expect(page.getByText('Version 2',{exact:true}).first()).toBeVisible();await fitsViewport(page);await safeScreenshot(page,info,'p6a-review')});
test('feedback, withdrawal correction and full exposure show truthful readiness',async({page,scene},info)=>{await scene('content-acceptance');await actor(page,'auth_learner');const a=await beginAssessment(page,root);await submit(page,a,4);const ticket=await apiReport(page,'/api/v1/feedback/contexts/knowledge/'+root,'suggestion');expect(ticket.id).toBeTruthy();await actor(page,'content_admin');const list=await wireLearning<{items:{id:string}[]}>(page,'/api/v1/question-bank/submissions?scope=all&status=approved');for(const s of list.data.items)expect((await wireLearning(page,'/api/v1/question-bank/submissions/'+s.id)).status).toBe(200);await page.goto('/knowledge/'+root);await expect(page.getByText('Five eligible questions are not available.',{exact:false})).toBeVisible();await expect(page.getByRole('button',{name:'Start five-question assessment'})).toBeDisabled();await fitsViewport(page);await safeScreenshot(page,info,'p6a-not-ready');await scene('learning-withdraw-first-assessed');await actor(page,'auth_learner');const r=await wireLearning<ResultView>(page,'/api/v1/learning/assessments/'+a.summary.id+'/result');expect(r.data.validity).toBe('restricted');expect(r.data.score).toBe(4)});
