import {expect,TEST_PASSWORD,type Runtime} from './fixtures';
import {actor,wireContent} from './content-helpers';
import type {Page,APIRequestContext} from '../../frontend/node_modules/@playwright/test/index.js';
import type {Envelope,CaseMetadata,Receipt,PlanInput,PlanRef,Mapping,ResultMetadata,Page as MetadataPage} from '../../frontend/src/lib/correction/types';
export {actor};
export const wireCorrection=<T>(page:Page,path:string,method='GET',input?:unknown,key?:string)=>wireContent<Envelope<T>>(page,path,method,input,key);
export type CorrectionState={cases:number;plans:number;jobs:number;results:number;notifications:number;reads:number;rates:number;grants:number;caseId:string|null;plan:PlanRef|null;resultId:string|null;attemptId:string|null;activeAttemptId:string|null;mappings:Mapping[];originalSha:string};
export async function correctionState(request:APIRequestContext,runtime:Runtime):Promise<CorrectionState>{const r=await request.get(runtime.controlURL+'/correction/state',{headers:{Authorization:'Bearer '+runtime.token}});expect(r.status()).toBe(200);return r.json()}
export async function correctionScene(request:APIRequestContext,runtime:Runtime,name:string){const r=await request.post(runtime.controlURL+'/scene/'+name,{headers:{Authorization:'Bearer '+runtime.token},timeout:45000});expect(r.status()).toBe(204)}
export async function reauthenticate(page:Page){const r=await wireContent(page,'/api/v1/auth/reauth','POST',{password:TEST_PASSWORD});expect(r.status).toBe(200)}
export async function apiPlan(page:Page,caseId:string,mappings:Mapping[]=[]){const input:PlanInput={expectedSequence:null,parent:null,algorithmVersion:1,mappings,reason:'Original independently reviewed correction. 中'};const r=await wireCorrection<Receipt>(page,'/api/v1/corrections/cases/'+caseId+'/plans','POST',input);expect(r.status).toBe(201);const p=r.data.data.plan;if(!p)throw Error('Missing actual plan');const sub=await wireCorrection<Receipt>(page,'/api/v1/corrections/plans/'+p.ref.id+'/versions/'+p.ref.version+'/submit','POST',{expectedSequence:p.sequence});expect(sub.status).toBe(200);if(!sub.data.data.plan)throw Error('Missing submitted plan');return sub.data.data.plan}
export async function approvePlan(page:Page,ref:PlanRef,sequence:number){await reauthenticate(page);const r=await wireCorrection<Receipt>(page,'/api/v1/corrections/plans/'+ref.id+'/versions/'+ref.version+'/decision','POST',{expectedSequence:sequence,decision:'approve',reason:'Independently checked exact original answers and mathematical sources.'});expect(r.status).toBe(200);return r.data.data.plan}
export async function ownedResults(page:Page,attemptId:string){const r=await wireCorrection<MetadataPage<ResultMetadata>>(page,'/api/v1/corrections/evidence?kind=assessment&id='+attemptId);expect(r.status).toBe(200);return r.data.data.items}
