import {test,expect,fitsViewport,safeScreenshot} from './fixtures';
import {actor,correctionScene,correctionState,ownedResults} from './correction-helpers';
test('real withdrawal restricts immediately; approved equivalent basis restores current evidence and keeps original history',async({page,request,runtime},info)=>{test.setTimeout(90000);await correctionScene(request,runtime,'correction');const before=await correctionState(request,runtime);expect(before.attemptId).toBeTruthy();await correctionScene(request,runtime,'correction-withdraw-instance');await actor(page,'auth_learner');await page.goto('/assessments/'+before.attemptId+'/result');await expect(page.getByText('Saved result needs review',{exact:true})).toBeVisible();await expect(page.getByText('5 / 5',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Check corrections',exact:true}).click();await expect(page.getByText('No correction results yet.',{exact:true})).toBeVisible();await correctionScene(request,runtime,'correction-publish-equivalent');await correctionScene(request,runtime,'correction-approve-equivalent');await correctionScene(request,runtime,'correction-run');const results=await ownedResults(page,before.attemptId!);const current=results.find(r=>r.status==='corrected_passed');expect(current?.score).toBe(5);expect(current?.validity).toBe('effective');await page.goto('/corrections/'+current!.id);await expect(page.getByText('Score: 5/5 · Passed',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Original result',exact:true})).toHaveAttribute('href','/assessments/'+before.attemptId+'/result');await page.getByRole('button',{name:'Review corrected answers',exact:true}).click();await expect(page.getByText('Original answer:',{exact:false})).toHaveCount(5);await page.goto('/knowledge/learning-root');await expect(page.getByRole('link',{name:'View corrected qualification',exact:true})).toHaveAttribute('href','/corrections/'+current!.id);await page.goto('/learning-history');await expect(page.getByRole('link',{name:'View attempt',exact:true})).toHaveCount(1);await page.goto('/notifications');await expect(page.getByRole('button',{name:'Mark as read',exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'Mark as read',exact:true}).first().click();await expect(page.getByText(/^Read ·/).first()).toBeVisible();const after=await correctionState(request,runtime);expect(after.originalSha).toBe(before.originalSha);expect(after.grants).toBe(1);await fitsViewport(page);await safeScreenshot(page,info,'correction-notifications')});
test('an approved plan with no exact withdrawn mapping honestly requires retaking',async({page,request,runtime},info)=>{test.setTimeout(90000);await correctionScene(request,runtime,'correction');const before=await correctionState(request,runtime);await correctionScene(request,runtime,'correction-withdraw-instance');await correctionScene(request,runtime,'correction-approve-empty');await correctionScene(request,runtime,'correction-run');await actor(page,'auth_learner');const results=await ownedResults(page,before.attemptId!);const current=results.find(r=>r.status==='retake_required');expect(current).toBeTruthy();expect(current?.score).toBeNull();await page.goto('/corrections/'+current!.id);await expect(page.getByText('Retake required',{exact:true})).toBeVisible();await expect(page.getByText('Score:',{exact:false})).toHaveCount(0);await expect(page.getByRole('button',{name:'Review corrected answers',exact:true})).toHaveCount(0);expect((await correctionState(request,runtime)).originalSha).toBe(before.originalSha);await fitsViewport(page);await safeScreenshot(page,info,'correction-retake')});

test('corrected template illustrations load through owned effective results and stop after replacement withdrawal',async({page,request,runtime},info)=>{
 test.setTimeout(90000);await correctionScene(request,runtime,'correction');const before=await correctionState(request,runtime);
 await correctionScene(request,runtime,'correction-withdraw-template');await correctionScene(request,runtime,'correction-publish-equivalent');await correctionScene(request,runtime,'correction-approve-equivalent');await correctionScene(request,runtime,'correction-run');await actor(page,'auth_learner');
 const current=(await ownedResults(page,before.attemptId!)).find(r=>r.status==='corrected_passed');expect(current?.validity).toBe('effective');await page.goto('/corrections/'+current!.id);await page.getByRole('button',{name:'Review corrected answers',exact:true}).click();
 const images=page.getByRole('img',{name:'Question illustration',exact:true});await expect(images).toHaveCount(5);await expect.poll(()=>images.evaluateAll(nodes=>nodes.every(n=>(n as HTMLImageElement).complete&&(n as HTMLImageElement).naturalWidth>0))).toBe(true);
 const urls=await images.evaluateAll(nodes=>nodes.map(n=>(n as HTMLImageElement).getAttribute('src')!));for(const url of urls){expect(url).toMatch(new RegExp('^/api/v1/corrections/results/'+current!.id+'/assets/[0-9a-f]{64}$'));const response=await page.request.get(url);expect(response.status()).toBe(200);expect(response.headers()['cache-control']).toBe('private, no-store')}
 await fitsViewport(page);await safeScreenshot(page,info,'correction-effective-illustrations');await correctionScene(request,runtime,'correction-withdraw-replacement');for(const url of urls)expect((await page.request.get(url)).status()).toBe(404);expect((await correctionState(request,runtime)).originalSha).toBe(before.originalSha);
});
