import {expect,type Runtime} from './fixtures';
import {actor,wireContent} from './content-helpers';
import type {Page,APIRequestContext} from '../../frontend/node_modules/@playwright/test/index.js';
import type {Context,Envelope,Metadata,Receipt,Resolution,DiscussionPage} from '../../frontend/src/lib/feedback/types';
export {actor};
export async function wireFeedback<T>(page:Page,path:string,method='GET',input?:unknown,key?:string){return wireContent<Envelope<T>>(page,path,method,input,key)}
export type FeedbackState={tickets:number;events:number;rates:number;ticketId:string;withdrawalId:string|null;replacement:Extract<Resolution,{kind:'revision_published'}>['replacement']|null};
export async function feedbackState(request:APIRequestContext,runtime:Runtime):Promise<FeedbackState>{const r=await request.get(runtime.controlURL+'/feedback/state',{headers:{Authorization:'Bearer '+runtime.token}});expect(r.status()).toBe(200);return r.json()}
export async function feedbackScene(request:APIRequestContext,runtime:Runtime,name:string){const r=await request.post(runtime.controlURL+'/scene/'+name,{headers:{Authorization:'Bearer '+runtime.token},timeout:40000});expect(r.status()).toBe(204)}
export async function report(page:Page,url='/feedback/new?kind=site&area=other',title='Original English report with 中文 mathematical context',message='Please explain this original mathematical detail. 中\nSecond line.'){await page.goto(url);await page.getByLabel('Title',{exact:true}).fill(title);await page.getByLabel('Details',{exact:true}).fill(message);await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page).toHaveURL(/\/feedback\/[0-9a-f-]+$/);await expect(page.getByText('New',{exact:true})).toBeVisible();return page.url().split('/').pop()!}
export async function apiReport(page:Page,path:string,category='suggestion'){const c=await wireFeedback<Context>(page,path);expect(c.status).toBe(200);const r=await wireFeedback<Receipt>(page,'/api/v1/feedback/tickets','POST',{target:c.data.data.target,source:c.data.data.source,category,title:'Original private report',message:'Original details.',location:''});expect(r.status).toBe(201);return r.data.data.ticket}
export async function handleReport(page:Page,id:string,status:Metadata['status'],message='Independent handling reply.',basis?:Resolution['kind'],fill?:(page:Page)=>Promise<void>){await page.goto('/review/feedback/'+id);await page.getByLabel('Report status',{exact:true}).selectOption(status);await page.getByLabel('Review reply',{exact:true}).fill(message);if(basis)await page.getByLabel('Resolution basis',{exact:true}).selectOption(basis);if(fill)await fill(page);await page.getByRole('button',{name:'Save handling result',exact:true}).click();await expect(page.getByLabel('Review reply',{exact:true})).toHaveValue('');}
export async function discussion(page:Page,id:string,review=false){return wireFeedback<DiscussionPage>(page,'/api/v1/feedback/'+(review?'review/':'')+'tickets/'+id+'/events?limit=50')}
