import {test,expect,fitsViewport,safeScreenshot} from './fixtures';
import {actor,report,handleReport,feedbackState,feedbackScene} from './feedback-helpers';
import {beginPractice,beginAssessment,wireLearning} from './learning-helpers';
test('real lesson parts, path, own practice, fifth assessment item and site retain exact source',async({page,scene},info)=>{test.setTimeout(90000);await scene('feedback');await actor(page,'auth_learner');await page.goto('/knowledge/learning-root');const unit=page.locator('a[href*="partKind=unit"]').first();await expect(unit).toBeVisible();await report(page,(await unit.getAttribute('href'))!);await page.goto('/paths/learning-route');await expect(page.getByRole('link',{name:'Report a problem',exact:true})).toBeVisible();await report(page,(await page.getByRole('link',{name:'Report a problem',exact:true}).getAttribute('href'))!);const p=await beginPractice(page);const asset=page.locator('a[href*="kind=practice"][href*="partKind=asset"]').first();await expect(asset).toBeVisible();await report(page,(await asset.getAttribute('href'))!);expect((await wireLearning(page,'/api/v1/learning/practice/'+p.summary.id+'/abandon','POST',{})).status).toBe(200);const a=await beginAssessment(page);const fifth=page.locator('a[href*="kind=assessment"][href*="position=5"]').first();await expect(fifth).toBeVisible();await report(page,(await fifth.getAttribute('href'))!);expect((await wireLearning(page,'/api/v1/learning/assessments/'+a.summary.id+'/abandon','POST',{})).status).toBe(200);await report(page);await page.goto('/feedback');await expect(page.getByRole('heading',{name:'My reports',exact:true})).toBeVisible();await expect(page.locator('main li,section li').filter({has:page.locator('[data-feedback-status]')})).toHaveCount(5);await fitsViewport(page);await safeScreenshot(page,info,'feedback-real-sources')});
test('waiting details and terminal objections reopen with current metadata',async({page,scene},info)=>{test.setTimeout(60000);await scene('feedback');await actor(page,'auth_learner');const id=await report(page);await actor(page,'content_reviewer');await handleReport(page,id,'waiting_details');await expect(page.locator('[data-feedback-status="waiting_details"]')).toBeVisible();await actor(page,'auth_learner');await page.goto('/feedback/'+id);await page.getByLabel('Additional details',{exact:true}).fill('Original additional detail. 中');await page.getByRole('button',{name:'Reload report status',exact:true}).click();await expect(page.getByLabel('Additional details',{exact:true})).toHaveValue('Original additional detail. 中');await page.getByRole('button',{name:'Add details',exact:true}).click();await expect(page.locator('[data-feedback-status="processing"]')).toBeVisible();await actor(page,'content_reviewer');await handleReport(page,id,'closed','Suggestion recorded independently.','suggestion_recorded');await actor(page,'auth_learner');await page.goto('/feedback/'+id);await page.getByLabel('Additional details',{exact:true}).fill('I have a further question.');await page.getByRole('button',{name:'Add details',exact:true}).click();await expect(page.locator('[data-feedback-status="processing"]')).toBeVisible();await fitsViewport(page);await safeScreenshot(page,info,'feedback-reopened')});
test('discussion pagination stays bounded after fifty events',async({page,scene,request,runtime},info)=>{test.setTimeout(60000);await scene('feedback');await feedbackScene(request,runtime,'feedback-history');const state=await feedbackState(request,runtime);expect(state.events).toBe(61);await actor(page,'learning_other');await page.goto('/feedback/'+state.ticketId);await page.getByRole('button',{name:'Read discussion',exact:true}).click();await expect(page.locator('article')).toHaveCount(50);await page.getByRole('button',{name:'Next discussion page',exact:true}).click();await expect(page.locator('article')).toHaveCount(11);await expect(page.locator('article').first()).toContainText('Event 51');await expect(page.locator('article').last()).toContainText('Event 61');await fitsViewport(page);await safeScreenshot(page,info,'feedback-history')});
test('feedback outage preserves public server-rendered lesson',async({page,scene})=>{await scene('feedback');await actor(page,'auth_learner');await scene('feedback-unavailable');await page.goto('/knowledge/learning-root');await expect(page.getByRole('heading',{name:'Addition basics',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Report a problem',exact:true}).first()).toBeVisible();await page.getByRole('link',{name:'Report a problem',exact:true}).first().click();await expect(page.locator('#main-content').getByRole('alert')).toContainText('temporarily unavailable');await page.goto('/knowledge/learning-root');await expect(page.getByRole('heading',{name:'Addition basics',exact:true})).toBeVisible();await fitsViewport(page)});

test('maximum Chinese body and long English title remain plain text and fit the screen',async({page,scene},info)=>{test.setTimeout(60000);await scene('feedback');await actor(page,'auth_learner');const suffix='\n<img src="x">\n',body='中'.repeat(4000-[...suffix].length)+suffix,title='Original mathematical explanation with assumptions, examples and alternative approaches for review. 中文';await report(page,'/feedback/new?kind=site&area=other',title,body);await page.getByRole('button',{name:'Read discussion',exact:true}).click();await expect(page.getByText(title,{exact:true})).toBeVisible();await expect(page.locator('article')).toContainText(body.trim());await expect(page.locator('#main-content img')).toHaveCount(0);await fitsViewport(page);await safeScreenshot(page,info,'feedback-long-text')});

test('temporary client identity failure recovers through the offered Reload page action',async({page,scene},info)=>{
 await scene('feedback');await actor(page,'auth_learner');let unavailable=true;
 await page.route('**/api/v1/auth/context',async route=>{if(unavailable)await route.abort();else await route.continue();});
 await page.goto('/feedback/new?kind=site&area=other');await expect(page.locator('#main-content').getByRole('alert')).toContainText('temporarily unavailable');
 unavailable=false;await page.getByRole('button',{name:'Reload page',exact:true}).click();await expect(page.getByLabel('Title',{exact:true})).toHaveValue('');await expect(page.locator('#main-content').getByRole('alert')).toHaveCount(0);
 await fitsViewport(page);await safeScreenshot(page,info,'feedback-identity-recovery');
});

test('a real new publication refreshes a stale target without losing the draft or sending automatically',async({page,scene,request,runtime},info)=>{
 test.setTimeout(90000);await scene('feedback');await actor(page,'auth_learner');await page.goto('/feedback/new?kind=path&id=learning-route');
 await expect(page.getByText('path learning-route · v1',{exact:true})).toBeVisible();
 await page.getByLabel('Title',{exact:true}).fill('Retained original route report');await page.getByLabel('Details',{exact:true}).fill('中'.repeat(4000));
 await scene('learning-new-route');await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page.locator('#main-content').getByRole('alert')).toContainText('source changed');
 const failed=await feedbackState(request,runtime);expect([failed.tickets,failed.events]).toEqual([1,1]);
 await page.getByRole('button',{name:'Refresh report target',exact:true}).click();await expect(page.getByText('path learning-route · v2',{exact:true})).toBeVisible();
 await expect(page.getByLabel('Title',{exact:true})).toHaveValue('Retained original route report');await expect(page.getByLabel('Details',{exact:true})).toHaveValue('中'.repeat(4000));
 const refreshed=await feedbackState(request,runtime);expect([refreshed.tickets,refreshed.events,refreshed.rates]).toEqual([failed.tickets,failed.events,failed.rates]);
 await fitsViewport(page);await safeScreenshot(page,info,'feedback-refreshed-target');
 await page.getByRole('button',{name:'Submit report',exact:true}).click();await expect(page).toHaveURL(/\/feedback\/[0-9a-f-]+$/);await expect(page.getByText('path learning-route · v2',{exact:true})).toBeVisible();
 const saved=await feedbackState(request,runtime);expect([saved.tickets,saved.events]).toEqual([2,2]);
});
