import { test, expect, fitsViewport, safeScreenshot, TEST_PASSWORD } from "./fixtures";
import { createQuestion, submitQuestion, approveQuestion, prepareQuestion, wireQuestion, actor, questionKnowledge } from "./question-helpers";
import type { DraftView, SubmissionView } from "../../frontend/src/lib/question/types";
test("questionAuthoringRealStackAndResponsiveFrozenPages", async ({ page, scene }, info) => {
    await scene("question");
    const { id } = await createQuestion(page);
    await expect(page.getByLabel("Template 1 family")).toHaveValue("rational_arithmetic");
    await expect(page.getByLabel("Template 2 family")).toHaveValue("rational_comparison");
    await expect(page.getByLabel("Template 3 family")).toHaveValue("missing_operand");
    await page.getByRole("button", { name: "Load published objectives" }).first().click();
    await expect(page.getByText("Fractions as rational numbers · 分数")).toBeVisible();
    await expect(page.getByText("0: Represent one half as a rational number.")).toBeVisible();
    await page.getByRole("button", { name: "Validate saved revision" }).click();
    await expect(page.getByText("Machine checks passed. Independent review is required.")).toBeVisible();
    await expect(page.getByText(/Independently verified instances: 10/).first()).toBeVisible();
    await fitsViewport(page);
    await safeScreenshot(page, info, "question-authoring");
    await page.getByRole("button", { name: "Submit for review" }).click();
    await expect(page.getByRole("status")).toHaveText(/frozen for independent review/);
    const r = await wireQuestion<{
        items: SubmissionView[];
    }>(page, "/api/v1/question-bank/submissions?scope=mine");
    expect(r.status).toBe(200);
    await page.goto("/review/questions/" + r.data.items[0].id);
    await expect(page.locator(".katex").first()).toBeVisible();
    await expect(page.getByText("Authors cannot review their own or inherited questions.")).toBeVisible();
    await expect(page.getByRole("button", { name: "Approve submission" })).toHaveCount(0);
    await page.getByRole("button", { name: "Next instances" }).click();
    await expect(page.getByText(/Offset 20/)).toBeVisible();
    await fitsViewport(page);
    await safeScreenshot(page, info, "question-frozen-review");
});
test("questionPublicationKeyboardDialogAndResponsiveDiff", async ({ page, scene }, info) => { await scene("question"); const d = await submitQuestion(page); await approveQuestion(page, d.submissionID); await prepareQuestion(page, d.submissionID); await fitsViewport(page); await page.getByRole("button", { name: "Activate snapshot" }).click(); await expect(page.getByRole("dialog")).toBeVisible(); const password = page.getByLabel("Your password", { exact: true }); await expect(password).toBeFocused(); await page.keyboard.press("Shift+Tab"); await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeFocused(); await page.keyboard.press("Tab"); await expect(password).toBeFocused(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog")).toHaveCount(0); await expect(page.getByRole("button", { name: "Retry previous request" })).toBeFocused(); await page.getByRole("button", { name: "Retry previous request" }).click(); await expect(page.getByRole("dialog")).toBeVisible(); await password.fill(TEST_PASSWORD); await page.getByRole("button", { name: "Verify password" }).click(); await expect(page.getByRole("dialog")).toHaveCount(0); await page.getByRole("button", { name: "Retry previous request" }).click(); await expect(page.getByRole("status")).toHaveText(/Snapshot activated/); await expect(page.getByText("Published snapshots changed. Refresh both heads and prepare a new snapshot.")).toHaveCount(0); await page.goto("/admin/question-publications"); await expect(page.getByText("Ready for five questions")).toBeVisible(); await fitsViewport(page); await safeScreenshot(page, info, "question-publication"); await page.goto("/admin/question-withdrawals"); await page.getByLabel("Target ID").fill("rational-addition"); await page.getByRole("button", { name: "Preview withdrawal" }).click(); await expect(page.getByText("Affected instances: 10")).toBeVisible(); await fitsViewport(page); await safeScreenshot(page, info, "question-withdrawal"); });
import { originalQuestionInput, questionState, wireCreateQuestion } from "./question-helpers";
test("questionWrongAnswersParameterRangeAndConflictKeepInput", async ({ page, scene, request, runtime }) => {
    await scene("question");
    const d = await createQuestion(page), current = await wireQuestion<DraftView>(page, "/api/v1/question-bank/drafts/" + d.id);
    const saved = await wireQuestion<DraftView>(page, "/api/v1/question-bank/drafts/" + d.id, "PUT", { ...d.input, expectedRevision: current.data.revision });
    expect(saved.status).toBe(200);
    await page.getByLabel("Template 1 prompt").fill("Keep my unsaved original prompt {{left}} + {{right}}.");
    await page.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(page.locator("p[role=alert]")).toHaveText(/draft has changed/i);
    await expect(page.getByLabel("Template 1 prompt")).toHaveValue("Keep my unsaved original prompt {{left}} + {{right}}.");
    await page.getByRole("button", { name: "Reload saved version" }).click();
    await page.getByLabel("Template 1 parameter 1 values").fill("1".repeat(129));
    await page.getByRole("button", { name: "Save draft", exact: true }).click();
    await expect(page.getByRole("status")).toHaveText(/Draft saved/);
    await page.getByRole("button", { name: "Validate saved revision" }).click();
    await expect(page.getByText("Questions need work before submission.")).toBeVisible();
    await expect(page.getByRole("button", { name: "Submit for review" })).toBeDisabled();
    const input = await originalQuestionInput();
    input.questionPackage.id = "e2e-wrong-answer";
    input.questionPackage.templates = [];
    input.questionPackage.blueprints = [];
    input.questionPackage.fixedQuestions = [{ id: "e2e-wrong-fixed", version: 1, body: { type: "numeric", knowledge: { id: questionKnowledge, version: 1 }, coverage: [{ knowledge: { id: questionKnowledge, version: 1 }, objectiveIndices: [0] }], units: [], prompt: "Calculate $1+2$.", explanation: "Add exact rational numbers.", answerFormat: "rational", choices: [], correctChoiceId: null, correctNumeric: { numerator: "2", denominator: "1" }, witness: { engine: { family: "rational_arithmetic", operation: "add", unknownSide: null, generatorVersion: 1, verifierVersion: 1 }, parameters: [{ name: "left", value: "1" }, { name: "right", value: "2" }] }, assets: [], sources: d.input.questionPackage.templates[0].sources } }];
    const wrong = await wireCreateQuestion(page, input);
    const gate = await wireQuestion<{
        readyToSubmit: boolean;
        completenessErrors: {code:string}[];
    }>(page, `/api/v1/question-bank/drafts/${wrong.id}/validate`, "POST", { expectedRevision: 1 });
    expect(gate.status).toBe(200);
    expect(gate.data.readyToSubmit).toBe(false);
    expect(gate.data.completenessErrors.some(e=>e.code==="FIXED_ANSWER_NOT_VERIFIED")).toBe(true);
    const state = await questionState(request, runtime);
    expect(state.submissions).toBe(0);
    expect(state.events.saveDraft).toBe(3);
});
test("questionCLIImportAdoptionDoesNotCreateApproval", async ({ page, scene, request, runtime }) => { await scene("question"); await scene("question-cli-import"); await actor(page, "content_editor"); await page.goto("/editor/questions"); await page.getByLabel("New question package ID").fill("elementary-rationals"); await page.getByLabel("Adoption reason").fill("Take responsibility for this original imported technical question draft."); await page.getByRole("button", { name: "Adopt package" }).click(); await expect(page).toHaveURL(/\/editor\/questions\/drafts\/[0-9a-f-]+$/); await expect(page.getByText("Verify historical authorship and original sources before approval.")).toBeVisible(); const state = await questionState(request, runtime); expect(state.workspaces).toBe(1); expect(state.submissions).toBe(0); expect(state.reviews).toBe(0); expect(state.head).toBeNull(); });
