import { test, expect } from "./fixtures";
import { createQuestion, actor, wireQuestion, questionState, originalQuestionInput } from "./question-helpers";
import type { DraftView } from "../../frontend/src/lib/question/types";
test("questionLearnerPrivate404RoleRevocationAndMissingMigration", async ({ page, scene, request, runtime }) => { await scene("question"); const d = await createQuestion(page); await actor(page, "content_editor_two"); expect((await wireQuestion(page, "/api/v1/question-bank/drafts/" + d.id)).status).toBe(404); await actor(page, "auth_learner"); const denied = await wireQuestion(page, "/api/v1/question-bank/drafts/" + d.id); expect(denied.status).toBe(403); expect(JSON.stringify(denied.data)).not.toContain("prompt"); await page.goto("/review/questions"); await expect(page.getByRole("heading", { name: "You do not have permission." })).toBeVisible(); await actor(page, "content_editor"); await scene("question-revoke-editor"); expect((await wireQuestion(page, "/api/v1/question-bank/drafts/" + d.id, "PUT", { ...d.input, expectedRevision: 2 })).status).toBe(401); await actor(page,"content_editor"); expect((await wireQuestion(page,"/api/v1/question-bank/drafts/"+d.id,"PUT",{...d.input,expectedRevision:2})).status).toBe(403); await scene("question-migration-missing"); expect((await wireQuestion(page, "/api/v1/question-bank/drafts")).status).toBe(503); expect((await wireQuestion(page, "/api/v1/knowledge/e2e-question-fractions")).status).toBe(200); await scene("question-migration-recover"); expect((await questionState(request, runtime)).events.saveDraft).toBe(1); });
for (const stop of ["timeout", "cancel"] as const)
    test("questionUnconfirmedWriteManualSameKeyReplay-" + stop, async ({ page, scene, request, runtime }) => { await scene("question"); const d = await createQuestion(page); const writes: {
        body: string | null;
        key: string | undefined;
    }[] = []; page.on("request", r => { if (r.method() === "PUT" && r.url().includes("/api/v1/question-bank/drafts/"))
        writes.push({ body: r.postData(), key: r.headers()["idempotency-key"] }); }); await scene("question-hold-next-save"); await page.getByLabel("Template 1 prompt").fill("Keep the exact pending request {{left}} + {{right}}."); await page.getByRole("button", { name: "Save draft", exact: true }).click(); await expect.poll(async () => (await questionState(request, runtime)).maxRevision).toBe(3); if (stop === "cancel")
        await page.getByRole("button", { name: "Stop waiting" }).click(); await expect(page.getByText(/The result is unconfirmed/)).toBeVisible({ timeout: 12000 }); await expect(page.getByLabel("Template 1 prompt")).toBeDisabled(); await page.waitForTimeout(250); expect(writes).toHaveLength(1); await page.getByRole("button", { name: "Retry previous request" }).click(); await expect(page.getByRole("status")).toHaveText(/Draft saved/); expect(writes).toHaveLength(2); expect(writes[1]).toEqual(writes[0]); const state = await questionState(request, runtime); expect(state.maxRevision).toBe(3); expect(state.events.saveDraft).toBe(2); });
test("questionSharedActualSlotsAndEnvelopeBudget", async ({ page, scene }) => { await scene("question"); const d = await createQuestion(page); await scene("question-hold-slots"); try {
    expect((await wireQuestion(page, `/api/v1/question-bank/drafts/${d.id}/validate`, "POST", { expectedRevision: 2 })).status).toBe(503);
    expect((await wireQuestion(page, "/api/v1/content/drafts", "POST", {catalogueVersion:1,package:{schemaVersion:1,id:"e2e-shared-slot",version:1,knowledge:[],units:[],paths:[],assets:[]},assetBytes:[],sourceMap:[]})).status).toBe(429);
    expect((await wireQuestion(page, "/api/v1/question-bank/drafts/" + d.id)).status).toBe(200);
}
finally {
    await scene("question-release-slots");
} ; expect((await wireQuestion(page, `/api/v1/question-bank/drafts/${d.id}/validate`, "POST", { expectedRevision: 2 })).status).toBe(200); const input = await originalQuestionInput(); input.questionPackage.templates[0].promptTemplate = "x".repeat(4 * 1024 * 1024); expect((await wireQuestion(page, "/api/v1/question-bank/drafts", "POST", input)).status).toBe(413); });
