import { test, expect } from "./fixtures";
import { submitQuestion, approveQuestion, prepareQuestion, activateQuestion, wireQuestion, questionState, wirePrepareQuestion, wireActivateQuestion, wireReauth, actor, originalQuestionInput, wireSubmitQuestion } from "./question-helpers";
import type { SubmissionView, InstancePage, WithdrawalPreview, WithdrawalResult, CoverageReport, MemberPage, DraftView } from "../../frontend/src/lib/question/types";
for (const kind of ["instance", "template"] as const)
    test("questionAtomicPermanentWithdrawal-" + kind, async ({ page, scene, request, runtime }) => { await scene("question"); const d = await submitQuestion(page); await approveQuestion(page, d.submissionID); await prepareQuestion(page, d.submissionID); await activateQuestion(page); const items = await wireQuestion<InstancePage>(page, `/api/v1/question-bank/submissions/${d.submissionID}/instances?limit=100`); expect(items.status).toBe(200); const target = { kind, id: kind === "instance" ? items.data.items[0].identity.id : "rational-addition", version: 1 }; const p = await wireQuestion<WithdrawalPreview>(page, "/api/v1/question-bank/withdrawals/preview?limit=1", "POST", { target }); expect(p.status).toBe(200); expect(p.data.affectedInstances).toBe(kind === "instance" ? 1 : 10); expect(p.data.changes.items).toHaveLength(1); const key = crypto.randomUUID(), input = { target, expectedKnowledgeHead: p.data.currentKnowledgeHead, expectedQuestionHead: p.data.currentQuestionHead, reason: "Permanently withdraw this exact technical fixture version." }; const out = await wireQuestion<WithdrawalResult>(page, "/api/v1/question-bank/withdrawals", "POST", input, key); expect(out.status).toBe(201); const replay = await wireQuestion<WithdrawalResult>(page, "/api/v1/question-bank/withdrawals", "POST", input, key); expect(replay.status).toBe(201); expect(replay.data).toEqual(out.data); const coverage = await wireQuestion<CoverageReport>(page, "/api/v1/question-bank/coverage"); expect(coverage.status).toBe(200); expect(coverage.data.effectiveInstances).toBe(kind === "instance" ? 27 : 18); expect(coverage.data.nodes.items[0].ready).toBe(kind === "instance"); const state = await questionState(request, runtime); expect(state.withdrawals).toBe(1); expect(state.events.withdrawVersion).toBe(1); expect(state.head).toBe(out.data.publication.id); expect(state.manifestSha).toBe(out.data.publication.manifestSha); const frozen = await wireQuestion<SubmissionView>(page, "/api/v1/question-bank/submissions/" + d.submissionID); expect(frozen.data.frozen.instanceIdentities).toHaveLength(28); });
test("questionEitherHeadMakesPreparedActivationStale", async ({ page, scene, request, runtime }) => { await scene("question"); const d = await submitQuestion(page); await approveQuestion(page, d.submissionID); const first = await prepareQuestion(page, d.submissionID), second = await wirePrepareQuestion(page, d.submissionID); await wireReauth(page); expect((await wireActivateQuestion(page, first)).status).toBe(200); expect((await wireActivateQuestion(page, second)).status).toBe(409); const third = await wirePrepareQuestion(page, d.submissionID); await scene("question-advance-knowledge"); const stale = await wireActivateQuestion(page, third); expect(stale.status).toBe(409); expect((stale.data as unknown as {
    error: {
        code: string;
    };
}).error.code).toBe("QUESTION_PUBLICATION_STALE"); expect((await questionState(request, runtime)).head).toBe(first.id); });
test("questionTemplateReplacementRetiresInstancesWithoutPermanentWithdrawal", async ({ page, scene, request, runtime }) => { await scene("question"); const d = await submitQuestion(page); await approveQuestion(page, d.submissionID); await prepareQuestion(page, d.submissionID); await activateQuestion(page); const old = await wireQuestion<SubmissionView>(page, "/api/v1/question-bank/submissions/" + d.submissionID); await actor(page, "content_editor"); const revised = await wireQuestion<DraftView>(page, `/api/v1/question-bank/submissions/${d.submissionID}/revision`, "POST", {}); expect(revised.status).toBe(201); const input = await originalQuestionInput(); input.questionPackage.version = 2; input.questionPackage.templates[0].version = 2; input.questionPackage.templates[0].explanationTemplate = "The new original explanation gives {{answer}} exactly."; input.questionPackage.blueprints[0].version = 2; input.questionPackage.blueprints[0].sources[0].ref.version = 2; const saved = await wireQuestion<DraftView>(page, `/api/v1/question-bank/drafts/${revised.data.id}`, "PUT", { ...input, expectedRevision: 1 }); expect(saved.status).toBe(200); const sub = await wireSubmitQuestion(page, revised.data.id, saved.data.revision); await approveQuestion(page, sub.id); await actor(page, "content_admin"); const next = await wirePrepareQuestion(page, sub.id); await wireReauth(page); expect((await wireActivateQuestion(page, next)).status).toBe(200); const members = await wireQuestion<MemberPage>(page, `/api/v1/question-bank/publications/${next.id}/members?limit=100`); expect(members.status).toBe(200); expect(members.data.items.some(m => m.identity.kind === "template" && m.identity.id === "rational-addition" && m.identity.version === 2)).toBe(true); const oldIDs = new Set(old.data.frozen.instanceIdentities.map(i => i.id)); expect(members.data.items.filter(m => m.identity.kind === "instance" && oldIDs.has(m.identity.id))).toHaveLength(18); expect((await questionState(request, runtime)).withdrawals).toBe(0); const retained = await wireQuestion<SubmissionView>(page, "/api/v1/question-bank/submissions/" + d.submissionID); expect(retained.data.frozen).toEqual(old.data.frozen); });
