import {test,expect,TEST_PASSWORD,NEW_PASSWORD,signIn} from "./fixtures";
async function login(page:import("../../frontend/node_modules/@playwright/test").Page,name:string){await page.goto("/login");await page.getByLabel("Username",{exact:true}).fill(name);await page.getByLabel("Password",{exact:true}).fill(TEST_PASSWORD);await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(/\/learn$/)}
test("SSR and anonymous reads never start study and another actor cannot read private notes",async({page,request,browser,scene,baseURL})=>{await scene("topic-study");await page.goto("/knowledge/learning-root");expect(await page.getByRole("button",{name:"Complete learning"}).count()).toBe(0);expect((await request.get("/api/v2/study/overview")).status()).toBe(401);await login(page,"auth_learner");const before=await page.request.get("/learning-history");expect(before.status()).toBe(200);await page.goto("/knowledge/learning-root");await expect(page.getByRole("button",{name:"Complete learning"})).toBeEnabled();await page.getByLabel("Personal note",{exact:true}).fill("Private isolated actor note.");await page.getByRole("button",{name:"Save note",exact:true}).click();await expect(page.getByText("Note saved.",{exact:true})).toBeVisible();const context=await browser.newContext({baseURL,viewport:page.viewportSize()!});try{const other=await context.newPage();await login(other,"content_admin");const response=await other.request.get("/api/v2/study/knowledge/learning-root/note");expect(response.status()).toBe(404);expect((await response.text())).not.toContain("Private isolated actor note.")}finally{await context.close()}});
test("lost begin confirmation retries the same key without another event",async({page,scene})=>{await scene("topic-study");await login(page,"auth_learner");await scene("study-hold-next-write");const keys:string[]=[];page.on("request",r=>{if(r.url().endsWith("/api/v2/study/knowledge/learning-root/begin"))keys.push(r.headers()["idempotency-key"])});await page.goto("/knowledge/learning-root");await expect(page.getByRole("button",{name:"Retry same request"})).toBeVisible({timeout:15000});await page.getByRole("button",{name:"Retry same request"}).click();await expect(page.getByRole("button",{name:"Complete learning"})).toBeEnabled();expect(keys).toHaveLength(2);expect(keys[1]).toBe(keys[0]);const history=await page.request.get("/api/v2/study/history?kind=started");expect(history.status()).toBe(200);expect((await history.json()).items).toHaveLength(1)});

test("revoked sessions and a forced password change remove the previous private input",async({page,browser,scene,baseURL})=>{
 await scene("topic-study");await login(page,"auth_learner");await page.goto("/knowledge/learning-root");await expect(page.getByRole("button",{name:"Complete learning"})).toBeEnabled();await page.getByLabel("Personal note",{exact:true}).fill("Unsaved private input before revocation.");
 const context=await browser.newContext({baseURL,viewport:page.viewportSize()!});try{
  const other=await context.newPage();await signIn(other,"auth_learner",TEST_PASSWORD);await other.getByRole("button",{name:"Sign out everywhere",exact:true}).click();await expect(other).toHaveURL(/\/$/);await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.getByLabel("Personal note",{exact:true})).toHaveCount(0);
  await login(page,"auth_learner");await page.goto("/knowledge/learning-root");await expect(page.getByRole("button",{name:"Complete learning"})).toBeEnabled();await page.getByLabel("Personal note",{exact:true}).fill("Unsaved private input before forced password.");
  await signIn(other,"auth_admin",TEST_PASSWORD);await other.goto("/admin/users");await other.getByRole("button",{name:"auth_learner learner",exact:true}).click();await other.getByLabel("Reason",{exact:true}).fill("Test owner verification");await other.getByLabel("Ownership verification").fill("Synthetic offline verification");await other.getByLabel("Temporary password").fill(NEW_PASSWORD);await other.getByRole("button",{name:"Reset password",exact:true}).click();await expect(other.getByRole("dialog")).toBeVisible();await other.getByLabel("Your password",{exact:true}).fill(TEST_PASSWORD);await other.getByRole("button",{name:"Verify password",exact:true}).click();await expect(other.getByText("Password verified. Submit your change again.")).toBeVisible();await other.getByLabel("Temporary password").fill(NEW_PASSWORD);await other.getByRole("button",{name:"Reset password",exact:true}).click();await expect(other.getByText("Changes saved.")).toBeVisible();
  await page.evaluate(()=>window.dispatchEvent(new Event("focus")));await expect(page.getByLabel("Personal note",{exact:true})).toHaveCount(0);await signIn(page,"auth_learner",NEW_PASSWORD);await expect(page.getByText("Change your password to continue",{exact:true})).toBeVisible();await page.goto("/knowledge/learning-root");await expect(page.getByRole("button",{name:"Complete learning"})).toHaveCount(0);expect((await page.request.get("/api/v2/study/overview")).status()).toBe(403);
 }finally{await context.close()}
});
