import {test,expect,fitsViewport} from "./fixtures";
import {actor,recordReading,beginAssessment,fillAnswers,learningState,knowledgeDetail,beginPractice,rootKnowledge,wireLearning,arithmeticAnswer} from "./learning-helpers";
test("Chinese answer entry retains attempt, then four correct preserve the qualification rule",async({page,scene,request,runtime})=>{
 await scene("learning-basic");await actor(page,"auth_learner");await recordReading(page);const a=await beginAssessment(page,rootKnowledge,"node");const before=await learningState(request,runtime);await page.getByLabel("Answer for question 1").fill("1/2");const writes:string[]=[];page.on("request",r=>{if(!["GET","HEAD"].includes(r.method()))writes.push(r.url());});await page.getByRole("button",{name:"中文",exact:true}).click();await expect(page.getByLabel("第 1 题答案")).toHaveValue("1/2");await expect(page).toHaveURL("/assessments/"+a.summary.id);expect(writes).toEqual([]);expect(await learningState(request,runtime)).toEqual(before);await expect(page.getByText(/正确答案：/)).toHaveCount(0);await fitsViewport(page);
 await page.getByRole("button",{name:"English",exact:true}).click();await fillAnswers(page,a,4);await page.getByRole("button",{name:"中文",exact:true}).click();await page.getByRole("button",{name:"提交五题答案",exact:true}).click();await expect(page).toHaveURL(/\/result$/);await expect(page.getByText("4 / 5",{exact:true})).toBeVisible();await expect(page.getByText("已通过",{exact:true})).toBeVisible();expect((await knowledgeDetail(page,"learning-middle")).state.canEnter).toBe(true);await page.goto("/learning-history");await expect(page.getByRole("heading",{name:"学习历史",exact:true})).toBeVisible();await fitsViewport(page);
});
test("Chinese practice errors follow language and preserve raw answer with no qualification",async({page,scene,request,runtime})=>{
 await scene("learning-basic");await actor(page,"auth_learner");const p=await beginPractice(page);await page.getByLabel("Answer for question 1").fill("1/0");await page.getByRole("button",{name:"Submit answer",exact:true}).click();await expect(page.getByText("Check the requested answer format.",{exact:true})).toBeVisible();await page.getByRole("button",{name:"中文",exact:true}).click();await expect(page.getByText("请检查要求的答案格式。",{exact:true})).toBeVisible();await expect(page.getByLabel("第 1 题答案")).toHaveValue("1/0");const raw="  "+arithmeticAnswer(p.question.prompt)+" / 1 ";await page.getByLabel("第 1 题答案").fill(raw);await page.getByRole("button",{name:"提交答案",exact:true}).click();await expect(page.getByText("正确",{exact:true})).toBeVisible();const saved=await wireLearning<any>(page,"/api/v1/learning/practice/"+p.summary.id);expect(saved.data.result.item.answer).toEqual({kind:"numeric",raw});expect((await learningState(request,runtime)).qualifications).toBe(0);await fitsViewport(page);
});
