import {test,expect,TEST_PASSWORD,fitsViewport,safeScreenshot} from './fixtures';import {createHash} from 'node:crypto';
const id='k-'+createHash('sha256').update('demo-rational-fraction').digest('hex').slice(0,56);
test('editing waits for hydration and preserves replacement text through a locale change',async({page,scene})=>{
 await scene('managed-knowledge');await page.goto('/login');
 await page.getByLabel('Username',{exact:true}).fill('auth_admin');await page.getByLabel('Password',{exact:true}).fill(TEST_PASSWORD);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/learn$/);
 let release!:()=>void;const blocked=new Promise<void>(resolve=>{release=resolve});const scripts=/\/_next\/static\/.*\.js(?:\?.*)?$/;
 await page.route(scripts,async route=>{await blocked;await route.continue()});
 try{
  await page.goto('/admin/knowledge/'+id,{waitUntil:'commit'});
  await expect(page.getByLabel('Statement',{exact:true})).toBeVisible();
  await expect(page.getByLabel('Statement',{exact:true})).toBeDisabled();
  release();await expect(page.getByLabel('Statement',{exact:true})).toBeEnabled();
  await page.getByLabel('Statement',{exact:true}).fill('水合完成后替换的完整数学正文。');
  await page.getByRole('button',{name:'中文',exact:true}).click();
  await expect(page.getByLabel('知识正文',{exact:true})).toHaveValue('水合完成后替换的完整数学正文。');
 }finally{release();await page.unroute(scripts)}
});
test('current management and private learning translate while retaining mathematical input',async({page,scene})=>{await scene('managed-knowledge');await page.goto('/login');await page.getByLabel('Username',{exact:true}).fill('auth_admin');await page.getByLabel('Password',{exact:true}).fill(TEST_PASSWORD);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/learn$/);await page.goto('/admin/knowledge/'+id);await page.getByLabel('Statement',{exact:true}).fill('保留数学正文 x + y = y + x。');await page.getByRole('button',{name:'中文',exact:true}).click();await expect(page.getByLabel('知识正文',{exact:true})).toHaveValue('保留数学正文 x + y = y + x。');await page.getByRole('button',{name:'English',exact:true}).click();await expect(page.getByLabel('Statement',{exact:true})).toHaveValue('保留数学正文 x + y = y + x。');await page.goto('/knowledge/'+id);await page.getByLabel('Private note',{exact:true}).fill('私人数学笔记保持不变。');await page.getByRole('button',{name:'中文',exact:true}).click();await expect(page.getByLabel('私人笔记',{exact:true})).toHaveValue('私人数学笔记保持不变。');await page.getByRole('button',{name:'保存笔记',exact:true}).click();await expect(page.getByText('笔记已保存。',{exact:true})).toBeVisible();await page.goto('/learning-history');await expect(page.getByRole('heading',{name:'学习历史',exact:true})).toBeVisible();await page.getByRole('button',{name:'English',exact:true}).click();await expect(page.getByRole('heading',{name:'Learning history',exact:true})).toBeVisible();await page.goto('/knowledge');await expect(page.getByRole('heading',{name:'Knowledge map',exact:true})).toBeVisible();
 await expect(page.locator('main a[href="/topics/00-XX"] h3')).toHaveText('Original fixture theme 00-XX');
 await page.getByRole('button',{name:'中文',exact:true}).click();await expect(page.locator('main a[href="/topics/00-XX"] h3')).toHaveText('原创主题 00-XX');
 await page.locator('main a[href="/topics/00-XX"]').click();await expect(page.getByRole('heading',{name:'原创主题 00-XX',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'English',exact:true}).click();await expect(page.getByRole('heading',{name:'Original fixture theme 00-XX',exact:true})).toBeVisible();
 await expect(page.locator('main a[href="/topics/00Axx"] h3')).toHaveText('Original fixture subtheme 00Axx');await fitsViewport(page)});

test('my learning names themes, preserves filters and reflects real completion and review',async({page,scene},info)=>{
 await scene('managed-knowledge');await page.goto('/login');
 await page.getByLabel('Username',{exact:true}).fill('auth_learner');await page.getByLabel('Password',{exact:true}).fill(TEST_PASSWORD);
 await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/learn$/);
 await expect(page.getByRole('heading',{name:'Knowledge points',exact:true})).toBeVisible();
 const english=page.getByRole('navigation',{name:'Learn by theme',exact:true});
 await expect(english.getByRole('link',{name:/Original fixture theme 97-XX/})).toBeVisible();
 await expect(page.getByRole('region',{name:'Learning overview',exact:true}).locator('dl [data-state="unlearned"] dd')).toHaveText('2');
 await page.getByRole('searchbox',{name:'Search knowledge',exact:true}).fill('保留搜索');
 await page.getByRole('button',{name:'中文',exact:true}).click();
 await expect(page.getByRole('searchbox',{name:'搜索知识点',exact:true})).toHaveValue('保留搜索');
 const chinese=page.getByRole('navigation',{name:'按主题学习',exact:true});
 await expect(chinese.getByRole('link',{name:/原创主题 97-XX/})).toBeVisible();
 await expect(page.getByRole('link',{name:'有理分数',exact:true})).toBeVisible();
 await expect(chinese.getByRole('progressbar')).toHaveAccessibleName('原创主题 97-XX：已完成 0 / 2');
 await fitsViewport(page);await safeScreenshot(page,info,'my-learning-chinese');
 await page.goto('/knowledge/'+id);
 await page.getByRole('button',{name:'开始学习',exact:true}).click();await page.getByRole('button',{name:'完成学习',exact:true}).click();
 await expect(page.getByText('已完成',{exact:true})).toBeVisible();
 await page.goto('/learn');
 await expect(page.getByRole('region',{name:'学习概览',exact:true}).locator('dl [data-state="completed"] dd')).toHaveText('1');
 await expect(chinese.getByRole('progressbar')).toHaveAccessibleName('原创主题 97-XX：已完成 1 / 2');
 await page.goto('/knowledge/'+id);await page.getByRole('button',{name:'开始复习',exact:true}).click();
 await expect(page.getByRole('button',{name:'结束复习',exact:true})).toBeVisible();
 await page.goto('/learn?q=有理&state=reviewing&mode=review');
 await chinese.getByRole('link',{name:/原创主题 97-XX/}).click();
 await expect(page).toHaveURL(/topicKey=97-XX/);
 const url=new URL(page.url());expect(Object.fromEntries(url.searchParams)).toEqual({q:'有理',topicKey:'97-XX',state:'reviewing',mode:'review'});
 await expect(page.getByRole('region',{name:'学习概览',exact:true}).locator('dl [data-state="reviewing"] dd')).toHaveText('1');
 await expect(chinese.getByRole('progressbar')).toHaveAccessibleName('原创主题 97-XX：已完成 1 / 2');
 await expect(page.getByRole('region',{name:'检索已学知识复习',exact:true}).getByRole('link',{name:'有理分数',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'English',exact:true}).click();
 await expect(page.getByRole('combobox',{name:'Theme',exact:true})).toHaveValue('97-XX');
 await expect(page.getByRole('searchbox',{name:'Search knowledge',exact:true})).toHaveValue('有理');
 await expect(page.getByRole('region',{name:'Review studied knowledge',exact:true}).getByRole('link',{name:'Rational fraction',exact:true})).toBeVisible();
 await fitsViewport(page);
 await page.goto('/learn?topicKey=97');await expect(page.getByRole('combobox',{name:'Theme',exact:true})).toHaveValue('97-XX');
 await page.goto('/learn?topicKey=msc-97f');await expect(page.getByRole('combobox',{name:'Theme',exact:true})).toHaveValue('97Fxx');
 await expect(page.getByRole('option',{name:'Original fixture subtheme 97Fxx',exact:true})).toBeAttached();
});
