import {test,expect,TEST_PASSWORD,NEW_PASSWORD,signIn,fitsViewport} from "./fixtures";
test("Chinese registration, existing errors, login and sign out",async({page,scene})=>{
 await scene("auth");await page.goto("/register");await page.getByRole("button",{name:"中文",exact:true}).click();await page.getByLabel("用户名",{exact:true}).fill("ui_language_learner");await page.getByLabel("密码",{exact:true}).fill(TEST_PASSWORD);await page.getByRole("button",{name:"注册账户",exact:true}).click();await expect(page).toHaveURL(/\/login$/);await expect(page).toHaveTitle("登录 | Math Master");
 await page.getByLabel("用户名",{exact:true}).fill("ui_language_learner");await page.getByLabel("密码",{exact:true}).fill(NEW_PASSWORD);await page.getByRole("button",{name:"登录",exact:true}).click();await expect(page.locator("p[role=alert]")).toHaveText("用户名或密码错误。");await page.getByRole("button",{name:"English",exact:true}).click();await expect(page.locator("p[role=alert]")).toHaveText("Invalid username or password.");
 await page.getByLabel("Password",{exact:true}).fill(TEST_PASSWORD);await page.getByRole("button",{name:"Sign in",exact:true}).click();await expect(page).toHaveURL(/\/learn$/);await page.goto("/account");await page.getByRole("button",{name:"中文",exact:true}).click();await fitsViewport(page);await page.getByRole("button",{name:"退出登录",exact:true}).click();await expect(page).toHaveURL("/");
});
test("password modal switch retains credentials, reason, roles and original commands",async({page,scene})=>{
 await scene("auth");await signIn(page,"auth_admin",TEST_PASSWORD);await page.goto("/admin/users");await page.getByRole("button",{name:"auth_learner learner",exact:true}).click();await page.getByLabel("reviewer",{exact:true}).check();await page.getByLabel("Reason",{exact:true}).fill("Save draft is an unchanged user reason");await page.getByRole("button",{name:"Save roles",exact:true}).click();
 const dialog=page.getByRole("dialog");await expect(dialog).toBeVisible();const password=dialog.locator("#verify-password");await password.fill(TEST_PASSWORD);
 const commands:string[]=[];const listener=(r:any)=>{if(!["GET","HEAD"].includes(r.method()))commands.push(r.url());};page.on("request",listener);
 await dialog.getByRole("button",{name:"中文",exact:true}).click();await expect(password).toHaveValue(TEST_PASSWORD);await expect(page.locator("#role-reason")).toHaveValue("Save draft is an unchanged user reason");await expect(page.getByLabel("审核者",{exact:true})).toBeChecked();expect(commands).toEqual([]);page.off("request",listener);
 await password.focus();await page.keyboard.press("Shift+Tab");await expect(dialog.getByRole("button",{name:"取消",exact:true})).toBeFocused();await page.keyboard.press("Tab");await expect(password).toBeFocused();await dialog.getByRole("button",{name:"验证密码",exact:true}).click();await expect(dialog).toHaveCount(0);await page.getByRole("button",{name:"保存角色",exact:true}).click();await expect(page.getByText("更改已保存。",{exact:true})).toBeVisible();await fitsViewport(page);
});
