import {test,expect,fitsViewport,TEST_PASSWORD} from "./fixtures";
import {createQuestion,submitQuestion,prepareQuestion,questionState,wireQuestion} from "./question-helpers";
import {grantAdministratorReview} from "./content-helpers";
import type {DraftView} from "../../frontend/src/lib/question/types";
test("Chinese question authoring preserves prompts and original exact parameters",async({page,scene})=>{
 await scene("question");const d=await createQuestion(page);const original=await wireQuestion<DraftView>(page,"/api/v1/question-bank/drafts/"+d.id);const prompt=page.getByRole("textbox",{name:"Template 1 prompt",exact:true});await prompt.fill("Save draft {{left}} + {{right}}.");const promptID=await prompt.getAttribute("id");
 const writes:string[]=[];page.on("request",r=>{if(!["GET","HEAD"].includes(r.method()))writes.push(r.url());});await page.getByRole("button",{name:"中文",exact:true}).click();await expect(page.locator('[id="'+promptID+'"]')).toHaveValue("Save draft {{left}} + {{right}}.");expect(writes).toEqual([]);await expect(page.getByRole("option",{name:"数值题",exact:true}).first()).toHaveValue("numeric");
 const response=page.waitForResponse(r=>r.request().method()==="PUT"&&new URL(r.url()).pathname==="/api/v1/question-bank/drafts/"+d.id);await page.getByRole("button",{name:"保存草稿",exact:true}).click();expect((await response).status()).toBe(200);await expect(page.getByRole("status")).toHaveText(/草稿已保存/);const saved=await wireQuestion<DraftView>(page,"/api/v1/question-bank/drafts/"+d.id);expect(saved.data.questionPackage.templates[0].parameters).toEqual(original.data.questionPackage.templates[0].parameters);expect(saved.data.questionPackage.templates[0].promptTemplate).toBe("Save draft {{left}} + {{right}}.");await page.getByRole("button",{name:"校验已保存修订",exact:true}).click();await expect(page.getByText("自动检查已通过，仍需审核者批准。",{exact:true})).toBeVisible();await fitsViewport(page);
});
test("Chinese question self-review and reauthentication keep fixed evidence and original retry",async({page,scene,request,runtime})=>{
 await scene("question");const d=await submitQuestion(page);await grantAdministratorReview(page);await page.goto("/review/questions/"+d.submissionID);await page.getByRole("checkbox").first().check();await page.getByRole("button",{name:"中文",exact:true}).click();await expect(page.getByRole("checkbox").first()).toBeChecked();await expect(page.getByRole("heading",{name:"管理员自审",exact:true})).toBeVisible();for(const check of await page.getByRole("checkbox").all())await check.check();await page.getByLabel("审核责任声明").fill("Administrator self-review: original question source and all finite instances inspected.");await page.getByLabel("审核说明").fill("Save draft is an unchanged review note for this fixed test batch.");await page.getByRole("button",{name:"批准提交",exact:true}).click();await expect(page.getByRole("heading",{name:"管理员自审决定",exact:true})).toBeVisible();await expect(page.getByText("Save draft is an unchanged review note for this fixed test batch.",{exact:true})).toBeVisible();await fitsViewport(page);
 await prepareQuestion(page,d.submissionID);await page.getByRole("button",{name:"Activate snapshot",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel("Your password",{exact:true}).fill(TEST_PASSWORD);await dialog.getByRole("button",{name:"中文",exact:true}).click();await expect(dialog.getByLabel("你的密码",{exact:true})).toHaveValue(TEST_PASSWORD);await dialog.getByRole("button",{name:"验证密码",exact:true}).click();await expect(dialog).toHaveCount(0);expect((await questionState(request,runtime)).head).toBeNull();await page.getByRole("button",{name:"重试上次请求",exact:true}).click();await expect(page.getByRole("status")).toHaveText(/快照已激活/);const state=await questionState(request,runtime);expect(state.head).not.toBeNull();expect(state.events.decideReview).toBe(1);
});
