import {test,expect,fitsViewport,TEST_PASSWORD} from './fixtures';
import {actor,correctionScene,correctionState,wireCorrection} from './correction-helpers';
test('Chinese correction preserves independent approval and modal draft input',async({page,request,runtime})=>{
 test.setTimeout(90000);await correctionScene(request,runtime,'correction');await correctionScene(request,runtime,'correction-rule-case');const state=await correctionState(request,runtime);await actor(page,'content_admin');await page.goto('/review/corrections/'+state.caseId);await page.getByLabel('Plan reason',{exact:true}).fill('Save draft is original user reason for exact rational grading.');// Inject one valid protocol failure to exercise the existing optional reauthentication dialog.
 let requirePassword=true;await page.route('**/api/v1/corrections/cases/*/plans',async route=>{if(requirePassword&&route.request().method()==='POST'){requirePassword=false;const requestId='a'.repeat(32);await route.fulfill({status:428,headers:{'content-type':'application/json','x-request-id':requestId,'cache-control':'private, no-store','x-content-type-options':'nosniff'},body:JSON.stringify({error:{code:'REAUTHENTICATION_REQUIRED',message:'Confirm your password before continuing.',requestId}})});}else await route.continue();});
 await page.getByRole('button',{name:'Create correction plan',exact:true}).click();await page.getByRole('button',{name:'Verify your password',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await dialog.getByLabel('Your password',{exact:true}).fill(TEST_PASSWORD);await dialog.getByRole('button',{name:'中文',exact:true}).click();await expect(dialog.getByLabel('你的密码',{exact:true})).toHaveValue(TEST_PASSWORD);await dialog.getByRole('button',{name:'验证密码',exact:true}).click();await expect(dialog).toHaveCount(0);await page.getByRole('button',{name:'重试同一请求',exact:true}).click();await page.getByRole('link',{name:'打开纠错方案',exact:true}).click();await page.getByRole('button',{name:'阅读方案详情',exact:true}).click();await page.getByRole('button',{name:'提交独立审核',exact:true}).click();await expect(page.getByText('序号 2',{exact:true})).toBeVisible();const pending=await correctionState(request,runtime);expect((await wireCorrection(page,'/api/v1/corrections/plans/'+pending.plan!.id+'/versions/1/decision','POST',{expectedSequence:2,decision:'approve',reason:'Self approval remains forbidden in Chinese.'})).status).toBe(403);
 await actor(page,'content_reviewer');await page.goto('/review/corrections/'+state.caseId+'/plans/'+pending.plan!.id+'/1');await page.getByRole('button',{name:'Read plan details',exact:true}).click();await page.getByLabel('Independent review reason',{exact:true}).fill('Independent reviewer verified original exact rational grading.');await page.getByRole('button',{name:'中文',exact:true}).click();await page.getByRole('button',{name:'批准纠错',exact:true}).click();await expect(page.getByText('序号 3',{exact:true})).toBeVisible();await fitsViewport(page);
});
test('Chinese notification toggles do not mark read or expose details',async({page,request,runtime})=>{
 test.setTimeout(90000);await correctionScene(request,runtime,'correction');await correctionScene(request,runtime,'correction-rule-case');await actor(page,'auth_learner');await page.goto('/notifications');const before=await correctionState(request,runtime);await page.getByRole('button',{name:'中文',exact:true}).click();await expect(page.getByRole('heading',{name:'通知',exact:true})).toBeVisible();expect((await correctionState(request,runtime)).reads).toBe(before.reads);await page.getByRole('button',{name:'English',exact:true}).click();expect((await correctionState(request,runtime)).reads).toBe(before.reads);await fitsViewport(page);
});
