import {test,expect,fitsViewport,TEST_PASSWORD} from "./fixtures";
import {createDraft,submitDraft,grantAdministratorReview,prepare,wireContent,contentKnowledge} from "./content-helpers";
import type {DraftView} from "../../frontend/src/lib/content/types";
test("Chinese dirty editing and saved reader preserve original content",async({page,scene})=>{
 await scene("content");const {id}=await createDraft(page);const before=await wireContent<DraftView>(page,"/api/v1/content/drafts/"+id);
 const input=page.getByLabel("Knowledge 1 statement");await input.fill("Save draft — unchanged user mathematical prose");const inputId=await input.getAttribute("id");
 const writes:string[]=[];page.on("request",r=>{if(!["GET","HEAD"].includes(r.method()))writes.push(r.url());});await page.getByRole("button",{name:"中文",exact:true}).click();await expect(page.locator('[id="'+inputId+'"]')).toHaveValue("Save draft — unchanged user mathematical prose");expect(writes).toEqual([]);await expect(page.getByRole("option",{name:"定义",exact:true}).first()).toHaveValue("definition");const savedResponse=page.waitForResponse(r=>new URL(r.url()).pathname==="/api/v1/content/drafts/"+id&&r.request().method()==="PUT");await page.getByRole("button",{name:"保存草稿",exact:true}).click();expect((await savedResponse).status()).toBe(200);await expect(page.getByRole("status")).toHaveText(/草稿已保存/);
 const saved=await wireContent<DraftView>(page,"/api/v1/content/drafts/"+id);expect(saved.data.sourceMap).toEqual(before.data.sourceMap);expect(saved.data.package.knowledge[0].statement).toBe("Save draft — unchanged user mathematical prose");await page.getByRole("link",{name:"阅读已保存草稿",exact:true}).click();await expect(page.getByRole("heading",{name:"阅读知识草稿",exact:true})).toBeVisible();await expect(page.getByText("Save draft — unchanged user mathematical prose",{exact:true})).toBeVisible();await fitsViewport(page);
});
test("Chinese administrator self-review, modal, activation and withdrawal preserve authorization",async({page,scene})=>{
 await scene("content");const {submissionID}=await submitDraft(page);await grantAdministratorReview(page);await page.goto("/review/"+submissionID);await page.getByLabel("Mathematics",{exact:true}).check();await page.getByRole("button",{name:"中文",exact:true}).click();await expect(page.getByLabel("数学正确性",{exact:true})).toBeChecked();await expect(page.getByRole("heading",{name:"管理员自审",exact:true})).toBeVisible();
 for(const label of ["讲解","知识关系","来源","配图"])await page.getByLabel(label,{exact:true}).check();await page.getByLabel("审核责任声明").fill("Administrator self-review: Save draft remains original user prose.");await page.getByLabel("审核说明").fill("All checks completed for isolated original test content.");await page.getByRole("button",{name:"批准提交",exact:true}).click();await expect(page.getByRole("heading",{name:"管理员自审决定"})).toBeVisible();await fitsViewport(page);
 await prepare(page,submissionID);await page.getByRole("button",{name:"中文",exact:true}).click();await page.getByRole("button",{name:"激活快照",exact:true}).click();const dialog=page.getByRole("dialog");await dialog.getByLabel("你的密码",{exact:true}).fill(TEST_PASSWORD);await dialog.getByRole("button",{name:"English",exact:true}).click();await expect(dialog.getByLabel("Your password",{exact:true})).toHaveValue(TEST_PASSWORD);await dialog.getByRole("button",{name:"Verify password",exact:true}).click();await expect(dialog).toHaveCount(0);expect((await page.request.get("/api/v1/knowledge/"+contentKnowledge)).status()).toBe(404);await page.getByRole("button",{name:"中文",exact:true}).click();await page.getByRole("button",{name:"激活快照",exact:true}).click();await expect(page.getByRole("status")).toHaveText(/快照已激活/);expect((await page.request.get("/api/v1/knowledge/"+contentKnowledge)).status()).toBe(200);
 await page.goto("/admin/withdrawals");await page.getByLabel("已发布成员").selectOption("0");await page.getByLabel("撤回理由").fill("Withdraw isolated technical fixture after Chinese review.");await page.getByRole("button",{name:"预览撤回影响",exact:true}).click();await expect(page.getByRole("heading",{name:"撤回预览"})).toBeVisible();await page.getByRole("button",{name:"撤回版本",exact:true}).click();await expect(page.getByRole("status")).toHaveText(/撤回已完成/);await fitsViewport(page);
});
