import { z } from 'zod';
import { parseContentJSON,validContentString } from '../content/raw-json';
import { readContentBytes } from '../content/bytes';
import { FeedbackRequestError,feedbackPolicies,type FeedbackRoute,type FeedbackErrorCode,type FeedbackAction,type Envelope } from './types';
export const feedbackUUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const mathID=/^[a-z][a-z0-9-]{0,63}$/,instanceID=/^(?:[a-z][a-z0-9-]{0,63}|qi-[0-9a-f]{64})$/,uuid=z.string().regex(feedbackUUID),id=z.string().regex(mathID),sha=z.string().regex(/^[0-9a-f]{64}$/),seq=z.number().int().min(1).max(Number.MAX_SAFE_INTEGER);
const scalar=(max:number,min=1)=>z.string().refine(v=>validContentString(v)&&[...v].length>=min&&[...v].length<=max&&(v===''&&min===0||v.replace(/^\p{White_Space}+|\p{White_Space}+$/gu,'')!==''));
const identity=z.object({id,version:z.number().int().min(1).max(2147483647),sha256:sha}).strict(),instanceIdentity=identity.extend({id:z.string().regex(instanceID)}).strict(),asset=z.object({id,sha256:sha}).strict();
const statuses=['new','processing','waiting_details','resolved','closed'] as const,categories=['math_error','unclear_explanation','typo','accessibility','technical_issue','suggestion'] as const,areas=['home','knowledge_map','learning_center','account','review','other'] as const,kinds=['clarified','withdrawn','revision_published','service_fixed','duplicate','not_reproducible','out_of_scope','suggestion_recorded'] as const;
const unitPart=z.object({kind:z.literal('unit'),unit:identity,asset:z.null()}).strict(),assetPart=z.object({kind:z.literal('asset'),unit:z.null(),asset}).strict();
export const targetSchema=z.discriminatedUnion('kind',[z.object({kind:z.literal('site'),identity:z.null(),area:z.enum(areas),part:z.null()}).strict(),z.object({kind:z.literal('knowledge'),identity,area:z.null(),part:z.union([unitPart,assetPart]).nullable()}).strict(),z.object({kind:z.literal('path'),identity,area:z.null(),part:z.null()}).strict(),z.object({kind:z.literal('instance'),identity:instanceIdentity,area:z.null(),part:assetPart.nullable()}).strict()]);
const sourceSchema=z.discriminatedUnion('kind',[z.object({kind:z.literal('site'),publicationId:z.null(),attemptId:z.null(),position:z.null()}).strict(),z.object({kind:z.literal('publication'),publicationId:uuid,attemptId:z.null(),position:z.null()}).strict(),z.object({kind:z.literal('practice'),publicationId:z.null(),attemptId:uuid,position:z.literal(1)}).strict(),z.object({kind:z.literal('assessment'),publicationId:z.null(),attemptId:uuid,position:z.number().int().min(1).max(5)}).strict()]);
const targetSource=(v:{target:z.infer<typeof targetSchema>;source:z.infer<typeof sourceSchema>})=>v.target.kind==='site'?v.source.kind==='site':v.target.kind==='instance'?['practice','assessment'].includes(v.source.kind):v.source.kind==='publication';
export function feedbackLabel(t:z.infer<typeof targetSchema>):string{if(t.kind==='site')return 'Site · '+t.area;let label=`${t.kind} ${t.identity.id} · v${t.identity.version}`;if(t.part?.kind==='unit')label+=` · unit ${t.part.unit.id} v${t.part.unit.version}`;if(t.part?.kind==='asset')label+=' · asset '+t.part.asset.id;return label}
const create=z.object({target:targetSchema,source:sourceSchema,category:z.enum(categories),title:scalar(120),message:scalar(4000),location:scalar(400,0)}).strict().refine(v=>targetSource(v)&&(v.target.kind!=='site'||!['math_error','unclear_explanation'].includes(v.category)));
const reply=z.object({expectedSequence:seq,message:scalar(4000)}).strict();
const withdrawal=z.object({space:z.enum(['content','question']),id:uuid}).strict();
const replacement=z.union([z.object({kind:z.enum(['knowledge','path','unit']),identity,asset:z.null(),publicationId:uuid}).strict(),z.object({kind:z.literal('instance'),identity:instanceIdentity,asset:z.null(),publicationId:uuid}).strict(),z.object({kind:z.literal('asset'),identity:z.null(),asset,publicationId:uuid}).strict()]);
const resolutionBase={kind:z.enum(kinds),withdrawal:withdrawal.nullable(),replacement:replacement.nullable(),duplicateOf:uuid.nullable()};
function resolutionShape(v:z.infer<ReturnType<typeof resolutionObject>>,view=false):boolean{switch(v.kind){case 'withdrawn':return v.withdrawal!==null&&v.replacement===null&&v.duplicateOf===null;case 'revision_published':return v.withdrawal!==null&&v.replacement!==null&&v.duplicateOf===null;case 'duplicate':return v.withdrawal===null&&v.replacement===null&&(view||v.duplicateOf!==null);default:return v.withdrawal===null&&v.replacement===null&&v.duplicateOf===null}}
function resolutionObject(){return z.object(resolutionBase).strict()}
const resolution=resolutionObject().refine(v=>resolutionShape(v)),resolutionView=resolutionObject().refine(v=>resolutionShape(v,true));
const transition=reply.extend({status:z.enum(statuses),resolution:resolution.nullable()}).strict().refine(v=>v.resolution===null||v.status==='resolved'&&['clarified','withdrawn','revision_published','service_fixed'].includes(v.resolution.kind)||v.status==='closed'&&['duplicate','not_reproducible','out_of_scope','suggestion_recorded'].includes(v.resolution.kind));
export const feedbackInputSchemas={create,reply,transition};
const time=z.string().regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2})$/).refine(v=>Number.isFinite(Date.parse(v)));
const cursor=z.string().max(512).regex(/^[A-Za-z0-9_-]+$/).nullable();
export const metadataSchema=z.object({id:uuid,target:targetSchema,label:scalar(512),category:z.enum(categories),status:z.enum(statuses),sequence:seq,createdAt:time,updatedAt:time,resolutionKind:z.enum(kinds).nullable(),targetValidity:z.enum(['current','replaced','withdrawn','not_applicable']),canHandle:z.boolean()}).strict().refine(v=>v.label===feedbackLabel(v.target));
const contextSchema=z.object({target:targetSchema,source:sourceSchema,label:scalar(512)}).strict().refine(v=>targetSource(v)&&v.label===feedbackLabel(v.target));
const eventSchema=z.object({sequence:seq,kind:z.enum(['created','replied','transitioned']),actor:z.enum(['submitter','review_team']),from:z.enum(statuses).nullable(),to:z.enum(statuses),message:scalar(4000),resolution:resolutionView.nullable(),recordedAt:time}).strict();
const discussionSchema=z.object({title:scalar(120),location:scalar(400,0),items:z.array(eventSchema).max(50),nextCursor:cursor}).strict().refine(v=>v.items.every((e,i)=>i===0||e.sequence===v.items[i-1].sequence+1));
const pageSchema=z.object({items:z.array(metadataSchema).max(50),nextCursor:cursor}).strict();
const receiptSchema=z.object({status:z.union([z.literal(200),z.literal(201)]),ticket:metadataSchema}).strict();
function schemaFor(r:FeedbackRoute){switch(r.action){case 'readContext':return contextSchema;case 'create':case 'reply':case 'transition':return receiptSchema;case 'listOwn':case 'listReview':return pageSchema;case 'readOwn':case 'readReview':return metadataSchema;default:return discussionSchema}}
export function resolveFeedbackRoute(path:string,method='GET'):FeedbackRoute{const bad=():never=>{throw new FeedbackRequestError('INVALID_REQUEST')};if(!path.startsWith('/api/v1/feedback/')||path.includes('#')||path.includes('\\')||path.endsWith('?'))return bad();const u=new URL(path,'http://localhost'),p=u.pathname.slice('/api/v1/feedback/'.length).split('/');if(u.pathname.includes('%')||p.some(v=>!v))return bad();let action:FeedbackAction,kind:FeedbackRoute['kind'],id:string|undefined,wanted:'GET'|'POST'='GET';
 if(p[0]==='contexts'&&p.length===2&&p[1]==='site'){action='readContext';kind='site'}else if(p[0]==='contexts'&&p.length===3&&['knowledge','path','practice','assessment'].includes(p[1])){action='readContext';kind=p[1] as FeedbackRoute['kind'];id=p[2];if(!(kind==='knowledge'||kind==='path'?mathID:feedbackUUID).test(id))return bad()}
 else if(p[0]==='tickets'&&p.length===1){action=method==='POST'?'create':'listOwn';wanted=method==='POST'?'POST':'GET'}else{const review=p[0]==='review';const q=review?p.slice(1):p;if(q[0]!=='tickets'||q.length<1||q.length>3)return bad();if(q.length===1){if(!review)return bad();action='listReview'}else{id=q[1];if(!feedbackUUID.test(id))return bad();if(q.length===2)action=review?'readReview':'readOwn';else if(q[2]==='events')action=review?'discussReview':'discussOwn';else if(q[2]===(review?'transition':'reply')){action=review?'transition':'reply';wanted='POST'}else return bad()}}
 if(method!==wanted)throw new FeedbackRequestError('METHOD_NOT_ALLOWED');const query=u.searchParams,seen=new Set<string>(),list=['listOwn','listReview','discussOwn','discussReview'].includes(action);const original=new Map(u.search.slice(1).split('&').filter(Boolean).map(v=>v.split('=') as [string,string]));if(u.search&&u.search.slice(1).split('&').some(v=>v.split('=').length!==2))return bad();for(const [key,v] of query){if(seen.has(key)||!v)return bad();seen.add(key);switch(key){case 'area':if(kind!=='site'||!areas.includes(v as typeof areas[number]))return bad();break;case 'partKind':if(!['knowledge','practice','assessment'].includes(kind??'')||(v!=='asset'&&(kind!=='knowledge'||v!=='unit')))return bad();break;case 'partId':if(!['knowledge','practice','assessment'].includes(kind??'')||!mathID.test(v))return bad();break;case 'position':if(kind!=='assessment'||original.get(key)!==v||! /^[1-5]$/.test(v))return bad();break;case 'limit':if(!list||original.get(key)!==v||! /^[1-9][0-9]*$/.test(v)||Number(v)>50)return bad();break;case 'cursor':if(!list||v.length>512||! /^[A-Za-z0-9_-]+$/.test(v))return bad();break;case 'status':if(action!=='listReview'||!statuses.includes(v as typeof statuses[number]))return bad();break;case 'category':if(action!=='listReview'||!categories.includes(v as typeof categories[number]))return bad();break;default:return bad()}}
 if(kind==='site'&&!query.has('area')||kind==='assessment'&&!query.has('position')||query.has('partKind')!==query.has('partId'))return bad();return {path,method:wanted,action,kind,id,query}}
const errorSchema=z.object({error:z.object({code:z.enum(Object.keys(feedbackPolicies) as [FeedbackErrorCode,...FeedbackErrorCode[]]),message:scalar(4000),requestId:z.string().regex(/^(?:[0-9a-f]{32}|unavailable)$/),retryAt:time.optional()}).strict()}).strict();
export async function readFeedbackResponse(response:Response,path:string,signal:AbortSignal,method='GET'):Promise<Envelope<unknown>>{try{const route=resolveFeedbackRoute(path,method);const rid=response.headers.get('X-Request-ID')??'unavailable';if(response.headers.has('Set-Cookie')||response.headers.get('Cache-Control')!=='private, no-store'||response.headers.get('X-Content-Type-Options')!=='nosniff'||! /^(?:[0-9a-f]{32}|unavailable)$/.test(rid)||! /^application\/json(?:;\s*charset=utf-8)?$/i.test(response.headers.get('Content-Type')??''))throw new Error();const raw=await readContentBytes(response,2097152,signal);const value=parseContentJSON(raw);if(response.status>=400){const parsed=errorSchema.parse(value).error;if(parsed.requestId!==rid||feedbackPolicies[parsed.code][0]!==response.status||parsed.code!=='RATE_LIMITED'&&parsed.retryAt!==undefined)throw new Error();throw new FeedbackRequestError(parsed.code,rid,parsed.retryAt)}const out=z.object({actorId:uuid,data:schemaFor(route)}).strict().parse(value);const expected=route.action==='create'?201:200;if(response.status!==expected||['create','reply','transition'].includes(route.action)&&(out.data as {status:number}).status!==response.status)throw new Error();return out}catch(e){if(e instanceof FeedbackRequestError)throw e;throw new FeedbackRequestError()}}
