import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AdminUsers } from "./admin-users";
import { failure } from "@/lib/auth/schemas";
const mocks = vi.hoisted(() => ({ replace: vi.fn(), refresh: vi.fn(), request: vi.fn(), context: vi.fn(), changed: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => mocks }));
vi.mock("@/lib/auth/client", () => ({ authRequest: mocks.request, getAuthContext: mocks.context, notifyAuthChanged: mocks.changed }));
const user = { id: "00000000-0000-4000-8000-000000000001", username: "admin_one", roles: ["learner", "admin"] as ("learner" | "admin")[], mustChangePassword: false };
const initial = { items: [user], total: 1, limit: 20, offset: 0 };
beforeEach(() => { Object.values(mocks).forEach(m => m.mockReset()); mocks.context.mockResolvedValue({ ok: true, data: { user, csrfToken: "A".repeat(43) } }); });
describe("TestAdminUsers", () => {
  it.each(["learner", "editor", "reviewer"] as const)("has no controls for %s", async role => {
    mocks.context.mockResolvedValue({ ok: true, data: { user: { ...user, roles: role === "learner" ? ["learner"] : ["learner", role] }, csrfToken: "A".repeat(43) } });
    render(<AdminUsers initial={initial} />);
    await screen.findByText("You do not have permission.");
    expect(screen.queryByRole("button", { name: "Save roles" })).not.toBeInTheDocument();
  });
  it("requires reason/ownership and explicit retry after verification, cancel never writes", async () => {
    render(<AdminUsers initial={initial} />);
    await screen.findByRole("button", { name: "Save roles" });
    fireEvent.submit(screen.getByRole("button", { name: "Save roles" }).closest("form")!);
    expect(mocks.request).not.toHaveBeenCalled();
    fireEvent.change(screen.getByLabelText("Reason"), { target: { value: "Confirmed role assignment" } });
    mocks.request.mockResolvedValueOnce(failure("REAUTHENTICATION_REQUIRED"));
    fireEvent.click(screen.getByRole("button", { name: "Save roles" }));
    await screen.findByRole("dialog");
    fireEvent.click(screen.getByRole("button", { name: "Cancel" }));
    expect(mocks.request).toHaveBeenCalledTimes(1);
    mocks.request.mockResolvedValueOnce(failure("REAUTHENTICATION_REQUIRED"));
    fireEvent.click(screen.getByRole("button", { name: "Save roles" }));
    await screen.findByRole("dialog");
    fireEvent.change(screen.getByLabelText("Your password"), { target: { value: "test verification passphrase" } });
    mocks.request.mockResolvedValueOnce({ ok: true, data: { validUntil: "2026-10-01T00:00:00Z" } });
    fireEvent.click(screen.getByRole("button", { name: "Verify password" }));
    await screen.findByText("Password verified. Submit your change again.");
    expect(mocks.request).toHaveBeenCalledTimes(3);
    mocks.request.mockResolvedValueOnce({ ok: true, data: undefined }).mockResolvedValueOnce({ ok: true, data: initial });
    fireEvent.click(screen.getByRole("button", { name: "Save roles" }));
    await screen.findByText("Changes saved.");
    expect(mocks.request).toHaveBeenLastCalledWith({ kind: "users", query: { q: "", limit: 20, offset: 0 } }, undefined);
    fireEvent.change(screen.getByLabelText("Temporary password"), { target: { value: "temporary test passphrase" } });
    fireEvent.submit(screen.getByRole("button", { name: "Reset password" }).closest("form")!);
    expect(mocks.request).toHaveBeenCalledTimes(5);
    expect(screen.getByLabelText("Temporary password")).toHaveValue("");
  });
  it("locks double writes and navigates after self revocation", async () => {
    render(<AdminUsers initial={initial} />);
    await screen.findByRole("button", { name: "Save roles" });
    fireEvent.change(screen.getByLabelText("Reason"), { target: { value: "Removing my own admin role" } });
    fireEvent.click(screen.getByLabelText("admin"));
    let resolve!: (value: unknown) => void;
    mocks.request.mockReturnValue(new Promise(r => { resolve = r; }));
    fireEvent.submit(screen.getByRole("button", { name: "Save roles" }).closest("form")!);
    fireEvent.submit(screen.getByRole("button", { name: "Save roles" }).closest("form")!);
    expect(mocks.request).toHaveBeenCalledTimes(1);
    mocks.context.mockResolvedValue({ ok: true, data: { user: null, csrfToken: "A".repeat(43) } });
    resolve({ ok: true, data: undefined });
    await waitFor(() => expect(mocks.replace).toHaveBeenCalledWith("/login"));
  });
});
