import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {validateUiLanguageCI,languageBatches,originalBatches,e2eCommand,readPlaywrightPolicy,removeApprovedLanguageSteps,languageWorkflowSteps} from './ui-language-ci.mjs';
const policy={workers:1,retries:0,globalTimeout:480000,viewports:[{width:1280,height:900},{width:390,height:844}]};
const workflow=batches=>batches.map(b=>'      - name: '+b.join(' ')+'\n        run: '+e2eCommand(b)).join('\n');
const valid=()=>workflow([...originalBatches,...languageBatches]);
test('all seven isolated language batches are required alongside original batches',()=>{assert.equal(validateUiLanguageCI(valid(),policy),true);assert.throws(()=>validateUiLanguageCI(workflow([...originalBatches,...languageBatches.slice(1)]),policy),/missing/);assert.throws(()=>validateUiLanguageCI(workflow([...originalBatches.slice(1),...languageBatches]),policy),/missing/)});
test('names and comments do not count as executable batches',()=>{assert.throws(()=>validateUiLanguageCI(workflow(originalBatches)+'\n# '+languageBatches.map(e2eCommand).join('\n# '),policy),/missing/)});
test('retry, worker, viewport and timeout budgets cannot be relaxed',()=>{for(const change of [{workers:2},{retries:1},{globalTimeout:540000},{viewports:[policy.viewports[0]]}])assert.throws(()=>validateUiLanguageCI(valid(),{...policy,...change}),/budget/)});
test('repository workflow satisfies the policy',()=>{const root=new URL('../../',import.meta.url);const source=readFileSync(new URL('.github/workflows/frontend.yml',root),'utf8');assert.equal(validateUiLanguageCI(source,readPlaywrightPolicy(readFileSync(new URL("tests/e2e/playwright.config.ts",root),"utf8"))),true)});

test('live config reader rejects altered, missing or ambiguous literal budgets',()=>{const root=new URL('../../',import.meta.url),source=readFileSync(new URL('tests/e2e/playwright.config.ts',root),'utf8');assert.throws(()=>validateUiLanguageCI(valid(),readPlaywrightPolicy(source.replace('retries: 0','retries: 1'))),/budget/);assert.throws(()=>readPlaywrightPolicy(source.replace('workers: 1','workers: workerCount')),/budget/);assert.throws(()=>readPlaywrightPolicy(source+'\n retries: 0,\n'),/budget/)});

test('only the exact approved additions may be removed for old workflow byte protection',()=>{const root=new URL('../../',import.meta.url),source=readFileSync(new URL('.github/workflows/frontend.yml',root),'utf8');const original=removeApprovedLanguageSteps(source);assert(!original.includes('ui-language-'));for(const step of languageWorkflowSteps){assert.throws(()=>removeApprovedLanguageSteps(source.replace(step,'')),/missing/);assert.throws(()=>removeApprovedLanguageSteps(source+step),/duplicated/)}assert.throws(()=>removeApprovedLanguageSteps(source.replace('中英文账户双视口验证','renamed')),/changed/)});
