import type { Identity, AttemptSummary, AttemptView, PracticeView, ResultView, SafeQuestion, Overview, KnowledgeState, KnowledgeDetail, PathSummary, PathNode } from "./types";
export const fixtureID = "11111111-1111-4111-8111-111111111111", otherID = "22222222-2222-4222-8222-222222222222", token = "A".repeat(43);
export const identity = (id = "math-root"): Identity => ({ id, version: 1, sha256: "a".repeat(64) });
export const summary = (kind: "practice" | "assessment" = "assessment"): AttemptSummary => { const common = { id: fixtureID, knowledge: identity(), state: "active" as const, createdAt: "2026-10-02T00:00:00Z", expiresAt: "2026-10-03T00:00:00Z", submittedAt: null }; return kind === "practice" ? { ...common, kind: "practice", mode: null } : { ...common, kind: "assessment", mode: "diagnostic" }; };
export const safeQuestion = (position = 1): SafeQuestion => ({ position, instance: identity("qi-" + String(position).repeat(64)), knowledge: identity(), type: "numeric", prompt: "Calculate 1 + 1.", choices: [], answerFormat: "rational", assets: [] });
export const attempt = (): AttemptView => ({ summary: summary(), questions: [1, 2, 3, 4, 5].map(safeQuestion) });
export const practice = (): PracticeView => ({ summary: summary("practice"), question: safeQuestion(), result: null });
export const result = (): ResultView => ({ summary: { ...summary(), kind: "assessment", mode: "diagnostic", state: "submitted", submittedAt: "2026-10-02T00:01:00Z" }, ruleVersion: 1, score: 5, passed: true, outcome: "passed", validity: "effective", reasons: [], items: attempt().questions.map(question => ({ question, answer: { kind: "numeric", raw: "2" }, correct: true, correctChoiceId: null, correctNumeric: { numerator: "2", denominator: "1" }, explanation: "Original addition explanation.", validity: "effective", reasons: [] })), progress: { knowledge: identity(), qualificationGranted: true, newlyUnlocked: [] } });
export const state = (overrides: Partial<KnowledgeState> = {}): KnowledgeState => ({ knowledge: identity(), title: "Addition basics", titleZh: "加法", state: "unlearned", canEnter: true, everUnlocked: false, completionValid: false, startedAt: null, completedAt: null, qualification: null, prerequisites: [], ...overrides });
export const detail = (): KnowledgeDetail => ({ knowledgeHead: fixtureID, questionHead: fixtureID, state: state(), objectives: ["Add two rational numbers exactly."], blueprints: [{ blueprint: identity("five"), coreObjectiveIndices: [0], ready: true, reasons: [], retryAt: null }], activeAssessment: null });
export const overview = (): Overview => ({ knowledgeHead: fixtureID, questionHead: fixtureID, availablePaths: [], startedCount: 0, completedCount: 0, effectivePassedCount: 0, historicalUnlockedCount: 0, activePractice: null, activeAssessment: null, recent: [] });
export const pathSummary = (overrides: Partial<PathSummary> = {}): PathSummary => ({ id: fixtureID, path: identity("route"), title: "Learning route", titleZh: "学习路线", knowledgePublicationId: fixtureID, totalNodes: 3, completedNodes: 1, passedNodes: 0, unlockedNodes: 1, newVersionAvailable: false, createdAt: "2026-10-02T00:00:00Z", ...overrides });
export const pathNodes = (): PathNode[] => [0, 1, 2].map(position => ({ position, title: "Knowledge " + position, titleZh: "知识", state: state(), available: position !== 2, reasons: position === 2 ? ["knowledge-withdrawn"] : [] }));
export function learningJSON(v: unknown, status = 200, extra: HeadersInit = {}): Response { return Response.json(v, { status, headers: { "Content-Type": "application/json", "Cache-Control": "private, no-store", "X-Content-Type-Options": "nosniff", "X-Request-ID": "a".repeat(32), ...extra } }); }
