"use client";
import Link from "next/link";
import {useState} from "react";
import {useRouter} from "next/navigation";
import type {PracticeView} from "@/lib/learning/types";
import {useLearningCommand} from "@/features/learning/pending-command";
import {CommandFeedback} from "@/features/learning/learning-status";
import {AnswerFields,emptyAnswer} from "@/features/assessment/answer-fields";
import {ResultItemPanel} from "@/features/assessment/result-panel";
import styles from "@/styles/assessment.module.css";
export function PracticePanel({view}:{view:PracticeView}){const router=useRouter(),[current,setCurrent]=useState(view),[value,setValue]=useState(()=>emptyAnswer(view.question));const command=useLearningCommand<PracticeView>(r=>{setCurrent(r);router.refresh()});const active=current.summary.state==="active";return <section className={styles.panel}><h1>Single-question practice</h1><p>Practice supports understanding. It does not grant assessment qualification.</p><p>Expires at <time dateTime={current.summary.expiresAt}>{new Date(current.summary.expiresAt).toISOString().replace("T"," ").replace(".000Z"," UTC")}</time></p>{active?<form onSubmit={e=>{e.preventDefault();void command.run({kind:"answerPractice",id:current.summary.id},value)}}><AnswerFields attemptId={current.summary.id} question={current.question} value={value} disabled={command.busy} onChange={a=>{command.clear();setValue(a)}}/><div className={styles.actions}><button className="button" disabled={command.busy||!!command.pending}>Submit answer</button><button className="button secondary" type="button" disabled={command.busy||!!command.pending} onClick={()=>void command.run({kind:"revealPractice",id:current.summary.id},{})}>Reveal answer</button><button className="button secondary" type="button" disabled={command.busy} onClick={()=>void command.run({kind:"abandonPractice",id:current.summary.id},{})}>Abandon practice</button></div><p>Reveal answer ends this practice immediately.</p></form>:<><p>{current.summary.state==="revealed"?"Practice ended: answer revealed.":"Practice "+current.summary.state+"."}</p>{current.result&&<ResultItemPanel item={current.result.item} attemptId={current.summary.id}/>}<Link prefetch={false} href={"/knowledge/"+current.summary.knowledge.id}>Review the lesson or start another practice</Link></>}<CommandFeedback command={command}/></section>}
