import { it, expect, vi, afterEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { CorrectionAccountContext } from './correction-account';
import { PlanEditor } from './plan-editor';
import { correctionClient } from '@/lib/correction/client';
import { getAuthContext, authRequest } from '@/lib/auth/client';
import { CorrectionRequestError } from '@/lib/correction/types';
import { id, planMetadata, planInput, context } from '@/lib/correction/test-fixtures';
vi.mock('next/navigation', () => ({ useRouter: () => ({ refresh: vi.fn() }) }));
vi.mock('@/lib/auth/client', () => ({ getAuthContext: vi.fn(), notifyAuthChanged: vi.fn(), authRequest: vi.fn() }));
vi.mock('@/lib/correction/client', async (original) => { const m = await original<typeof import('@/lib/correction/client')>(); return { ...m, correctionClient: { ...m.correctionClient, readPlan: vi.fn(), readPlanDetail: vi.fn(), updatePlan: vi.fn(), submitPlan: vi.fn(), decidePlan: vi.fn(), createPlan: vi.fn() } }; });
const wrapper = ({ children }: {
    children: React.ReactNode;
}) => <CorrectionAccountContext.Provider value={{ actorId: id, roles: ['editor', 'reviewer'], checking: false, invalidate: vi.fn() }}>{children}</CorrectionAccountContext.Provider>;
afterEach(() => vi.resetAllMocks());
const metadata = () => ({ plan: planMetadata(), parent: null, mappings: [], reason: null, decisionReason: null });
function proof() { vi.mocked(getAuthContext).mockResolvedValue({ ...context(), ok: true, data: { ...context().data, user: { ...context().data.user, username: 'test', roles: ['editor', 'reviewer'] } } }); }
it('requires the protected plan read before editing; status refresh preserves private draft', async () => { proof(); vi.mocked(correctionClient.readPlanDetail).mockResolvedValue({ actorId: id, data: { ...metadata(), reason: planInput().reason } }); vi.mocked(correctionClient.readPlan).mockResolvedValue({ actorId: id, data: { ...metadata(), plan: { ...planMetadata(), sequence: 2 } } }); vi.mocked(correctionClient.updatePlan).mockRejectedValue(new CorrectionRequestError()); render(<PlanEditor initial={metadata()}/>, { wrapper }); expect(screen.queryByLabelText('Plan reason')).toBeNull(); fireEvent.click(screen.getByRole('button', { name: 'Read plan details' })); fireEvent.change(await screen.findByLabelText('Plan reason'), { target: { value: 'Unsubmitted original draft' } }); fireEvent.click(screen.getByRole('button', { name: 'Reload plan status' })); await screen.findByText('Sequence 2'); expect(screen.getByLabelText('Plan reason')).toHaveValue('Unsubmitted original draft'); fireEvent.click(screen.getByRole('button', { name: 'Save plan draft' })); await waitFor(() => expect(correctionClient.updatePlan).toHaveBeenCalledTimes(1)); expect(vi.mocked(correctionClient.updatePlan).mock.calls[0][1]).toMatchObject({ expectedSequence: 2, reason: 'Unsubmitted original draft' }); });
it('presents separate independent approval/rejection and retains a frozen same-key conflict retry', async () => { proof(); const p = { ...planMetadata(), status: 'pending' as const, sequence: 2, digest: 'a'.repeat(64) }; const initial = { ...metadata(), plan: p }; vi.mocked(correctionClient.readPlanDetail).mockResolvedValue({ actorId: id, data: { ...initial, reason: planInput().reason } }); vi.mocked(correctionClient.decidePlan).mockRejectedValue(new CorrectionRequestError('CORRECTION_CONFLICT')); render(<PlanEditor initial={initial}/>, { wrapper }); fireEvent.click(screen.getByRole('button', { name: 'Read plan details' })); fireEvent.change(await screen.findByLabelText('Independent review reason'), { target: { value: 'Independently verified original answers' } }); fireEvent.click(screen.getByRole('button', { name: 'Approve correction' })); await screen.findByRole('alert'); const original = vi.mocked(correctionClient.decidePlan).mock.calls[0]; expect(original[1]).toMatchObject({ decision: 'approve', expectedSequence: 2 }); expect(screen.getByRole('button', { name: 'Reject correction' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: 'Retry same request' })); await waitFor(() => expect(correctionClient.decidePlan).toHaveBeenCalledTimes(2)); expect(vi.mocked(correctionClient.decidePlan).mock.calls[1]?.slice(0, 2)).toEqual(original.slice(0, 2)); expect(vi.mocked(correctionClient.decidePlan).mock.calls[1]?.[2]).toMatchObject({ actorId: original[2].actorId, key: original[2].key }); });
it('reauthentication preserves the original command and never submits it automatically', async () => { proof(); const initial = metadata(); vi.mocked(correctionClient.readPlanDetail).mockResolvedValue({ actorId: id, data: { ...initial, reason: 'Original approved rationale' } }); vi.mocked(correctionClient.submitPlan).mockRejectedValue(new CorrectionRequestError('REAUTHENTICATION_REQUIRED')); vi.mocked(authRequest).mockResolvedValue({ ok: true, data: { reauthenticatedAt: '2026-10-03T00:00:00Z' } }); render(<PlanEditor initial={initial}/>, { wrapper }); fireEvent.click(screen.getByRole('button', { name: 'Read plan details' })); await screen.findByLabelText('Plan reason'); fireEvent.click(screen.getByRole('button', { name: 'Submit for independent review' })); await screen.findByRole('alert'); const original = vi.mocked(correctionClient.submitPlan).mock.calls[0]; fireEvent.click(screen.getByRole('button', { name: 'Verify your password' })); fireEvent.change(await screen.findByLabelText('Your password'), { target: { value: 'technical original password' } }); fireEvent.click(screen.getByRole('button', { name: 'Verify password' })); await screen.findByText('Password verified. Retry the preserved request.'); expect(correctionClient.submitPlan).toHaveBeenCalledTimes(1); expect(screen.queryByLabelText('Your password')).toBeNull(); fireEvent.click(screen.getByRole('button', { name: 'Retry same request' })); await waitFor(() => expect(correctionClient.submitPlan).toHaveBeenCalledTimes(2)); expect(vi.mocked(correctionClient.submitPlan).mock.calls[1]?.[1]).toEqual(original[1]); expect(vi.mocked(correctionClient.submitPlan).mock.calls[1]?.[2]).toMatchObject({ actorId: original[2].actorId, key: original[2].key }); });
it('same-account server metadata refresh updates sequence without erasing an open draft', async () => { proof(); vi.mocked(correctionClient.readPlanDetail).mockResolvedValue({ actorId: id, data: { ...metadata(), reason: 'Saved text' } }); const v = render(<PlanEditor initial={metadata()}/>, { wrapper }); fireEvent.click(screen.getByRole('button', { name: 'Read plan details' })); fireEvent.change(await screen.findByLabelText('Plan reason'), { target: { value: 'Unsubmitted SSR draft' } }); v.rerender(<PlanEditor initial={{ ...metadata(), plan: { ...planMetadata(), sequence: 2 } }}/>); expect(screen.getByLabelText('Plan reason')).toHaveValue('Unsubmitted SSR draft'); expect(screen.getByText('Sequence 2')).toBeVisible(); });
