import {parseStudyResponseJSON} from "./response-json";
import {z} from "zod";
import {contentPolicies,contentCanonicalJSON,contentResponseHeaders,contentUUID} from "../content/schemas";
import {readContentBytes} from "../content/bytes";
import {validContentString} from "../content/raw-json";
import {commandSchema,reviewInputSchema,noteInputSchema,noteDeleteSchema,detailSchema,overviewSchema,topicsPageSchema,knowledgePageSchema,historyPageSchema,noteViewSchema,noteReceiptSchema,stateSchema} from "./schemas";
import type {StudyRoute,StudyErrorCode,StudyResult,ListQuery,HistoryQuery} from "./types";
export const studyPolicies={...contentPolicies,REAUTH_REQUIRED:{status:428,message:"Verify your password before continuing."},STUDY_INVALID:{status:400,message:"Study input is invalid."},STUDY_NOT_CONFIGURED:{status:503,message:"Study records are temporarily unavailable."},STUDY_STATE_CONFLICT:{status:409,message:"Study state has changed. Refresh before continuing."},STUDY_VERSION_STALE:{status:409,message:"Study material has changed. Refresh before continuing."},STUDY_IDEMPOTENCY_CONFLICT:{status:409,message:"This request key was already used with different input."},STUDY_NOTE_CONFLICT:{status:409,message:"This note has changed. Read the latest revision before saving."}} satisfies Record<StudyErrorCode,{status:number;message:string}>;
export const studyFailure=(code:StudyErrorCode="SERVICE_UNAVAILABLE",requestId="unavailable"):Extract<StudyResult<never>,{ok:false}>=>({ok:false,code,...studyPolicies[code],requestId});
const id=/^[a-z][a-z0-9-]{0,63}$/;
function queryValid(q:Record<string,unknown>,kind:string):boolean{
 const allowed=kind==="history"?["knowledgeId","topicId","from","to","kind","cursor","limit"]:kind==="topics"?["topicId","limit","offset"]:["topicId","state","q","reviewOnly","limit","offset"];
 if(Object.keys(q).some(k=>!allowed.includes(k)))return false;
 for(const[key,value]of Object.entries(q)){if(value===undefined)continue;if(key==="limit"||key==="offset"){if(!Number.isSafeInteger(value)||Number(value)<(key==="limit"?1:0)||Number(value)>(key==="offset"?100000:kind==="history"?50:100))return false}else if(key==="reviewOnly"){if(typeof value!=="boolean")return false}else{if(typeof value!=="string"||value===""||!validContentString(value))return false;if((key==="topicId"||key==="knowledgeId")&&!id.test(value))return false;if(key==="topicId"&&!value.startsWith("msc-"))return false;if(key==="q"&&new TextEncoder().encode(value).byteLength>512)return false;if(key==="state"&&!stateSchema.safeParse(value).success)return false;if(key==="kind"&&!["started","completed","review-started","review-finished","note-saved","note-deleted"].includes(value))return false;if(key==="cursor"&&(value.length>512||!/^[\x20-\x7e]*$/.test(value)))return false;if((key==="from"||key==="to")&&!z.iso.datetime({offset:true}).safeParse(value).success)return false}}
 if(q.from!==undefined&&q.to!==undefined&&Date.parse(String(q.from))>=Date.parse(String(q.to)))return false;return true;
}
export function studyRouteRequest(route:StudyRoute):{path:string;method:string;kind:string}|null{
 if(!route||typeof route!=="object")return null;const allowed=(keys:string[])=>Object.keys(route).every(k=>keys.includes(k));let path="",method="GET";
 if(["overview","topics","knowledge","history"].includes(route.kind)){if(!allowed(route.kind==="overview"?["kind"]:["kind","query"]))return null;path="/api/v2/study/"+route.kind;if("query"in route){const q=route.query??{};if(typeof q!=="object"||q===null||!queryValid(q,route.kind))return null;const params=new URLSearchParams();for(const[key,value]of Object.entries(q)){if(value!==undefined)params.set(key,String(value))};if(params.size)path+="?"+params}}
 else if(["readKnowledge","readNote","begin","complete","startReview","finishReview","saveNote","deleteNote"].includes(route.kind)){if(!allowed(["kind","id"])||!("id"in route)||!id.test(route.id))return null;path="/api/v2/study/knowledge/"+route.id;switch(route.kind){case"readNote":path+="/note";break;case"saveNote":path+="/note";method="PUT";break;case"deleteNote":path+="/note";method="DELETE";break;case"begin":case"complete":path+="/"+route.kind;method="POST";break;case"startReview":path+="/review/start";method="POST";break;case"finishReview":path+="/review/finish";method="POST";break}}
 else return null;return {path,method,kind:route.kind};
}
const inputs={begin:commandSchema,complete:commandSchema,startReview:commandSchema,finishReview:reviewInputSchema,saveNote:noteInputSchema,deleteNote:noteDeleteSchema};
export function studyInputError(kind:string,input:unknown):StudyErrorCode|null{if(!Object.hasOwn(inputs,kind)||!inputs[kind as keyof typeof inputs].safeParse(input).success)return "INVALID_REQUEST";if(new TextEncoder().encode(contentCanonicalJSON(input)).byteLength>(kind==="saveNote"?131072:8192))return "PAYLOAD_TOO_LARGE";return null}
export function resolveStudyRoute(request:Request):StudyRoute|StudyErrorCode{
 const url=new URL(request.url);if(!url.pathname.startsWith("/api/v2/study/"))return "NOT_FOUND";if(url.pathname.includes("%")||url.href.endsWith("?"))return "INVALID_REQUEST";try{decodeURIComponent(url.search)}catch{return "INVALID_REQUEST"};const p=url.pathname.slice("/api/v2/study/".length).split("/");if(p.some(s=>s===""))return "NOT_FOUND";let route:StudyRoute;
 if(p.length===1&&["overview","topics","knowledge","history"].includes(p[0]))route={kind:p[0]} as StudyRoute;
 else if(p[0]==="knowledge"&&p.length>=2){let kind:string="readKnowledge";if(p.length===3){if(p[2]==="note")kind=request.method==="PUT"?"saveNote":request.method==="DELETE"?"deleteNote":"readNote";else if(["begin","complete"].includes(p[2]))kind=p[2];else return "NOT_FOUND"}else if(p.length===4&&p[2]==="review"&&["start","finish"].includes(p[3]))kind=p[3]==="start"?"startReview":"finishReview";else if(p.length!==2)return "NOT_FOUND";route={kind,id:p[1]} as StudyRoute}else return "NOT_FOUND";
 if(["topics","knowledge","history"].includes(route.kind)){const query:Record<string,unknown>={};for(const[key,value]of url.searchParams){if(Object.hasOwn(query,key))return "INVALID_REQUEST";if(key==="limit"||key==="offset"){if(!/^[0-9]+$/.test(value))return "INVALID_REQUEST";query[key]=Number(value)}else if(key==="reviewOnly"){if(!["true","false"].includes(value))return "INVALID_REQUEST";query[key]=value==="true"}else query[key]=value};if(!queryValid(query,route.kind))return "INVALID_REQUEST";route={...route,query:query as ListQuery&HistoryQuery} as StudyRoute}else if(url.search!=="")return "INVALID_REQUEST";
 const target=studyRouteRequest(route);if(!target||url.pathname!==target.path.split("?")[0])return "INVALID_REQUEST";return route;
}
const outputs={overview:overviewSchema,topics:topicsPageSchema,knowledge:knowledgePageSchema,readKnowledge:detailSchema,history:historyPageSchema,readNote:noteViewSchema,begin:detailSchema,complete:detailSchema,startReview:detailSchema,finishReview:detailSchema,saveNote:noteReceiptSchema,deleteNote:noteReceiptSchema};
const errorSchema=z.object({error:z.object({code:z.enum(Object.keys(studyPolicies) as[StudyErrorCode,...StudyErrorCode[]]),message:z.string().refine(validContentString),requestId:z.string().regex(/^(?:[a-f0-9]{32}|unavailable)$/)}).strict()}).strict().refine(v=>v.error.message===studyPolicies[v.error.code].message);
export async function readStudyResponse(response:Response,kind:string,signal:AbortSignal):Promise<{result:StudyResult<unknown>;payload:unknown}>{const requestId=contentResponseHeaders(response);if(response.headers.get("Cache-Control")!=="private, no-store"||!/^application\/json(?:;\s*charset=(?:utf-8|"utf-8"))?$/i.test(response.headers.get("Content-Type")??""))throw new Error("Invalid study response.");const raw=parseStudyResponseJSON(await readContentBytes(response,2<<20,signal));if(!response.ok){const error=errorSchema.parse(raw).error;if(studyPolicies[error.code].status!==response.status||error.requestId!==requestId)throw new Error("Invalid study response.");const result=studyFailure(error.code,requestId);if(error.code==="RATE_LIMITED"){const retry=response.headers.get("Retry-After");if(!retry||!/^(?:[1-9]|[1-5][0-9]|60)$/.test(retry))throw new Error("Invalid retry response.");result.retryAfter=Number(retry)}else if(response.headers.has("Retry-After"))throw new Error("Invalid retry response.");return{result,payload:raw}};if(response.status!==200||response.headers.has("Retry-After")||!Object.hasOwn(outputs,kind))throw new Error("Invalid study response.");const parsed=outputs[kind as keyof typeof outputs].parse(raw);return{result:{ok:true,data:parsed},payload:parsed}}
