import {z} from "zod";
import {validContentString} from "../content/raw-json";
import {knowledgeRefSchema,knowledgeSummarySchema,pairSchema} from "../taxonomy/schemas";
const text=z.string().refine(validContentString),id=text.regex(/^[a-z][a-z0-9-]{0,63}$/),actor=text.regex(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/),count=z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),time=z.iso.datetime({offset:true});
export const stateSchema=z.enum(["unlearned","learning","completed","reviewing"]);
export const recordSchema=z.object({knowledgeId:id,state:stateSchema,sequence:count,firstStartedAt:time.nullable(),firstCompletedAt:time.nullable(),lastCompletedAt:time.nullable(),lastReadAt:time.nullable(),lastReviewedAt:time.nullable(),completedRef:knowledgeRefSchema.nullable(),lastReviewRef:knowledgeRefSchema.nullable(),lastReviewId:actor.nullable(),activeReviewId:actor.nullable()}).strict();
export const detailSchema=z.object({actorId:actor,record:recordSchema,currentKnowledge:knowledgeSummarySchema.nullable(),pair:pairSchema,available:z.boolean(),materialChanged:z.boolean()}).strict().refine(v=>v.currentKnowledge===null||v.currentKnowledge.id===v.record.knowledgeId);
export const commandSchema=z.object({knowledge:knowledgeRefSchema,expectedKnowledgeHead:actor,expectedSequence:count}).strict();
export const reviewInputSchema=commandSchema.extend({reviewId:actor}).strict();
const noteText=text.refine(v=>[...v].length<=16000&&new TextEncoder().encode(v).byteLength<=65536);
export const noteInputSchema=z.object({knowledge:knowledgeRefSchema,expectedRevision:count,body:noteText}).strict();
export const noteDeleteSchema=z.object({expectedRevision:count}).strict();
export const noteViewSchema=z.object({actorId:actor,knowledgeId:id,revision:count,body:noteText,knowledge:knowledgeRefSchema.nullable(),updatedAt:time.nullable()}).strict().refine(v=>v.knowledge===null||v.knowledge.id===v.knowledgeId);
export const noteReceiptSchema=z.object({actorId:actor,knowledgeId:id,revision:count,deleted:z.boolean(),updatedAt:time}).strict();
export const topicProgressSchema=z.object({topicId:id,total:count,completed:count,learning:count,reviewing:count,added:count,removed:count,completedRatio:z.number().min(0).max(1).nullable()}).strict().refine(v=>v.completed<=v.total&&v.reviewing<=v.completed&&(v.total===0?v.completedRatio===null:v.completedRatio===v.completed/v.total));
const pageFields={actorId:actor,total:count,limit:count.min(1).max(100),offset:count};
export const topicsPageSchema=z.object({...pageFields,items:z.array(topicProgressSchema).max(100)}).strict().refine(v=>v.items.length<=v.limit&&v.items.length<=v.total);
export const knowledgePageSchema=z.object({...pageFields,items:z.array(detailSchema).max(100)}).strict().refine(v=>v.items.length<=v.limit&&v.items.length<=v.total&&v.items.every(item=>item.actorId===v.actorId));
export const contentReminderSchema=z.object({changeId:actor,knowledgeId:id,kind:z.enum(["updated","withdrawn"]),recordedAt:time,currentRef:knowledgeRefSchema.nullable(),reviewed:z.boolean()}).strict();
export const overviewSchema=z.object({actorId:actor,pair:pairSchema,mode:z.enum(["legacy","topics"]),total:count,completed:count,learning:count,reviewing:count,unavailable:count,unclassified:count,materialChanged:count,reminders:z.array(contentReminderSchema).max(1000)}).strict().refine(v=>v.completed<=v.total&&v.reviewing<=v.completed);
export const historyEntrySchema=z.object({id:actor,knowledge:knowledgeRefSchema,taxonomyVersionId:text.regex(/^[a-f0-9]{64}$/).nullable(),taxonomyHead:actor.nullable(),kind:z.enum(["started","completed","review-started","review-finished","note-saved","note-deleted"]),occurredAt:time,noteRevision:count.nullable(),reviewId:actor.nullable(),sourceKind:z.enum(["native","legacy"]),originEventId:actor.nullable()}).strict().refine(v=>v.sourceKind==="native"?v.taxonomyVersionId!==null&&v.taxonomyHead!==null&&v.originEventId===null:v.originEventId!==null);
const cursor=text.max(512).regex(/^[\x20-\x7e]*$/);
export const historyPageSchema=z.object({actorId:actor,items:z.array(historyEntrySchema).max(50),limit:count.min(1).max(50),nextCursor:cursor.nullable()}).strict().refine(v=>v.items.length<=v.limit);
