import {getUiMetadata} from "@/lib/i18n/server";
import {UiPageTitle} from "@/components/ui-page-title";
export async function generateMetadata(){return getUiMetadata("page.learn");}
import Link from "next/link";
import {getLearningClient} from "@/lib/learning/server-client";
import {learningActor,learningPageQuery} from "@/features/learning/page-data";
import {LearningBoundary,LearningNotice} from "@/features/learning/learning-status";
import {OverviewPanel} from "@/features/learning/overview-panel";
import {PathProgress} from "@/features/learning/path-progress";
import {KnowledgeList} from "@/features/learning/knowledge-list";
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const query=learningPageQuery(await searchParams,"learn");if(!query)return <><UiPageTitle messageKey="page.learn"/>{<section className="content-state" role="alert"><h1>Invalid learning parameters.</h1><Link prefetch={false} href="/learn">Reset learning view</Link></section>}</>;const actor=await learningActor();if(!actor.ok)return <><UiPageTitle messageKey="page.learn"/>{<LearningNotice result={actor.error}/>}</>;const client=getLearningClient();let body:React.ReactNode;if(query.enrollment){const route=await client.readLearningPath(query.enrollment);if(!route.ok)return <><UiPageTitle messageKey="page.learn"/>{<LearningNotice result={route}/>}</>;const nodes=await client.listLearningPathNodes(query.enrollment,{limit:20,offset:query.offset});if(!nodes.ok)return <><UiPageTitle messageKey="page.learn"/>{<LearningNotice result={nodes}/>}</>;body=<><PathProgress path={route.data.summary} nodes={nodes.data.items}/><nav aria-label="Route node pages">{query.offset>0&&<Link prefetch={false} href={`/learn?enrollment=${query.enrollment}&offset=${Math.max(0,query.offset-20)}`}>Previous nodes</Link>}{query.offset+20<nodes.data.total&&<Link prefetch={false} href={`/learn?enrollment=${query.enrollment}&offset=${query.offset+20}`}>Next nodes</Link>}</nav><Link prefetch={false} href="/learn">Back to my learning</Link></>}else{const overview=await client.readLearningOverview();if(!overview.ok)return <><UiPageTitle messageKey="page.learn"/>{<LearningNotice result={overview}/>}</>;const paths=await client.listLearningPaths({limit:20,offset:query.pathOffset});if(!paths.ok)return <><UiPageTitle messageKey="page.learn"/>{<LearningNotice result={paths}/>}</>;const knowledge=await client.listLearningKnowledge({limit:20,offset:query.knowledgeOffset});if(!knowledge.ok)return <><UiPageTitle messageKey="page.learn"/>{<LearningNotice result={knowledge}/>}</>;body=<><OverviewPanel overview={overview.data}/><section className="panel"><h2>Your saved routes</h2>{paths.data.items.length?paths.data.items.map(p=><p key={p.id}><Link prefetch={false} href={"/learn?enrollment="+p.id}>{p.title} · Saved version {p.path.version}</Link></p>):<p>Choose a reviewed route, then select Join route to save your progress.</p>}<nav aria-label="Saved route pages">{query.pathOffset>0&&<Link prefetch={false} href={"/learn?pathOffset="+Math.max(0,query.pathOffset-20)}>Previous routes</Link>}{query.pathOffset+20<paths.data.total&&<Link prefetch={false} href={"/learn?pathOffset="+(query.pathOffset+20)}>Next routes</Link>}</nav></section><KnowledgeList page={knowledge.data}/></>};return <><UiPageTitle messageKey="page.learn"/>{<><header className="page-heading"><p className="eyebrow">ONE IDEA AT A TIME</p><h1>My learning</h1><p>See what you have read, assessed, and unlocked.</p></header><LearningBoundary actorId={actor.id}>{body}</LearningBoundary></>}</>}
