import {z} from 'zod';
const id=z.string().regex(/^k-[0-9a-f]{56}$/),sha=z.string().regex(/^[0-9a-f]{64}$/),uuid=z.string().uuid();
export const managedRefSchema=z.object({id,contentSha256:sha,sourceKind:z.literal('managed')}).strict();
export const modeSchema=z.object({mode:z.enum(['legacy','managed']),capability:z.boolean()}).strict().refine(v=>v.capability===(v.mode==='managed'));
const counts=z.object({createdKnowledge:z.number().int().nonnegative(),linkedTopics:z.number().int().nonnegative(),skippedItems:z.number().int().nonnegative(),conflicts:z.number().int().nonnegative(),invalidItems:z.number().int().nonnegative()}).strict();
export const previewSchema=z.object({importId:uuid,inputSha256:sha,previewToken:uuid,items:z.array(z.object({index:z.number().int().nonnegative(),externalId:z.string(),action:z.enum(['create','link','skip','conflict','invalid']),topicKeys:z.array(z.string()),errorCode:z.string().optional(),errorPath:z.string().optional()}).strict()).max(100),counts}).strict();
export const receiptSchema=z.object({operationId:z.string(),counts,items:z.array(z.object({index:z.number().int().nonnegative(),externalId:z.string(),action:z.enum(['create','link','skip','conflict','invalid','not-selected']),knowledgeId:id,topicKeys:z.array(z.string()),errorCode:z.string().optional()}).strict()).max(100)}).strict();
export const importStatusSchema=z.object({preview:previewSchema,receipt:receiptSchema.nullable()}).strict();

const time=z.string().datetime({offset:true});
const source=z.object({sourceId:z.string(),title:z.string(),citation:z.string(),url:z.string().url().optional()}).strict();
const difficulty=z.object({difficulty_level:z.number().int().min(1).max(5),rationale:z.string().optional(),prerequisites:z.array(z.string()).optional(),review_status:z.string().optional(),rubric_version:z.string().optional(),proof_scope_note:z.string().optional()}).strict();
const types=z.enum(['concept','definition','axiom','theorem','corollary','method','mathematical-thinking','other']);
const point=z.object({title:z.string(),title_zh:z.string(),type:types,learning_difficulty:difficulty,statement:z.string().optional(),conditions:z.array(z.string()).optional(),scope:z.string().optional(),system:z.string().optional(),objectives:z.array(z.string()).optional(),type_status:z.string().optional(),type_reason:z.string().optional(),type_other_reason:z.string().optional(),subtype:z.string().optional(),classification_mode:z.string().optional(),msc_codes:z.array(z.string()).optional(),classification_status:z.string().optional(),classification_evidence:z.array(z.object({msc_code:z.string(),kind:z.string(),reason:z.string(),evidence_fields:z.array(z.string())}).strict()).optional(),project_other:z.object({group_id:z.string(),reason:z.string(),evidence_fields:z.array(z.string())}).strict().optional(),proof:z.string().optional(),proof_scope:z.string().optional(),equations:z.array(z.string()).optional(),explanations:z.array(z.object({kind:z.string(),body:z.string()}).strict()).optional(),examples:z.array(z.string()).optional(),counterexamples:z.array(z.string()).optional(),common_misconceptions:z.array(z.string()).optional(),relations:z.array(z.object({kind:z.string(),target_source_id:z.string(),target_id:z.string(),target_version:z.number().int(),status:z.string(),reason:z.string()}).strict()).optional(),tags:z.array(z.string()).optional()}).strict();
const publicKnowledge=z.object({id,externalId:z.string(),topicKeys:z.array(z.string()),point,sources:z.array(source),ref:managedRefSchema,updatedAt:time}).strict().refine(v=>v.id===v.ref.id);
const summary=z.object({id,externalId:z.string(),topicKeys:z.array(z.string()),title:z.string(),titleZh:z.string(),type:types,difficulty:z.number().int().min(1).max(5),ref:managedRefSchema,published:z.boolean(),deleted:z.boolean(),editToken:uuid,updatedAt:time}).strict();
const knowledge=z.object({id,externalId:z.string(),topicKeys:z.array(z.string()),point:z.object({id:z.string(),version:z.number().int().min(1),title:z.string(),title_zh:z.string(),type:types,learning_difficulty:difficulty}).passthrough(),sources:z.array(source),ref:managedRefSchema,published:z.boolean(),deleted:z.boolean(),editToken:uuid,updatedAt:time}).strict().refine(v=>v.id===v.ref.id&&v.externalId===v.point.id);
const page=<T extends z.ZodType>(item:T)=>z.object({items:z.array(item).max(100),total:z.number().int().nonnegative(),limit:z.number().int().min(1).max(100),offset:z.number().int().nonnegative()}).strict();
const topic=z.object({topicKey:z.string(),title:z.string(),titleEn:z.string().optional(),kind:z.enum(['primary','secondary','specific','other','project-other']),knowledgeCount:z.number().int().nonnegative(),items:page(publicKnowledge)}).strict();
const record=z.object({knowledgeId:id,state:z.enum(['unlearned','learning','completed','reviewing']),sequence:z.number().int().nonnegative(),firstStartedAt:time.nullable(),firstCompletedAt:time.nullable(),lastCompletedAt:time.nullable(),lastReadAt:time.nullable(),lastReviewedAt:time.nullable(),completedRef:managedRefSchema.nullable(),lastReviewRef:managedRefSchema.nullable(),lastReviewId:uuid.nullable(),activeReviewId:uuid.nullable()}).strict();
const detail=z.object({actorId:uuid,record,currentKnowledge:publicKnowledge.nullable(),available:z.boolean(),materialChanged:z.boolean()}).strict();
const note=z.object({actorId:uuid,knowledgeId:id,body:z.string(),revision:z.number().int().nonnegative(),knowledge:managedRefSchema.nullable(),deleted:z.boolean(),available:z.boolean(),updatedAt:time.nullable()}).strict();
const progress=z.object({topicKey:z.string(),total:z.number().int().nonnegative(),completed:z.number().int().nonnegative(),learning:z.number().int().nonnegative(),reviewing:z.number().int().nonnegative(),completedRatio:z.number().min(0).max(1).nullable()}).strict();
const overview=z.object({actorId:uuid,total:z.number().int().nonnegative(),completed:z.number().int().nonnegative(),learning:z.number().int().nonnegative(),reviewing:z.number().int().nonnegative(),unavailable:z.number().int().nonnegative(),unclassified:z.number().int().nonnegative(),materialChanged:z.number().int().nonnegative(),reminders:z.array(z.object({knowledgeId:id,kind:z.string(),recordedAt:time}).strict())}).strict();
const history=z.object({actorId:uuid,items:z.array(z.object({id:uuid,knowledge:managedRefSchema,topicKeys:z.array(z.string()),kind:z.enum(['started','completed','review-started','review-finished','note-saved','note-deleted']),noteRevision:z.number().int().nullable(),reviewId:uuid.nullable(),recordedAt:time,sourceKind:z.literal('managed')}).strict()).max(50),nextCursor:z.string().nullable()}).strict();
export function schemaForPath(path:string,method="GET"){if(path==='/api/v3/content-mode')return modeSchema;if(path==='/api/v3/admin/knowledge/imports')return previewSchema;if(/\/imports\/[^/]+\/apply$/.test(path))return receiptSchema;if(/\/imports\/[^/]+$/.test(path))return importStatusSchema;if(path==='/api/v3/admin/knowledge')return method==='POST'?knowledge:page(summary);if(path.startsWith('/api/v3/admin/knowledge/'))return knowledge;if(path==='/api/v3/knowledge')return page(publicKnowledge);if(path.startsWith('/api/v3/knowledge/'))return publicKnowledge;if(path==='/api/v3/topics')return page(topic);if(path.startsWith('/api/v3/topics/'))return topic;if(path==='/api/v3/study/overview')return overview;if(path==='/api/v3/study/topics')return page(progress);if(path==='/api/v3/study/history')return history;if(path==='/api/v3/study/knowledge')return page(detail);if(path.endsWith('/note'))return note;if(path.startsWith('/api/v3/study/knowledge/'))return detail;return z.never()}
