import {it,expect,vi} from 'vitest';import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';
vi.mock('@/lib/feedback/client',()=>({readFeedback:vi.fn(),sendFeedback:vi.fn()}));vi.mock('@/lib/auth/client',()=>({getAuthContext:vi.fn(async()=>({ok:true,data:{user:{id:'11111111-1111-4111-8111-111111111111',username:'test',roles:['learner'],mustChangePassword:false},csrfToken:'A'.repeat(43)}})),notifyAuthChanged:vi.fn()}));vi.mock('next/navigation',()=>({useRouter:()=>({refresh:vi.fn(),push:vi.fn()})}));
import {FeedbackAccountContext} from '@/features/feedback/feedback-account';import {DiscussionPanel,FeedbackTicket} from '@/features/feedback/discussion-panel';import {CorrectionCommandStatus} from '@/features/correction/status';import {readFeedback,sendFeedback} from '@/lib/feedback/client';import {FeedbackRequestError} from '@/lib/feedback/types';import {CorrectionRequestError} from '@/lib/correction/types';import {id,metadata} from '@/lib/feedback/test-fixtures';import {UiLocaleProvider} from './provider';import {LanguageSwitch} from '@/components/language-switch';
const wrapper=({children}:{children:React.ReactNode})=><UiLocaleProvider initialLocale="en"><LanguageSwitch/><FeedbackAccountContext.Provider value={{actorId:id,invalidate:vi.fn()}}>{children}</FeedbackAccountContext.Provider></UiLocaleProvider>;
it('user-comment-matching-ui-text-remains-original',async()=>{
 vi.mocked(readFeedback).mockResolvedValue({actorId:id,data:{title:'Save draft',location:'Original location',items:[{sequence:1,kind:'created',actor:'submitter',from:null,to:'new',message:'Save draft',resolution:null,recordedAt:'2026-10-03T00:00:00Z'}],nextCursor:null}});render(<DiscussionPanel ticketId={id}/>,{wrapper});fireEvent.click(screen.getByRole('button',{name:'Read discussion'}));await screen.findByRole('heading',{name:'Save draft'});fireEvent.click(screen.getByRole('button',{name:'中文'}));expect(screen.getByRole('heading',{name:'讨论'})).toBeVisible();expect(screen.getAllByText('Save draft')).toHaveLength(2);
});
it('feedback-and-correction-pending-state-keeps-request',async()=>{
 vi.mocked(sendFeedback).mockReset();vi.mocked(sendFeedback).mockRejectedValue(new FeedbackRequestError());render(<FeedbackTicket initial={metadata()} review={false}/>,{wrapper});fireEvent.change(screen.getByLabelText('Additional details'),{target:{value:'Save draft'}});fireEvent.click(screen.getByRole('button',{name:'Add details'}));await screen.findByRole('alert');const first=vi.mocked(sendFeedback).mock.calls[0][0];fireEvent.click(screen.getByRole('button',{name:'中文'}));expect(screen.getByLabelText('补充详情')).toHaveValue('Save draft');expect(sendFeedback).toHaveBeenCalledOnce();fireEvent.click(screen.getByRole('button',{name:'重试同一请求'}));await waitFor(()=>expect(sendFeedback).toHaveBeenCalledTimes(2));expect(vi.mocked(sendFeedback).mock.calls[1][0]).toEqual(first);cleanup();
 const pending={key:'fixed-original-key',input:{reason:'Save draft'}},before=JSON.stringify(pending),retry=vi.fn(async()=>{});render(<UiLocaleProvider initialLocale="en"><LanguageSwitch/><CorrectionCommandStatus command={{busy:false,error:new CorrectionRequestError(),pending,confirmed:true,retry,clear:vi.fn()}}/></UiLocaleProvider>);fireEvent.click(screen.getByRole('button',{name:'中文'}));expect(screen.getByText('更改已保存，请重试同一请求以加载最新状态。')).toBeVisible();expect(retry).not.toHaveBeenCalled();expect(JSON.stringify(pending)).toBe(before);
});

vi.mock('@/lib/notification/client',()=>({notificationClient:{list:vi.fn(),count:vi.fn(),read:vi.fn(),markRead:vi.fn()}}));
import {Inbox} from '@/features/notification/inbox';
import {CorrectionAccountContext} from '@/features/correction/correction-account';
import {metadata as notificationMetadata,id as notificationID} from '@/lib/notification/test-fixtures';
import {notificationClient} from '@/lib/notification/client';
it('notification fixed frame changes language without a read mutation',()=>{
 render(<UiLocaleProvider initialLocale="en"><LanguageSwitch/><CorrectionAccountContext.Provider value={{actorId:notificationID,roles:['learner'],checking:false,invalidate:vi.fn()}}><Inbox initial={{items:[notificationMetadata()],nextCursor:null}} count={1}/></CorrectionAccountContext.Provider></UiLocaleProvider>);
 expect(screen.getByRole('heading',{name:'Your learning evidence is being checked.'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'中文'}));expect(screen.getByRole('heading',{name:'正在核查你的学习证据。'})).toBeVisible();expect(notificationClient.markRead).not.toHaveBeenCalled();
});
