import {it,expect,vi,beforeEach} from 'vitest';import {render,screen,fireEvent,waitFor} from '@testing-library/react';
const mocks=vi.hoisted(()=>({request:vi.fn(),content:vi.fn(),refresh:vi.fn(),push:vi.fn()}));
vi.mock('next/navigation',()=>({useRouter:()=>mocks}));vi.mock('@/lib/question/client',()=>({requestQuestion:mocks.request}));vi.mock('@/lib/content/client',()=>({contentRequest:mocks.content}));
import {PublicationPanel} from '@/features/question/publication-panel';import {DraftEditor} from '@/features/question/draft-editor';import {SourcesFields} from '@/features/question/template-fields';import {CasePanel} from '@/features/correction/case-panel';
import {publication,fixtureID,otherID} from '@/lib/question/test-fixtures';import {componentDraft} from '@/features/question/test-fixtures';import {questionFailure} from '@/lib/question/schemas';import {contentFailure} from '@/lib/content/schemas';
import {caseMetadata,planMetadata,id,time} from '@/lib/correction/test-fixtures';import {UiLocaleProvider} from './provider';import {LanguageSwitch} from '@/components/language-switch';
const wrapper=({children}:{children:React.ReactNode})=><UiLocaleProvider initialLocale="en"><LanguageSwitch/>{children}</UiLocaleProvider>;
beforeEach(()=>{vi.clearAllMocks();mocks.request.mockImplementation(async()=>({ok:true,data:{items:[],total:0,limit:1,offset:0,head:null}}));mocks.content.mockResolvedValue({ok:true,data:{head:otherID,items:[],total:0,limit:1,offset:0}})});
it('late snapshot read errors follow current locale and retain original wire failure',async()=>{
 let resolve!:(v:unknown)=>void;const failure=questionFailure('NOT_FOUND'),before=JSON.stringify(failure);mocks.request.mockImplementation(route=>route.kind==='readPublication'?new Promise(r=>{resolve=r}):Promise.resolve({ok:true,data:{items:[],total:0,limit:1,offset:0}}));render(<PublicationPanel initial={{items:[],head:fixtureID,total:0,limit:1,offset:0}} knowledgeHead={otherID}/>,{wrapper});await waitFor(()=>expect(resolve).toBeTypeOf('function'));fireEvent.click(screen.getByRole('button',{name:'中文'}));resolve(failure);await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('未找到资源。'));fireEvent.click(screen.getByRole('button',{name:'English'}));expect(screen.getByRole('alert')).toHaveTextContent('Resource not found.');expect(JSON.stringify(failure)).toBe(before);
});
it('knowledge snapshot refresh errors use content namespace and remain translatable',async()=>{
 const failure=contentFailure('PUBLICATION_STALE');mocks.content.mockResolvedValue(failure);render(<PublicationPanel initial={{items:[],head:null,total:0,limit:1,offset:0}} knowledgeHead={otherID}/>,{wrapper});fireEvent.click(screen.getByRole('button',{name:'Refresh both current heads'}));await screen.findByRole('alert');fireEvent.click(screen.getByRole('button',{name:'中文'}));expect(screen.getByRole('alert')).toHaveTextContent('已发布内容已变更，请准备新快照。');expect(failure.message).toBe('Published content has changed. Prepare a new snapshot.');
});
it('submitted question and pending correction/job labels localize without mutating code values',()=>{
 const d={...componentDraft(),status:'submitted' as const},before=JSON.stringify(d);render(<DraftEditor initial={d}/>,{wrapper});fireEvent.click(screen.getByRole('button',{name:'中文'}));expect(screen.getByText(/已保存修订 1 · 已提交/)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'English'}));expect(screen.getByText(/Saved revision 1 · submitted/)).toBeVisible();expect(JSON.stringify(d)).toBe(before);
});
it('correction plan and retrying job labels preserve original metadata',()=>{
 const data={case:caseMetadata(),plans:{items:[{...planMetadata(),status:'pending' as const,digest:'a'.repeat(64)}],nextCursor:null},jobs:{items:[{id,caseId:id,plan:null,type:'rule_impact' as const,state:'retry_wait' as const,sequence:1,epoch:1,attempt:2,nextRunAt:time,processedCount:7,errorClass:null}],nextCursor:null}},before=JSON.stringify(data);render(<CasePanel initial={data}/>,{wrapper});fireEvent.click(screen.getByRole('button',{name:'中文'}));expect(screen.getByText(/方案版本 1 · 待审核/)).toBeVisible();expect(screen.getByText(/评分规则影响.*等待重试/)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'English'}));expect(screen.getByText(/rule impact.*retry_wait/)).toBeVisible();expect(JSON.stringify(data)).toBe(before);
});
it('source field names translate but the source author and title are preserved',()=>{
 const source={kind:'original' as const,author:'Save draft',title:'Original source title',url:'',accessedAt:'',license:'CC0-1.0',attribution:''};render(<SourcesFields label="Template 1" value={[source]} onChange={vi.fn()}/>,{wrapper});const author=screen.getByLabelText('Template 1 source 1 author');fireEvent.click(screen.getByRole('button',{name:'中文'}));expect(screen.getByLabelText('Template 1 来源 1 作者')).toBe(author);expect(author).toHaveValue('Save draft');expect(screen.getByLabelText('Template 1 来源 1 标题')).toHaveValue('Original source title');
});
