const main = document.querySelector('#main');
const announce = document.querySelector('#announcement');
const [catalogue, route] = await Promise.all([
  fetch('../data/knowledge-domains.json').then(readJSON),
  fetch('../data/elementary-route.json').then(readJSON),
]).catch(error => {
  main.innerHTML = '<section class="panel empty-state"><h1>Preview data could not be loaded</h1><p>Serve the repository over HTTP, then reload this page.</p></section>';
  throw error;
});
const domains = catalogue.domains;
const nodes = route.nodes;
let mapMode = 'domains';
let selectedDomain = 'elementary-mathematics';
let selectedNode = 'equivalent-fractions';
let lessonTab = 'visual';
let search = '';
let layoutObserver;
const stateLabels = {mastered:'Mastered',learned:'Learned',learning:'In progress',review:'Needs review',unlearned:'Not started',locked:'Locked',unlocked:'Unlocked',preview:'Preview route',outline:'Content planned'};
async function readJSON(response) { if (!response.ok) throw new Error(`Data request failed: ${response.status}`); return response.json(); }
function escape(value) { return String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])); }
function badge(state, label=stateLabels[state]) { return `<span class="badge ${escape(state)}"><span class="status-dot" aria-hidden="true"></span>${escape(label)}</span>`; }
function button(label, href, style='') { return `<a class="button ${style}" href="${href}">${escape(label)}</a>`; }
function heading(eyebrow, title, text) { return `<div class="page-heading"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${text}</p></div>`; }
function stats(items) { return `<div class="stats">${items.map(([label,value,note])=>`<div class="stat"><span>${label}</span><strong class="mono-number">${value}</strong><small>${note}</small></div>`).join('')}</div>`; }
function pointCard(node, graph=false) {
  return `<button type="button" class="knowledge-card ${selectedNode===node.id&&graph?'selected':''}" data-node="${node.id}" ${graph?`id="node-${node.id}" aria-pressed="${selectedNode===node.id}"`:''}><span class="meta">${node.type}${graph?'':' · Elementary Mathematics'}</span><h3>${node.title}</h3><div class="row">${badge(node.unlocked?'unlocked':'locked')}${badge(node.learningState)}</div><p>${node.description}</p><span class="availability">${node.unlocked?'Review and checkpoint available':'Reading remains available'}</span></button>`;
}
function hub() {
  return `<section class="hero"><div class="hero-copy"><span class="eyebrow">YOUR NEXT SMALL STEP</span><h1>Make every idea<br>part of your thinking.</h1><p>Begin with a short review of equivalent fractions.<br>Build connections, then take your next step.</p><div class="row">${button('Start today’s review','#lesson','secondary')}${button('Explore the knowledge map','#map','secondary')}</div></div><div class="hero-art"><span class="eyebrow">MATHEMATICS IS CONNECTED</span><h3>Different forms.<br>One beautiful idea.</h3><svg width="392" height="220" viewBox="0 0 392 220" role="img" aria-label="Original illustration of connected mathematical ideas"><circle cx="196" cy="110" r="94" fill="none" stroke="#b3cfc2"/><ellipse cx="196" cy="110" rx="174" ry="50" transform="rotate(-22 196 110)" fill="none" stroke="#1e7067"/><circle cx="70" cy="52" r="10" fill="#965c20"/><circle cx="310" cy="159" r="8" fill="#1e7067"/><path d="M106 110h180M196 32v156" stroke="#b3cfc2" stroke-dasharray="4 6"/></svg><div class="row"><span class="math">½ = ²⁄₄</span><span class="caption">Same quantity.<br>A new perspective.</span></div></div></section>
  ${stats([['Knowledge points learned','12 / 30','Your wider Elementary learning path'],['Mastered','8','Supported by checkpoint evidence'],['Ready for review','3','Revisit, connect and strengthen'],['Learning this week','4 days','86 minutes of steady progress']])}
  <div class="section-heading"><h2>Continue your learning path</h2><small>Elementary Mathematics · Arithmetic</small></div><section class="route-summary">${[['01','Numbers & operations','mastered'],['02','Fractions & decimals','learning'],['03','Ratios & percentages','locked'],['04','Problems & reasoning','locked']].map(([num,title,state])=>`<div class="route-step"><strong>${num}</strong><h3>${title}</h3>${badge(state)}</div>`).join('')}</section>
  <div class="section-heading"><h2>A good place to begin today</h2><small>Build on what you already know</small></div><div class="cards-3">${['equivalent-fractions','decimal-place-value','simplifying-fractions'].map(id=>pointCard(nodes.find(n=>n.id===id))).join('')}</div><div class="section-heading"><h2>16 domains. Many ways to grow.</h2>${button('Browse every learning domain','#map','ghost')}</div><p>From foundational reasoning to research topics. Choose a domain, then a path that fits your background.</p>`;
}
function domainCard(d) { return `<button type="button" class="domain-card ${d.contentStatus==='preview'?'featured':''}" data-domain="${d.id}"><span class="number">DOMAIN ${String(d.order).padStart(2,'0')}</span><h3>${escape(d.name)}</h3><span class="zh" lang="zh">${escape(d.nameZh)}</span><p>${d.topics.map(escape).join(' · ')}</p>${badge(d.contentStatus)}</button>`; }
function levels() {
  const depths=new Map();
  function depth(id) { if(depths.has(id))return depths.get(id);const n=nodes.find(n=>n.id===id);const d=n.prerequisites.length?Math.max(...n.prerequisites.map(depth))+1:0;depths.set(id,d);return d; }
  for(const n of nodes)depth(n.id);
  return Array.from({length:Math.max(...depths.values())+1},(_,i)=>nodes.filter(n=>depths.get(n.id)===i));
}
function nodeDetail() {
  const n=nodes.find(n=>n.id===selectedNode);
  return `<aside class="panel soft node-detail stack"><span class="eyebrow">SELECTED KNOWLEDGE POINT</span><h3>${n.title}</h3><div class="row">${badge(n.unlocked?'unlocked':'locked')}${badge(n.learningState)}</div><p>${n.description}</p><div class="divider"></div><h3 style="font-size:14px">Before this point</h3>${n.prerequisites.length?`<ul>${n.prerequisites.map(id=>`<li>${nodes.find(x=>x.id===id).title}</li>`).join('')}</ul>`:'<p>No prerequisites. Start here.</p>'}<p>${n.unlocked?'You can review this point and enter its checkpoint.':'Complete every prerequisite checkpoint to unlock this point. You can still browse the reading material.'}</p>${n.lessonAvailable?button('Review this lesson','#lesson'): '<p class="caption">This preview includes the outline for this point.</p>'}${n.lessonAvailable?button('Try the checkpoint','#practice','outline'):''}<div class="divider"></div><p class="caption">Knowledge type: ${n.type}<br>Preview version: 1.0</p></aside>`;
}
function currentRoute() {
  return `<div class="selected-domain"><div><span class="eyebrow">ELEMENTARY MATHEMATICS / ARITHMETIC</span><h2 style="margin-top:10px">${route.title}</h2><p>A small route through a much larger subject.</p></div>${badge('preview')}</div><div class="map-detail-layout"><section class="panel route-panel"><h3>See how the ideas connect</h3><p class="caption">Arrows show learning prerequisites, not subject classifications.</p><div class="row route-legend">${badge('mastered')}${badge('learned')}${badge('unlocked')}${badge('locked')}</div><div class="graph-wrap"><svg class="graph-edges" aria-hidden="true"><defs><marker id="arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#aac5b7"/></marker></defs><g id="edge-paths"></g></svg><div class="graph-levels">${levels().map(level=>`<div class="graph-level">${level.map(n=>pointCard(n,true)).join('')}</div>`).join('')}</div></div><p class="read-only-note">Unlock status and learning status are independent. Planned content is shown at domain level, not as a locked lesson.</p></section>${nodeDetail()}</div><p class="caption" style="margin-top:18px">10 visible points in this sample route. The wider Elementary path contains the progress records shown in the Learning Hub.</p>`;
}
function domainOutline(d) {
  return `<section class="selected-domain"><div><span class="eyebrow">DOMAIN ${String(d.order).padStart(2,'0')}</span><h2 style="margin-top:10px">${escape(d.name)}</h2><p lang="zh">${escape(d.nameZh)}</p></div>${badge(d.contentStatus)}</section><div class="board-notice">This is a learning-oriented grouping. Topic outlines describe coverage; they do not imply that lessons have been published or that you have unlocked them.</div><div class="section-heading"><h2>Topics within this domain</h2><small>${d.topics.length} learning areas</small></div><div class="domain-topic-grid">${d.topics.map((topic,i)=>`<section class="topic-outline"><span class="eyebrow">${String(i+1).padStart(2,'0')}</span><h3>${escape(topic)}</h3><span class="caption" lang="zh">${escape(d.topicsZh[i])}</span>${badge(d.contentStatus==='preview'&&i===0?'preview':'outline')}</section>`).join('')}</div>${d.id==='elementary-mathematics'?`<section class="panel soft outline-next"><h3>Begin with numbers and fractions</h3><p>A route designed for learning, consolidation and review.</p><div class="row"><button class="button" data-map-mode="route">Open the preview route</button>${button('Review equivalent fractions','#lesson','outline')}</div></section>`:'<section class="panel soft outline-next"><h3>Build the route from your starting point</h3><p>Lessons and checkpoints will appear here as content is reviewed. Your progress will be measured within a published route.</p></section>'}<div class="section-heading"><h2>Connect with other domains</h2></div><p>Related areas help you explore. These links are not automatic unlocking requirements.</p><div class="related-domains">${d.relatedDomains.map(id=>{const other=domains.find(x=>x.id===id);return `<button data-domain="${id}">${escape(other.name)}</button>`;}).join('')}</div>`;
}
function map() {
  const d=domains.find(x=>x.id===selectedDomain);
  const filtered=domains.filter(d=>[d.name,d.nameZh,...d.topics,...d.topicsZh].join(' ').toLocaleLowerCase().includes(search.toLocaleLowerCase()));
  return `${heading('KNOWLEDGE MAP','Find your place in mathematics.','Explore 16 learning domains, then choose a route and revisit the ideas you have learned.')}<div class="board-notice" style="margin-bottom:28px">16 study-friendly groups — not an official count of mathematical fields. Domains may overlap; knowledge points can be shared across learning paths.</div><div class="map-layout"><aside class="domain-sidebar"><h2>Learning domains <span class="caption">/ 16</span></h2><nav class="domain-nav" aria-label="Learning domains">${domains.map(d=>`<button data-domain="${d.id}" class="${selectedDomain===d.id&&mapMode!=='domains'?'selected':''}" aria-pressed="${selectedDomain===d.id&&mapMode!=='domains'}"><span>${String(d.order).padStart(2,'0')}</span>${escape(d.name)}</button>`).join('')}</nav></aside><div class="map-main"><label class="mobile-domain-select">Jump to a learning domain<select id="domain-select"><option value="all">All 16 domains</option>${domains.map(d=>`<option value="${d.id}" ${d.id===selectedDomain&&mapMode!=='domains'?'selected':''}>${String(d.order).padStart(2,'0')} · ${escape(d.name)}</option>`).join('')}</select></label><div class="map-toolbar"><div class="segmented" aria-label="Map view"><button data-map-mode="domains" class="${mapMode==='domains'?'active':''}" aria-pressed="${mapMode==='domains'}">All domains</button><button data-map-mode="route" class="${mapMode==='route'?'active':''}" aria-pressed="${mapMode==='route'}">My current route</button></div>${mapMode==='domains'?`<label class="search-field"><span aria-hidden="true">⌕</span><span class="sr-only">Search domains and topics</span><input id="domain-search" type="search" value="${escape(search)}" placeholder="Search domains or topics"></label>`:''}</div>${mapMode==='domains'?`<p class="caption" id="domain-count" style="margin-bottom:16px">${filtered.length} of 16 learning domains</p><section class="domain-grid" aria-label="Learning domains">${filtered.length?filtered.map(domainCard).join(''):'<div class="empty-state"><h2>No matching domain</h2><p>Try a subject name or topic.</p></div>'}</section>`:mapMode==='route'?currentRoute():domainOutline(d)}</div></div>`;
}
function fractionFigure() { return `<figure class="fraction-visual" aria-label="One of two equal parts and two of four equal parts cover the same half of a whole"><div class="fraction-pair"><div class="fraction-bar"><span class="filled"></span><span></span></div><figcaption class="math">1 / 2</figcaption></div><span class="equals" aria-hidden="true">=</span><div class="fraction-pair"><div class="fraction-bar"><span class="filled"></span><span class="filled"></span><span></span><span></span></div><figcaption class="math">2 / 4</figcaption></div></figure>`; }
function explanation() {
  if(lessonTab==='symbolic')return '<h3>Multiplying by one changes the form, not the value.</h3><p>For b ≠ 0 and k ≠ 0, the ratio k/k equals 1. Multiplying a/b by 1 keeps its value unchanged.</p><div class="math">a/b × k/k = (a × k)/(b × k)</div><p>For example, with a = 1, b = 2 and k = 2:</p><div class="math">1/2 × 2/2 = 2/4</div><p class="caption">For elementary fraction exercises, a, b and k are whole numbers with b and k nonzero.</p>';
  if(lessonTab==='examples')return '<h3>Use a shared factor to simplify.</h3><p>Both 6 and 8 are divisible by 2. Dividing the numerator and denominator by that same factor gives:</p><div class="math">6/8 = (6 ÷ 2)/(8 ÷ 2) = 3/4</div><p>Similarly, divide both 10 and 15 by their common factor 5:</p><div class="math">10/15 = 2/3</div><p class="caution">Changing only the numerator or only the denominator changes the value. For example, 1/2 ≠ 2/2.</p>';
  return `<h3>The same whole. A different way to divide it.</h3><p>Take one of two equal parts. Divide each part in two again, and you now have two of four equal parts. The shaded area stays the same.</p>${fractionFigure()}<p class="caption">The number of total parts doubles, and so does the number of selected parts.</p>`;
}
function lesson() {
  return `<div class="breadcrumbs"><a href="#map">Knowledge Map</a> / Elementary Mathematics / Fractions</div><div class="lesson-heading"><div><span class="eyebrow">THEOREM · 等值分数</span><h1 style="margin-top:12px">Equivalent fractions</h1><p>Why can a different fraction mean the same amount?</p></div><div class="row">${badge('unlocked')}${badge('learned')}</div></div><div class="lesson-layout"><nav class="panel lesson-nav" aria-label="Lesson sections"><h2>In this lesson</h2><a class="active" href="#visual-section">01 · See the idea</a><a href="#theorem-section">02 · State the property</a><a href="#example-section">03 · Apply it</a><a href="#lesson-actions">04 · Check understanding</a><div class="divider"></div><p class="caption">Return whenever<br>you need a refresher.</p></nav><article class="lesson-main"><section class="panel soft theorem" id="theorem-section"><span class="eyebrow">THEOREM / EQUIVALENT FRACTIONS</span><h2>Multiply the numerator and denominator by the same nonzero number. The fraction’s value stays the same.</h2><div class="math">a / b = (a × k) / (b × k)</div><p class="caption">Conditions: b ≠ 0 and k ≠ 0. When simplifying a fraction with whole-number terms, divide by a common factor.</p></section><section class="panel" id="visual-section"><div class="lesson-tabs" role="tablist" aria-label="Explanation perspective">${[['visual','Visual intuition'],['symbolic','Symbolic reasoning'],['examples','Worked examples']].map(([id,label])=>`<button role="tab" id="tab-${id}" data-lesson-tab="${id}" aria-selected="${id===lessonTab}" aria-controls="explanation-panel" class="${id===lessonTab?'active':''}" tabindex="${id===lessonTab?0:-1}">${label}</button>`).join('')}</div><div id="explanation-panel" role="tabpanel" aria-labelledby="tab-${lessonTab}" class="explanation-body">${explanation()}</div></section><section class="panel stack" id="example-section"><h3>Try explaining why 6/8 = 3/4.</h3><p>Both terms are divided by the common factor 2. The number of selected parts and the number of total parts change by the same factor.</p><p class="caution">Common mistake: changing only one of the two terms.</p></section></article><aside class="panel lesson-rail" id="lesson-actions"><h2>Your learning record</h2><div>${badge('learned')}</div><p>Last reviewed: Sep 28<br>Learning steps: 3 / 3</p><div class="progress-bar" aria-label="All 3 learning steps completed"><span style="width:100%"></span></div><div class="divider"></div><h2>Check your understanding</h2><p>A checkpoint has 5 questions.<br>At least 4 correct answers are needed to pass.</p>${button('Start the checkpoint','#practice')}${button('Report a content issue','#feedback','ghost')}<p class="caption">Original sample lesson · v1.0<br>Design preview, not a live publication.</p></aside></div>`;
}
function practice() {
  return `${heading('KNOWLEDGE CHECKPOINT / EQUIVALENT FRACTIONS','Let an idea stand up to a question.','5 questions. At least 4 correct to pass. Explanations appear after submission.')}<section class="panel step-list" aria-label="Checkpoint progress">${[['01','Answered'],['02','Answered'],['03','Current'],['04','Not answered'],['05','Not answered']].map(([num,label])=>`<div class="test-step ${num==='03'?'current':''}"><strong>${num}</strong><span>${label}</span></div>`).join('')}</section><div class="practice-layout"><section class="panel question"><span class="eyebrow">QUESTION 3 OF 5 · NUMERICAL ANSWER</span><h2>Write 6/8 in lowest terms.</h2><p>Enter a fraction, for example 2/3.</p><div class="answer-field"><label for="answer">Your answer</label><input id="answer" type="text" value="3/4" maxlength="128" autocomplete="off" spellcheck="false" aria-describedby="answer-note"></div><p class="caption" id="answer-note">Your answer has not been submitted.</p><div class="divider"></div><div class="row"><button class="button secondary" data-preview-action="previous">Previous question</button><button class="button" data-preview-action="next">Save & next question</button>${button('Back to the lesson','#lesson','ghost')}</div><p class="caption">Design preview: answers are not stored, submitted or graded.</p><div id="practice-notice" role="status"></div></section><aside class="panel soft stack practice-info"><h3>Take your time.<br>Focus on understanding.</h3><ul><li>2 of 5 questions answered</li><li>No countdown timer</li><li>Submit all questions together</li><li>View explanations after submission</li></ul><div class="divider"></div><h3>What this checkpoint covers</h3><p>Equivalent fractions<br>When the property applies<br>Simplification and common mistakes</p>${button('Report a question issue','#feedback','ghost')}<p class="caption">Sample question EX-FR-003<br>Sample content v1.0</p></aside></div>`;
}
function progress() {
  return `${heading('MY PROGRESS / ELEMENTARY MATHEMATICS','Every step has a place in your story.','Progress belongs to a learning path. Mastery is supported by learning and checkpoint records.')}${stats([['Knowledge points learned','12 / 30','The wider Elementary learning path'],['Mastered','8','Learning and checkpoint complete'],['Ready for review','3','A useful focus for this week'],['Learning days','18 days','6 hours 24 minutes in total']])}<div class="chart-layout"><section class="panel"><div class="section-heading" style="margin:0"><h2>Four weeks of steady growth</h2><small>New points learned per week</small></div><svg class="chart" viewBox="0 0 792 230" role="img" aria-label="New knowledge points learned: week 1, one; week 2, two; week 3, four; week 4, five."><path d="M48 30h710M48 90h710M48 150h710M48 210h710" fill="none" stroke="#dce5dd"/><path d="M96 186L300 150L504 78L708 42V210H96Z" fill="#e8f3ed"/><path d="M96 186L300 150L504 78L708 42" fill="none" stroke="#1e7067" stroke-width="3"/>${[[96,186],[300,150],[504,78],[708,42]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="6" fill="#1e7067"/>`).join('')}</svg><div class="chart-axis">${[1,2,4,5].map((n,i)=>`<div>Week ${i+1}<strong>${n} ${n===1?'point':'points'}</strong></div>`).join('')}</div><p class="caption" style="margin-top:22px">Sample record: 12 new knowledge points across four weeks.</p></section><aside class="panel soft stack"><h2>Review makes your next step stronger.</h2><p>3 knowledge points are ready for consolidation. Begin with a recent difficulty.</p><div class="stack" style="font-size:14px"><span>↗ Order of operations</span><span>↗ What a fraction means</span><span>↗ Factors & multiples</span></div><button class="button" data-open-route="true">Open the review map</button></aside></div><div class="section-heading"><h2>Your knowledge record</h2><small>Unlock and learning states stay separate</small></div><section class="panel table-scroll"><table class="table"><thead><tr><th>Knowledge point</th><th>Access</th><th>Learning</th><th>Last reviewed</th><th>Action</th></tr></thead><tbody>${[['Arithmetic operations','unlocked','mastered','Sep 22'],['Equivalent fractions','unlocked','learned','Sep 28'],['Simplifying fractions','locked','unlearned','Not started']].map(([title,access,state,date])=>`<tr><td>${title}</td><td>${badge(access)}</td><td>${badge(state)}</td><td>${date}</td><td>${title==='Equivalent fractions'?button('Review','#lesson','ghost'):'<button class="button ghost" data-open-route="true">View in map</button>'}</td></tr>`).join('')}</tbody></table></section><p class="caption" style="margin-top:20px">Sample learning records. Research frontiers are not measured as a percentage of “all mathematics.”</p>`;
}
function feedback() {
  return `${heading('FEEDBACK','Help make mathematics more reliable.','Report an error, suggest a clearer explanation or share an idea for a better learning path.')}<div class="feedback-layout"><form class="panel feedback-form" id="feedback-form"><h2>Share a suggestion</h2><fieldset class="field-group feedback-type"><legend>Feedback type</legend>${[['error','Content error'],['explanation','Explanation'],['feature','Feature idea']].map(([value,label])=>`<label><input type="radio" name="type" value="${value}" ${value==='explanation'?'checked':''}>${label}</label>`).join('')}</fieldset><div class="field-group"><label>Related content</label><div class="panel soft stack" style="padding:20px;gap:7px"><h3>Equivalent fractions</h3><p class="caption">Knowledge point KP-FR-005 · Sample version 1.0</p></div></div><div class="field-group"><label for="feedback-title">A short description</label><input id="feedback-title" name="title" required maxlength="160" value="Add a step-by-step view of splitting the whole."></div><div class="field-group"><label for="feedback-detail">What would make it clearer?</label><textarea id="feedback-detail" name="detail" required maxlength="4000">I understand multiplying both terms by 2. A sequence showing how each half becomes two equal parts would make it easier to explain to a child.</textarea></div><p class="caption">Specific examples help us review the issue.</p><button class="button" type="submit">Preview submission</button><div id="feedback-notice" role="status"></div><p class="caption">Design preview: this form does not send or save feedback.</p></form><aside class="panel soft stack"><h2>A suggestion should have a next step.</h2><p>Content errors go to review first. The outcome will appear in your feedback history.</p><div class="divider"></div><h3>Your sample feedback history</h3><section class="feedback-record"><h3 style="font-size:15px">Fraction diagram suggestion</h3>${badge('learning','Awaiting review')}<p class="caption">Sep 30</p></section><section class="feedback-record"><h3 style="font-size:15px">Order-of-operations wording</h3>${badge('mastered','Resolved')}<p class="caption">Sep 24 · Updated explanation</p></section><p class="caption">Received → Reviewed → Corrected → Published<br>Each report refers to a specific content version.</p></aside></div>`;
}
function drawEdges() {
  const wrap=document.querySelector('.graph-wrap');const paths=document.querySelector('#edge-paths');if(!wrap||!paths)return;
  const base=wrap.getBoundingClientRect();const svg=wrap.querySelector('svg');svg.setAttribute('viewBox',`0 0 ${base.width} ${base.height}`);
  paths.innerHTML=nodes.flatMap(n=>n.prerequisites.map(id=>{const from=document.getElementById(`node-${id}`).getBoundingClientRect();const to=document.getElementById(`node-${n.id}`).getBoundingClientRect();const x1=from.left+from.width/2-base.left,y1=from.bottom-base.top+1,x2=to.left+to.width/2-base.left,y2=to.top-base.top-5;const mid=y1+(y2-y1)/2;return `<path d="M${x1} ${y1} C${x1} ${mid},${x2} ${mid},${x2} ${y2}" fill="none" stroke="#aac5b7" stroke-width="1.5" marker-end="url(#arrow)"/>`;})).join('');
}
function render({focus=false}={}) {
  layoutObserver?.disconnect();
  const rawPage=(location.hash.slice(1).split('/')[0]||'hub');const page=['visual-section','theorem-section','example-section','lesson-actions'].includes(rawPage)?'lesson':rawPage;const renderers={hub,map,lesson,practice,progress,feedback};const current=renderers[page]?page:'hub';
  main.dataset.page=current;main.innerHTML=renderers[current]();document.title=`${({hub:'Learning Hub',map:'Knowledge Map',lesson:'Equivalent Fractions',practice:'Checkpoint',progress:'My Progress',feedback:'Feedback'})[current]} · Math Master`;
  document.querySelectorAll('[data-page]').forEach(a=>{const active=a.dataset.page===(current==='lesson'?'map':current);a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  layoutObserver=new ResizeObserver(drawEdges);const graph=document.querySelector('.graph-wrap');if(graph)layoutObserver.observe(graph);requestAnimationFrame(drawEdges);
  if(focus)main.focus({preventScroll:true});
}
function openRoute(node) { selectedDomain='elementary-mathematics';mapMode='route';if(node)selectedNode=node;if(location.hash==='#map'){render();document.querySelector(node?`#node-${node}`:'[data-map-mode="route"]')?.focus({preventScroll:true});}else location.hash='map'; }
document.addEventListener('click',event=>{
  if(event.target.closest('.skip-link')){event.preventDefault();main.focus({preventScroll:false});return;}
  const target=event.target.closest('button');if(!target)return;
  if(target.dataset.domain){selectedDomain=target.dataset.domain;mapMode='outline';search='';render();const sidebar=document.querySelector(`.domain-nav [data-domain="${selectedDomain}"]`);const control=sidebar?.getClientRects().length?sidebar:document.getElementById('domain-select');control?.focus({preventScroll:true});announce.textContent=`Showing ${domains.find(d=>d.id===selectedDomain).name}`;}
  if(target.dataset.mapMode){mapMode=target.dataset.mapMode;if(mapMode==='route')selectedDomain='elementary-mathematics';render();document.querySelector(`[data-map-mode="${mapMode}"]`)?.focus({preventScroll:true});}
  if(target.dataset.node){if(location.hash==='#map'&&mapMode==='route'){selectedNode=target.dataset.node;render();document.getElementById(`node-${selectedNode}`)?.focus({preventScroll:true});announce.textContent=`Selected ${nodes.find(n=>n.id===selectedNode).title}`;}else openRoute(target.dataset.node);}
  if(target.dataset.openRoute)openRoute();
  if(target.dataset.lessonTab){lessonTab=target.dataset.lessonTab;render();document.getElementById(`tab-${lessonTab}`).focus({preventScroll:true});}
  if(target.dataset.previewAction)document.querySelector('#practice-notice').innerHTML='<p class="notice">Preview only. This answer was not submitted or recorded.</p>';
});
document.addEventListener('input',event=>{if(event.target.id!=='domain-search')return;const input=event.target;const selection=input.selectionStart;search=input.value;render();const replacement=document.querySelector('#domain-search');replacement.focus({preventScroll:true});replacement.setSelectionRange(selection,selection);});
document.addEventListener('change',event=>{if(event.target.id!=='domain-select')return;selectedDomain=event.target.value==='all'?'elementary-mathematics':event.target.value;mapMode=event.target.value==='all'?'domains':'outline';render();document.getElementById('domain-select')?.focus({preventScroll:true});});
document.addEventListener('submit',event=>{if(event.target.id!=='feedback-form')return;event.preventDefault();document.querySelector('#feedback-notice').innerHTML='<p class="notice">Preview only. Your feedback was not sent or saved.</p>';});
document.addEventListener('keydown',event=>{const tab=event.target.closest('[data-lesson-tab]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const ids=['visual','symbolic','examples'];let i=ids.indexOf(lessonTab);i=event.key==='Home'?0:event.key==='End'?2:(i+(event.key==='ArrowRight'?1:2))%3;lessonTab=ids[i];render();document.getElementById(`tab-${lessonTab}`).focus({preventScroll:true});});
window.addEventListener('hashchange',()=>{if(['visual-section','theorem-section','example-section','lesson-actions'].includes(location.hash.slice(1))){if(main.dataset.page!=='lesson')render({focus:true});document.getElementById(location.hash.slice(1))?.scrollIntoView();return;}render({focus:true});window.scrollTo({top:0,behavior:'instant'});});
render();
