import {it,expect,vi,afterEach} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {FeedbackAccountContext,FeedbackAccountProvider} from './feedback-account';
import {DiscussionPanel,FeedbackTicket} from './discussion-panel';
import {TicketList} from './ticket-list';
import {FeedbackState,FeedbackStatus} from './status';
import {id,otherId,metadata} from '@/lib/feedback/test-fixtures';
import {FeedbackRequestError} from '@/lib/feedback/types';
import {readFeedback,sendFeedback} from '@/lib/feedback/client';
import {getAuthContext} from '@/lib/auth/client';
vi.mock('@/lib/feedback/client',()=>({readFeedback:vi.fn(),sendFeedback:vi.fn()}));
vi.mock('@/lib/auth/client',()=>({getAuthContext:vi.fn(),notifyAuthChanged:vi.fn()}));
vi.mock('next/navigation',()=>({useRouter:()=>({refresh:vi.fn(),push:vi.fn()})}));
const invalidate=vi.fn();const wrapper=({children}:{children:React.ReactNode})=><FeedbackAccountContext.Provider value={{actorId:id,invalidate}}>{children}</FeedbackAccountContext.Provider>;
afterEach(()=>vi.resetAllMocks());
it('reads discussion only on click and renders original unicode and HTML as text',async()=>{const text='中'.repeat(4000);vi.mocked(readFeedback).mockResolvedValue({actorId:id,data:{title:'<img src="https://invalid">',location:'line 1\nline 2',items:[{sequence:1,kind:'created',actor:'submitter',from:null,to:'new',message:text,resolution:null,recordedAt:'2026-10-03T00:00:00Z'}],nextCursor:null}});render(<DiscussionPanel ticketId={id}/>,{wrapper});expect(readFeedback).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Read discussion'}));expect(await screen.findByText(text)).toBeVisible();expect(screen.queryByRole('img')).toBeNull();expect(screen.getByText('<img src="https://invalid">')).toBeVisible();expect(screen.queryByRole('link',{name:'https://invalid'})).toBeNull()});
it('overlap returns a recoverable notice without any previous text',async()=>{vi.mocked(readFeedback).mockRejectedValue(new FeedbackRequestError('FEEDBACK_ANSWER_OVERLAP'));render(<DiscussionPanel ticketId={id}/>,{wrapper});fireEvent.click(screen.getByRole('button',{name:'Read discussion'}));expect(await screen.findByRole('alert')).toHaveTextContent('overlapping assessment');expect(screen.queryByText('answer-sentinel')).toBeNull()});
it('rejects a late read from a different actor',async()=>{vi.mocked(readFeedback).mockResolvedValue({actorId:otherId,data:{title:'answer-sentinel',location:'',items:[],nextCursor:null}});render(<DiscussionPanel ticketId={id}/>,{wrapper});fireEvent.click(screen.getByRole('button',{name:'Read discussion'}));await waitFor(()=>expect(invalidate).toHaveBeenCalled());expect(screen.queryByText('answer-sentinel')).toBeNull()});
it('metadata remains text-free and empty queues have a clear action',()=>{render(<TicketList initial={{items:[],nextCursor:null}} review={false}/>,{wrapper});expect(screen.getByText('No reports yet.')).toBeVisible();expect(screen.queryByText('answer-sentinel')).toBeNull()});
it.each(['new','processing','waiting_details','resolved','closed'] as const)('shows state %s',status=>{render(<FeedbackStatus status={status}/>);expect(screen.getByText({new:'New',processing:'In progress',waiting_details:'Waiting for details',resolved:'Resolved',closed:'Closed'}[status])).toBeVisible()});
it.each(['AUTHENTICATION_REQUIRED','FORBIDDEN','FEEDBACK_NOT_CONFIGURED','FEEDBACK_CONFLICT','RATE_LIMITED'] as const)('has a recoverable %s notice',code=>{render(<FeedbackState error={new FeedbackRequestError(code)}/>);expect(screen.getByRole('alert')).toBeVisible()});
it('successful old receipt refreshes current metadata without automatically reading text',async()=>{vi.mocked(getAuthContext).mockResolvedValue({ok:true,data:{user:{id,username:'x',roles:['learner'],mustChangePassword:false},csrfToken:'A'.repeat(43)}});vi.mocked(sendFeedback).mockResolvedValue({actorId:id,data:{status:200,ticket:metadata()}});vi.mocked(readFeedback).mockResolvedValue({actorId:id,data:{...metadata(),sequence:2,status:'processing'}});render(<FeedbackTicket initial={metadata()} review={false}/>,{wrapper});fireEvent.change(screen.getByLabelText('Additional details'),{target:{value:'reply'}});fireEvent.click(screen.getByRole('button',{name:'Add details'}));expect(await screen.findByText('In progress')).toBeVisible();expect(readFeedback).toHaveBeenCalledTimes(1);expect(vi.mocked(readFeedback).mock.calls[0][0]).toBe('/api/v1/feedback/tickets/'+id)});
it('account invalidation clears mounted text',async()=>{vi.mocked(getAuthContext).mockResolvedValue({ok:true,data:{user:{id,username:'x',roles:['learner'],mustChangePassword:false},csrfToken:'A'.repeat(43)}});render(<FeedbackAccountProvider actorId={id}><p>private-draft</p></FeedbackAccountProvider>);expect(await screen.findByText('private-draft')).toBeVisible();fireEvent(window,new Event('math-master:auth-change'));expect(screen.queryByText('private-draft')).toBeNull()});

import {feedbackPageError} from './page-data';
it('server error projections survive serialization with only safe fields',()=>{const error=feedbackPageError(new FeedbackRequestError('FEEDBACK_NOT_CONFIGURED'));expect(Object.getPrototypeOf(error)).toBe(Object.prototype);expect(JSON.parse(JSON.stringify(error))).toEqual({code:'FEEDBACK_NOT_CONFIGURED',message:'Feedback is temporarily unavailable.'});expect(feedbackPageError(new Error('answer-sentinel')).message).not.toContain('answer-sentinel')});
it('replaces rows when a fresh server queue page arrives on the same route',async()=>{
 const route='/api/v1/feedback/review/tickets';
 const view=render(<TicketList initial={{items:[metadata()],nextCursor:null}} review={true} route={route}/>,{wrapper});
 expect(screen.getByRole('link',{name:metadata().label})).toBeVisible();
 view.rerender(<TicketList initial={{items:[],nextCursor:null}} review={true} route={route}/>);
 expect(await screen.findByText('No reports match this queue.')).toBeVisible();
 expect(screen.queryByRole('link',{name:metadata().label})).toBeNull();
});
it('queue filter controls follow updated routes including browser back navigation',()=>{
 const view=render(<TicketList initial={{items:[],nextCursor:null}} review={true} route='/api/v1/feedback/review/tickets?status=closed&category=suggestion'/>,{wrapper});
 view.rerender(<TicketList initial={{items:[],nextCursor:null}} review={true} route='/api/v1/feedback/review/tickets?status=processing&category=math_error'/>);
 expect(screen.getByLabelText('Status',{exact:true})).toHaveValue('processing');
 expect(screen.getByLabelText('Category',{exact:true})).toHaveValue('math_error');
});
