import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, it, expect, vi } from "vitest";
import { DraftEditor } from "./draft-editor";
import { componentDraft, readyGate, publicGoals } from "./test-fixtures";
import { questionFailure } from "@/lib/question/schemas";
const mocks = vi.hoisted(() => ({ request: vi.fn(), push: vi.fn(), refresh: vi.fn() }));
vi.mock("@/lib/question/client", () => ({ requestQuestion: mocks.request }));
vi.mock("next/navigation", () => ({ useRouter: () => mocks }));
beforeEach(() => { Object.values(mocks).forEach(m => m.mockReset()); vi.spyOn(globalThis, "fetch").mockResolvedValue(Response.json({ data: publicGoals() })); });
it("DraftEditor", async () => {
    const d = componentDraft();
    render(<DraftEditor initial={d} canEdit/>);
    expect(screen.getByLabelText("Template 1 family")).toHaveValue("rational_arithmetic");
    expect(screen.getByLabelText("Template 2 family")).toHaveValue("rational_comparison");
    expect(screen.getByLabelText("Template 3 family")).toHaveValue("missing_operand");
    expect(screen.getByLabelText("Template 1 parameter 1 values")).toHaveValue("-1/2\n1/2\n1\n2\n3");
    expect(screen.getByLabelText("Template 1 coverage 1 objective index 1")).toHaveValue(0);
    fireEvent.click(screen.getAllByRole("button", { name: "Load published objectives" })[0]);
    expect(await screen.findByText("Fractions · 分数")).toBeVisible();
    expect(screen.getByText("0: Add rational numbers.")).toBeVisible();
    fireEvent.change(screen.getByLabelText("Template 1 prompt"), { target: { value: "Preserve this unsaved prompt {{left}} + {{right}}." } });
    mocks.request.mockResolvedValue(questionFailure("QUESTION_DRAFT_CONFLICT"));
    fireEvent.click(screen.getByRole("button", { name: "Save draft" }));
    await screen.findByRole("alert");
    expect(screen.getByLabelText("Template 1 prompt")).toHaveValue("Preserve this unsaved prompt {{left}} + {{right}}.");
    expect(mocks.request.mock.calls[0][1].expectedRevision).toBe(1);
    expect(screen.getByRole("button", { name: "Submit for review" })).toBeDisabled();
});
it("DraftEditorCannotSubmitOldValidationDigestAfterSave", async () => {
    const d = componentDraft();
    render(<DraftEditor initial={d} canEdit/>);
    mocks.request.mockResolvedValue({ ok: true, data: readyGate() });
    fireEvent.click(screen.getByRole("button", { name: "Validate saved revision" }));
    await waitFor(() => expect(screen.getByRole("button", { name: "Submit for review" })).toBeEnabled());
    fireEvent.change(screen.getByLabelText("Template 1 prompt"), { target: { value: "A revised prompt {{left}} + {{right}}." } });
    expect(screen.getByRole("button", { name: "Submit for review" })).toBeDisabled();
    mocks.request.mockResolvedValue({ ok: true, data: { ...d, revision: 2 } });
    fireEvent.click(screen.getByRole("button", { name: "Save draft" }));
    await screen.findByRole("heading", { name: /Saved revision 2/ });
    expect(screen.getByRole("button", { name: "Submit for review" })).toBeDisabled();
});
