"use client";
import {UiText} from "@/lib/i18n/ui-text";
import {uiMessage,uiValue} from "@/lib/i18n/format";
import {useUiI18n} from "@/lib/i18n/provider";
import { SafeMarkdown } from "@/features/reading/safe-markdown";
import type { ValidationReport, Instance, QuestionPackage } from "@/lib/question/types";
import styles from "@/styles/question.module.css";
export function GenerationPanel({ report, revision }: {
    report: ValidationReport;
    revision: number;
}) {
 const {t}=useUiI18n();
 return <section className={styles.card}><h2><UiText notice={uiMessage("generation-panel.saved.revision.value.generation.check.22a232",{v0:uiValue(revision)})}/></h2><p>{report.readyToSubmit ? t("generation-panel.machine.checks.passed.reviewer.approval.is.required.deef63",{}) : t("generation-panel.questions.need.work.before.submission.d2b52f",{})}</p><p><UiText notice={uiMessage("content-preview.structural.issues.value.completeness.issues.value.human.checks.va.6fe5e4",{v0:uiValue(report.structuralTotal),v1:uiValue(report.completenessTotal),v2:uiValue(report.humanReviewTotal)})}/></p>{report.truncated && <p><UiText notice={uiMessage("generation-panel.showing.the.first.100.issues.totals.include.every.issue.b82545",{})}/></p>}<ul>{[...report.structuralErrors, ...report.completenessErrors, ...report.humanReviewRequirements].map((i, n) => <li key={n}><strong>{i.code}</strong> {i.path}: {i.message}</li>)}</ul><p><UiText notice={uiMessage("generation-panel.question.package.bytes.value.frozen.bytes.value.42a43d",{v0:uiValue(report.packageBytes),v1:uiValue(report.frozenBytes)})}/></p>{report.generation.map(g => <article key={g.template.id}><h3>{g.template.id}</h3><p><UiText notice={uiMessage("generation-panel.raw.combinations.value.excluded.value.independently.verified.inst.58393d",{v0:uiValue(g.rawCombinations),v1:uiValue(g.excludedCombinations),v2:uiValue(g.validInstances)})}/></p><p><UiText notice={uiMessage("template-fields.generator.version.value.verifier.version.value.bda518",{v0:uiValue(g.generatorVersion),v1:uiValue(g.verifierVersion)})}/></p><ul>{g.constraintCounts.map(c => <li key={c.constraint}><UiText notice={uiMessage("generation-panel.value.value.excluded.combinations.671ebe",{v0:uiValue(c.constraint),v1:uiValue(c.count)})}/></li>)}</ul></article>)}{report.coverage.map((c, n) => <article key={n}><h3><UiText notice={uiMessage("content-preview.value.vvalue.bde90b",{v0:uiValue(c.knowledge.id),v1:uiValue(c.knowledge.version)})}/></h3><p><UiText notice={uiMessage("generation-panel.effective.instances.value.fixed.value.generated.value.a62299",{v0:uiValue(c.effectiveInstances),v1:uiValue(c.fixedInstances),v2:uiValue(c.generatedInstances)})}/></p><p><UiText notice={uiMessage("generation-panel.core.objective.indices.value.value.3f0422",{v0:uiValue(c.coreObjectiveIndices.join(", ") || "None configured"),v1:uiValue(c.fiveQuestionFeasible ? "Five-question cover found" : "Five-question cover needs work")})}/></p><p><UiText notice={uiMessage("generation-panel.supplementary.objective.indices.value.d292f7",{v0:uiValue(c.supplementaryObjectiveIndices.join(", ") || "None")})}/></p></article>)}<p><UiText notice={uiMessage("generation-panel.generated.previews.become.trusted.publication.content.only.after..03fe9c",{})}/></p></section>; }
export function Sources({ sources }: {
    sources: QuestionPackage["templates"][number]["sources"];
}) { return <section><h4><UiText notice={uiMessage("content.check.sources",{})}/></h4>{sources.length ? <ul>{sources.map((s, i) => <li key={i}><strong>{s.title || "Source title unverified"}</strong><p>{s.author || "Author unverified"} · {s.kind} · {s.license || "License unverified"}</p>{s.url && <p>{s.url}</p>}<p>{s.attribution || "Attribution unverified"}</p>{s.accessedAt && <p><UiText notice={uiMessage("content-preview.accessed.value.5dc1f8",{v0:uiValue(s.accessedAt)})}/></p>}</li>)}</ul> : <p><UiText notice={uiMessage("generation-panel.no.sources.declared.source.verification.is.required.f5603d",{})}/></p>}</section>; }
export function InstancePreview({ instance }: {
    instance: Instance;
}) { const b = instance.body; return <article className={styles.card}><h3>{instance.identity.id}</h3><p className={styles.metadata}><UiText notice={uiMessage("generation-panel.version.value.sha.value.777514",{v0:uiValue(instance.identity.version),v1:uiValue(instance.identity.sha256)})}/></p><p><UiText notice={uiMessage("generation-panel.primary.knowledge.value.vvalue.60e3e9",{v0:uiValue(b.knowledge.id),v1:uiValue(b.knowledge.version)})}/></p><div className={styles.formula}><SafeMarkdown source={b.prompt} assets={[]}/></div>{b.choices.length > 0 && <ol>{b.choices.map(c => <li key={c.id}><strong>{c.id}</strong>: <SafeMarkdown source={c.text} assets={[]}/></li>)}</ol>}<p><UiText notice={uiMessage("generation-panel.verified.answer.value.6f716c",{v0:uiValue(b.correctNumeric ? `${b.correctNumeric.numerator}/${b.correctNumeric.denominator}` : b.correctChoiceId)})}/></p><div className={styles.formula}><SafeMarkdown source={b.explanation} assets={[]}/></div>{b.assets.length > 0 && <section><h4><UiText notice={uiMessage("generation-panel.fixed.illustrations.fd3664",{})}/></h4><p><UiText notice={uiMessage("generation-panel.availability.follows.the.current.public.publication.check.attribu.c068b3",{})}/></p>{b.assets.map(a => <figure key={a.id}><img src={"/api/v1/assets/" + a.sha256} alt={"Fixed mathematical illustration " + a.id} loading="lazy"/><figcaption>{a.id} · {a.sha256}</figcaption></figure>)}</section>}<Sources sources={b.sources}/><details><summary><UiText notice={uiMessage("generation-panel.independent.verification.witness.and.fixed.coverage.8269b5",{})}/></summary><pre>{JSON.stringify({ origin: instance.origin, template: instance.template, parameters: instance.parameters, generatorVersion: instance.generatorVersion, verifierVersion: instance.verifierVersion, witness: b.witness, coverage: b.coverage, units: b.units, assets: b.assets }, null, 2)}</pre></details></article>; }
