import { SafeMarkdown } from "@/features/reading/safe-markdown";
import type { ValidationReport, Instance, QuestionPackage } from "@/lib/question/types";
import styles from "@/styles/question.module.css";
export function GenerationPanel({ report, revision }: {
    report: ValidationReport;
    revision: number;
}) { return <section className={styles.card}><h2>Saved revision {revision} · Generation check</h2><p>{report.readyToSubmit ? "Machine checks passed. Independent review is required." : "Questions need work before submission."}</p><p>Structural issues: {report.structuralTotal} · Completeness issues: {report.completenessTotal} · Human checks: {report.humanReviewTotal}</p>{report.truncated && <p>Showing the first 100 issues. Totals include every issue.</p>}<ul>{[...report.structuralErrors, ...report.completenessErrors, ...report.humanReviewRequirements].map((i, n) => <li key={n}><strong>{i.code}</strong> {i.path}: {i.message}</li>)}</ul><p>Question package bytes: {report.packageBytes} · Frozen bytes: {report.frozenBytes}</p>{report.generation.map(g => <article key={g.template.id}><h3>{g.template.id}</h3><p>Raw combinations: {g.rawCombinations} · Excluded: {g.excludedCombinations} · Independently verified instances: {g.validInstances}</p><p>Generator version {g.generatorVersion} · Verifier version {g.verifierVersion}</p><ul>{g.constraintCounts.map(c => <li key={c.constraint}>{c.constraint}: {c.count} excluded combinations</li>)}</ul></article>)}{report.coverage.map((c, n) => <article key={n}><h3>{c.knowledge.id} v{c.knowledge.version}</h3><p>Effective instances: {c.effectiveInstances} · Fixed: {c.fixedInstances} · Generated: {c.generatedInstances}</p><p>Core objective indices: {c.coreObjectiveIndices.join(", ") || "None configured"} · {c.fiveQuestionFeasible ? "Five-question cover found" : "Five-question cover needs work"}</p><p>Supplementary objective indices: {c.supplementaryObjectiveIndices.join(", ") || "None"}</p></article>)}<p>Generated previews become trusted publication content only after independent review and activation.</p></section>; }
export function Sources({ sources }: {
    sources: QuestionPackage["templates"][number]["sources"];
}) { return <section><h4>Sources</h4>{sources.length ? <ul>{sources.map((s, i) => <li key={i}><strong>{s.title || "Source title unverified"}</strong><p>{s.author || "Author unverified"} · {s.kind} · {s.license || "License unverified"}</p>{s.url && <p>{s.url}</p>}<p>{s.attribution || "Attribution unverified"}</p>{s.accessedAt && <p>Accessed: {s.accessedAt}</p>}</li>)}</ul> : <p>No sources declared. Source verification is required.</p>}</section>; }
export function InstancePreview({ instance }: {
    instance: Instance;
}) { const b = instance.body; return <article className={styles.card}><h3>{instance.identity.id}</h3><p className={styles.metadata}>Version {instance.identity.version} · SHA {instance.identity.sha256}</p><p>Primary knowledge: {b.knowledge.id} v{b.knowledge.version}</p><div className={styles.formula}><SafeMarkdown source={b.prompt} assets={[]}/></div>{b.choices.length > 0 && <ol>{b.choices.map(c => <li key={c.id}><strong>{c.id}</strong>: <SafeMarkdown source={c.text} assets={[]}/></li>)}</ol>}<p>Verified answer: {b.correctNumeric ? `${b.correctNumeric.numerator}/${b.correctNumeric.denominator}` : b.correctChoiceId}</p><div className={styles.formula}><SafeMarkdown source={b.explanation} assets={[]}/></div>{b.assets.length > 0 && <section><h4>Fixed illustrations</h4><p>Availability follows the current public publication. Check attribution in the original source.</p>{b.assets.map(a => <figure key={a.id}><img src={"/api/v1/assets/" + a.sha256} alt={"Fixed mathematical illustration " + a.id} loading="lazy"/><figcaption>{a.id} · {a.sha256}</figcaption></figure>)}</section>}<Sources sources={b.sources}/><details><summary>Independent verification witness and fixed coverage</summary><pre>{JSON.stringify({ origin: instance.origin, template: instance.template, parameters: instance.parameters, generatorVersion: instance.generatorVersion, verifierVersion: instance.verifierVersion, witness: b.witness, coverage: b.coverage, units: b.units, assets: b.assets }, null, 2)}</pre></details></article>; }
