import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, it, expect, vi } from "vitest";
import { PublicationPanel } from "./publication-panel";
import { publication, fixtureID, otherID } from "./test-fixtures";
import { questionFailure } from "@/lib/question/schemas";
const mocks = vi.hoisted(() => ({ request: vi.fn(), content: vi.fn(), auth: vi.fn(), push: vi.fn(), refresh: vi.fn() }));
vi.mock("@/lib/question/client", () => ({ requestQuestion: mocks.request }));
vi.mock("@/lib/content/client", () => ({ contentRequest: mocks.content }));
vi.mock("@/lib/auth/client", () => ({ authRequest: mocks.auth }));
vi.mock("next/navigation", () => ({ useRouter: () => mocks }));
beforeEach(() => { Object.values(mocks).forEach(m => m.mockReset()); mocks.request.mockImplementation(async (route) => ({ ok: true, data: route.kind === "readPublication" ? { ...publication(), status: "published" } : { items: [], total: 0, limit: 1, offset: 0, publicationId: otherID, manifestSha: publication().manifestSha } })); mocks.content.mockResolvedValue({ ok: true, data: { head: otherID, items: [], total: 0, limit: 1, offset: 0 } }); });
it("PublicationPanel", async () => {
    const candidate = { ...publication(), id: otherID, baseKnowledgeHead: otherID, baseQuestionHead: fixtureID };
    render(<PublicationPanel initial={{ items: [candidate], total: 2, limit: 1, offset: 0, head: fixtureID }} knowledgeHead={otherID}/>);
    await waitFor(() => expect(mocks.request.mock.calls.some(a => a[0].kind === "readPublication" && a[0].id === fixtureID)).toBe(true));
    fireEvent.change(screen.getByLabelText("Publication reason"), { target: { value: "Activate an independently reviewed fixed snapshot." } });
    mocks.request.mockResolvedValue(questionFailure("REAUTHENTICATION_REQUIRED"));
    fireEvent.click(screen.getByRole("button", { name: "Activate snapshot" }));
    expect(await screen.findByRole("dialog")).toBeVisible();
    const first = mocks.request.mock.calls.find(a => a[0].kind === "activateRelease")!;
    expect(first[1]).toMatchObject({ expectedKnowledgeHead: otherID, expectedQuestionHead: fixtureID });
    mocks.auth.mockResolvedValue({ ok: true, data: { reauthenticatedAt: "2026-10-02T00:00:00Z" } });
    fireEvent.change(screen.getByLabelText("Your password"), { target: { value: "a public test password" } });
    fireEvent.click(screen.getByRole("button", { name: "Verify password" }));
    await screen.findByRole("button", { name: "Retry previous request" });
    expect(mocks.request.mock.calls.filter(a => a[0].kind === "activateRelease")).toHaveLength(1);
    mocks.request.mockResolvedValue(questionFailure("QUESTION_PUBLICATION_STALE"));
    fireEvent.click(screen.getByRole("button", { name: "Retry previous request" }));
    await waitFor(() => expect(mocks.request.mock.calls.filter(a => a[0].kind === "activateRelease")).toHaveLength(2));
    const attempts = mocks.request.mock.calls.filter(a => a[0].kind === "activateRelease");
    expect(attempts[1][2]).toBe(attempts[0][2]);
    expect(attempts[1][1]).toEqual(attempts[0][1]);
    await waitFor(() => expect(screen.getByRole("button", { name: "Activate snapshot" })).toBeDisabled());
});
