import { readFileSync } from "node:fs";
import { draftView as emptyDraft, fixtureID, otherID, sha, publication } from "@/lib/question/test-fixtures";
import type { DraftView, SubmissionView, Instance, CoverageReport } from "@/lib/question/types";
export { fixtureID, otherID, sha, publication };
export const editor = { id: otherID, username: "question_editor", roles: ["learner", "editor"] as const, mustChangePassword: false };
export function componentDraft(): DraftView { return { ...emptyDraft(), questionPackage: JSON.parse(readFileSync("../content/questions/elementary-rationals.v1.json", "utf8")) } as DraftView; }
export const readyGate = () => ({ ...componentDraft().gate, completenessErrors: [], completenessTotal: 0, readyToSubmit: true, digest: sha });
export function componentInstances(): Instance[] { const source = componentDraft().questionPackage.templates[0].sources; return ["fixed-one", "fixed-two"].map((id, i) => ({ identity: { id, version: 1, sha256: sha }, origin: "fixed", template: null, parameters: [], generatorVersion: null, verifierVersion: null, body: { type: "numeric", knowledge: { id: "fractions", version: 2 }, coverage: [{ knowledge: { id: "fractions", version: 2 }, objectiveIndices: [0] }], units: [], prompt: "Calculate $1 + " + (i + 2) + "$.", explanation: "Add the two rational numbers exactly.", answerFormat: "rational", choices: [], correctChoiceId: null, correctNumeric: { numerator: String(i + 3), denominator: "1" }, witness: { engine: { family: "rational_arithmetic", operation: "add", unknownSide: null, generatorVersion: 1, verifierVersion: 1 }, parameters: [{ name: "left", value: "1" }, { name: "right", value: String(i + 2) }] }, assets: [], sources: source } })); }
export function componentSubmission(): SubmissionView { const d = componentDraft(), instances = componentInstances(); return { id: fixtureID, workspaceId: otherID, ownerId: otherID, status: "pending", createdAt: d.createdAt, revision: 1, frozen: { catalogueVersion: 1, catalogueSha256: sha, questionPackage: { ...d.questionPackage, templates: [], fixedQuestions: instances.map(i => ({ id: i.identity.id, version: 1, body: i.body })), blueprints: [] }, sourceMap: [{ knowledge: { id: "fractions", version: 2 }, batchSha256: sha, relativePath: "original/fractions.json", sha256: sha, legacyId: "original-fixture", note: "Source originality needs independent verification." }], authorIds: [otherID], legacyUnattributed: true, resolved: [], objectives: [{ knowledge: { id: "fractions", version: 2, sha256: sha }, objectiveIndex: 0, text: "Add rational numbers. 比较分数" }], generation: [], instanceIdentities: instances.map(i => i.identity), coverage: [], generatorVersions: [], verifierVersions: [1], frozenDigest: sha }, gate: readyGate(), review: null }; }
export function publicGoals() { const k = JSON.parse(readFileSync("../backend/internal/content/testdata/workflow-ready.json", "utf8")).knowledge[0]; return { knowledge: { ...k, id: "fractions", version: 2, title: "Fractions", titleZh: "分数", objectives: ["Add rational numbers.", "比较分数"] }, units: [], assets: [] }; }
export function coverageReport(): CoverageReport { return { knowledgeHead: otherID, questionHead: fixtureID, publishedKnowledge: 2, approvedTemplates: 1, fixedQuestions: 5, effectiveInstances: 5, duplicateInstances: 0, nodes: { items: [{ knowledge: { id: "fractions", version: 2, sha256: sha }, blueprint: { id: "fractions-blueprint", version: 1, sha256: sha }, effectiveInstances: 5, fixedInstances: 5, generatedInstances: 0, assessmentInstances: 5, duplicateInstances: 0, coreObjectiveIndices: [0], coveredObjectiveIndices: [0], fiveQuestionFeasible: true, ready: true, reasons: [], supplementaryObjectiveIndices: [] }], total: 2, limit: 1, offset: 0 } }; }
