import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';import {importManagedFiles,canonicalManagedJSON} from './import-managed.mjs';
const fixture=await readFile(new URL('../../backend/internal/knowledgeadmin/testdata/valid-source.json',import.meta.url));
test('managed importer serializes files and keeps raw identity, retrying the same apply key',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'managed-import-'));try{const a=join(dir,'a.json'),b=join(dir,'b.json');await writeFile(a,fixture);const other=JSON.parse(fixture);other.source.source_id='different-book';await writeFile(b,JSON.stringify(other));let active=0,max=0,applyKeys=[],attempt=0;const ids=[];
 const client={async preview(bytes,key){active++;max=Math.max(max,active);const d=JSON.parse(bytes);ids.push(d.knowledge_points[0].id);await new Promise(r=>setTimeout(r,5));active--;return {importId:key,previewToken:'token',items:d.knowledge_points.map((p,index)=>({index,externalId:p.id,action:index===0?'create':'conflict'}))}},async apply(id,input,key){assert.deepEqual(input.selectedIndexes,[0]);applyKeys.push(key);if(attempt++===0)throw new TypeError('network dropped');return {operationId:id,counts:{createdKnowledge:1,conflicts:1},items:[]}},async readImport(){return {receipt:null}}};
 const result=await importManagedFiles({files:[a,b],client,publish:true});assert.equal(result.length,2);assert.equal(max,1);assert.equal(ids[0],ids[1]);assert.equal(applyKeys[0],applyKeys[1]);
 }finally{await rm(dir,{recursive:true,force:true})}
});
test('manifest refuses unsafe paths and changed source before uploading',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'managed-manifest-'));try{const p=join(dir,'source.json');await writeFile(p,fixture);let uploads=0;const client={async preview(){uploads++;throw Error('unexpected upload')}};await assert.rejects(importManagedFiles({files:[p],manifest:manifestFor(fixture,'../source.json'),client}));assert.equal(uploads,0);await writeFile(p,Buffer.concat([fixture,Buffer.from(' ')]));await assert.rejects(importManagedFiles({files:[p],manifest:manifestFor(fixture,'source.json'),client}));assert.equal(uploads,0)}finally{await rm(dir,{recursive:true,force:true})}
});
test('JCS uses UTF16 ordering, ECMAScript numbers and stable property ordering',()=>{assert.equal(canonicalManagedJSON({d:1.0,c:'中文😀',b:2e-3,a:1e30}),'\u007b"a":1e+30,"b":0.002,"c":"中文😀","d":1}');assert.throws(()=>canonicalManagedJSON({x:NaN}))});

function manifestFor(bytes,name){const d=JSON.parse(bytes),hash=v=>createHash('sha256').update(v).digest('hex');const files=[{path:name,sha256:hash(bytes),bytes:bytes.length,source_id:d.source.source_id,dataset_version:d.dataset_version,record_count:d.knowledge_points.length}];const records=d.knowledge_points.map((p,n)=>({source_id:d.source.source_id,id:p.id,version:p.version,path:name,json_pointer:'/knowledge_points/'+n,record_sha256:hash(canonicalManagedJSON(p))}));return {format:'math-master-knowledge-manifest',schema_version:'1.0',record_digest_algorithm:'jcs-rfc8785-sha256',files,records,snapshot_id:hash(canonicalManagedJSON({files,records}))}}
