'use client';
import {useState,useSyncExternalStore} from 'react';import {useRouter} from 'next/navigation';import {useUiI18n} from '@/lib/i18n/provider';import {managedRequest} from '@/lib/knowledge-admin/client';import {KnowledgeError,type Knowledge,type CurrentInput} from '@/lib/knowledge-admin/types';import type {StaticMessageKey} from '@/lib/i18n/types';
const subscribeHydration=()=>()=>{},clientHydrated=()=>true,serverHydrated=()=>false;
const types=['concept','definition','axiom','theorem','corollary','method','mathematical-thinking','other'] as const;
export function EditKnowledge({initial}:{initial:Knowledge}) {
 const {t}=useUiI18n(),router=useRouter();const[data,setData]=useState(initial),[input,setInput]=useState<CurrentInput>({externalId:initial.externalId,point:structuredClone(initial.point),sources:initial.sources,topicKeys:initial.topicKeys}),[topics,setTopics]=useState(initial.topicKeys.join(', ')),[explanations,setExplanations]=useState(JSON.stringify(initial.point.explanations,null,2)),[sources,setSources]=useState(JSON.stringify(initial.sources,null,2)),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const p=input.point;
 const hydrated=useSyncExternalStore(subscribeHydration,clientHydrated,serverHydrated);
 async function save(){if(!hydrated||busy)return;setBusy(true);setNotice('');try{const payload={...input,topicKeys:topics.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean),sources:JSON.parse(sources),point:{...p,explanations:JSON.parse(explanations)}};const saved=await managedRequest<Knowledge>(`/api/v3/admin/knowledge/${data.id}`,'PUT',payload,crypto.randomUUID(),data.editToken);setData(saved);setNotice(t('managed.saved',{}));router.refresh()}catch(e){setNotice(t(e instanceof KnowledgeError&&e.status===409?'managed.conflict':'managed.invalidInput',{}))}finally{setBusy(false)}}
 const text=(key:'title'|'title_zh'|'statement'|'scope'|'system'|'proof'|'type_reason'|'type_other_reason'|'proof_scope',name:StaticMessageKey,rows=4)=><label>{t(name,{})}<textarea aria-label={t(name,{})} rows={rows} value={p[key]??''} onChange={e=>setInput({...input,point:{...p,[key]:e.target.value}})}/></label>;
 const lines=(key:'conditions'|'objectives'|'equations'|'examples'|'counterexamples'|'common_misconceptions'|'tags',name:StaticMessageKey)=><label>{t(name,{})}<textarea aria-label={t(name,{})} rows={4} value={p[key].join('\n')} onChange={e=>setInput({...input,point:{...p,[key]:e.target.value.split('\n').filter(Boolean)}})}/></label>;
 return <><header className="page-heading"><h1>{t('managed.edit',{})} · {p.title_zh}</h1><p>{t('managed.id',{})}: {data.externalId} · {t(data.published?'managed.published':'managed.unpublished',{})}</p></header><form className="panel" onSubmit={e=>{e.preventDefault();void save()}}><fieldset className="managed-fields" disabled={busy||!hydrated}>
 {text('title_zh','managed.title',2)}{text('title','content.field.title',2)}
 <label>{t('managed.type',{})}<select aria-label={t('managed.type',{})} value={p.type} onChange={e=>setInput({...input,point:{...p,type:e.target.value as typeof p.type}})}>{types.map(v=><option key={v} value={v}>{t(`managed.type.${v}`,{})}</option>)}</select></label>
 {text('type_reason','managed.reason')}{p.type==='other'&&text('type_other_reason','managed.otherReason')}
 <label>{t('managed.difficulty',{})}<select value={p.learning_difficulty.difficulty_level} onChange={e=>setInput({...input,point:{...p,learning_difficulty:{...p.learning_difficulty,difficulty_level:Number(e.target.value)}}})}>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select></label>
 <label>{t('managed.difficultyReason',{})}<textarea aria-label={t('managed.difficultyReason',{})} value={p.learning_difficulty.rationale} onChange={e=>setInput({...input,point:{...p,learning_difficulty:{...p.learning_difficulty,rationale:e.target.value}}})}/></label>
 <label>{t('managed.topics',{})}<input aria-label={t('managed.topics',{})} required value={topics} onChange={e=>setTopics(e.target.value)}/></label>
 {text('statement','managed.statement',14)}{lines('conditions','managed.conditions')}{text('scope','managed.scope')}{text('system','managed.system')}{lines('objectives','managed.objectives')}{text('proof','managed.proof',10)}
 <label>{t('managed.proofScope',{})}<select value={p.proof_scope} onChange={e=>setInput({...input,point:{...p,proof_scope:e.target.value as typeof p.proof_scope}})}>{['full','sketch','none','not_applicable'].map(v=><option key={v} value={v}>{v}</option>)}</select></label>
 {lines('equations','managed.equations')}{lines('examples','managed.examples')}{lines('counterexamples','managed.counterexamples')}{lines('common_misconceptions','managed.misconceptions')}{lines('tags','managed.tags')}
 <label>{t('managed.explanations',{})}<textarea aria-label={t('managed.explanations',{})} rows={10} value={explanations} onChange={e=>setExplanations(e.target.value)}/></label>
 <label>{t('managed.sourcesEdit',{})}<textarea aria-label={t('managed.sourcesEdit',{})} rows={10} value={sources} onChange={e=>setSources(e.target.value)}/></label>
 <button className="button">{t('managed.save',{})}</button><button type="button" className="button secondary" onClick={async()=>{if(!window.confirm(t('managed.deleteConfirm',{})))return;setBusy(true);try{await managedRequest(`/api/v3/admin/knowledge/${data.id}`,'DELETE',{},crypto.randomUUID(),data.editToken);router.push('/admin/knowledge')}catch{setNotice(t('managed.conflict',{}))}finally{setBusy(false)}}}>{t('managed.delete',{})}</button></fieldset>{notice&&<p role="status">{notice}</p>}</form></>;
}
