import {it,expect,vi} from 'vitest';import {render,screen} from '@testing-library/react';import {UploadKnowledge} from './upload';
vi.mock('@/lib/i18n/provider',()=>({useUiI18n:()=>({t:(key:string)=>key})}));
it('offers direct upload and saving with no review or version controls',()=>{render(<UploadKnowledge onComplete={()=>{}}/>);expect(screen.getByRole('button',{name:'managed.uploadPublish'})).toBeDisabled();expect(screen.queryByText(/review|version/i)).toBeNull();expect(document.querySelector('input[type=file][multiple]')).not.toBeNull()});

import {fireEvent,waitFor} from '@testing-library/react';import {KnowledgeError} from '@/lib/knowledge-admin/types';const uploadMocks=vi.hoisted(()=>({preview:vi.fn(),apply:vi.fn(),read:vi.fn()}));vi.mock('@/lib/knowledge-admin/client',()=>({previewSource:uploadMocks.preview,applyImport:uploadMocks.apply,readImport:uploadMocks.read,managedRequest:vi.fn()}));
it('lets an administrator replace a file after a definite invalid source response',async()=>{uploadMocks.preview.mockRejectedValueOnce(new KnowledgeError('INVALID_FIELD',422));render(<UploadKnowledge onComplete={()=>{}}/>);const input=document.querySelector('input[type=file]') as HTMLInputElement;await waitFor(()=>expect(input).toBeEnabled());fireEvent.change(input,{target:{files:[new File(['invalid'],'bad.json')]}});fireEvent.click(screen.getByRole('button',{name:'managed.uploadPublish'}));await screen.findByRole('alert');expect(input).toBeEnabled()});
import {KnowledgeAdminList} from './list';vi.mock('next/navigation',()=>({useRouter:()=>({refresh:vi.fn()}),useSearchParams:()=>new URLSearchParams('topicKey=97F40&difficulty=2&q=fractions')}));
import {renderToString} from 'react-dom/server';
import {EditKnowledge} from './edit';
import type {Knowledge} from '@/lib/knowledge-admin/types';
// Self-authored render fixture, local to the frontend Docker build context.
const editPoint={"id":"demo-rational-fraction","version":1,"title":"Rational fraction","title_zh":"有理分数","type":"definition","type_status":"confirmed","content_origin":"original","statement":"当整数 $b\\ne0$ 时，$a/b$ 表示满足 $b\\cdot x=a$ 的有理数 $x$。","conditions":["$a,b\\in\\mathbb{Z}$。","$b\\ne0$。"],"scope":"整数分子和非零整数分母构成的有理分数。","system":"有理数及其通常运算","objectives":["说明该知识点的含义，并检查适用条件。"],"msc_codes":["97F40"],"classification_status":"confirmed","classification_evidence":[{"msc_code":"97F40","reason":"内容用于整数与有理数的基础教学。","evidence_fields":["statement","conditions","scope"],"kind":"specific"}],"learning_difficulty":{"difficulty_level":1,"rationale":"使用基本整数运算和分数含义即可理解。","prerequisites":["整数","乘法和除法"],"review_status":"body_assessed","rubric_version":"learning-foundation-v1-20261008","proof_scope_note":"这是格式示例的知识理解评估，没有外部教材证明认证。"},"proof":"","proof_scope":"not_applicable","equations":[],"explanations":[{"kind":"intuition","body":"分母说明把单位分成多少份，分子说明取多少份；代数定义也覆盖负数。"}],"examples":["$3/4$ 表示满足 $4x=3$ 的有理数。"],"counterexamples":[],"common_misconceptions":["分母为零的表达式不属于这里定义的有理分数。"],"provenance":[],"relations":[],"tags":["format-example"],"extensions":{},"type_reason":"核心陈述明确引入有理分数的定义。","classification_mode":"msc"} as Knowledge['point'];
it('keeps server-rendered editing controls disabled until the client owns their state',()=>{
 const initial={id:'k-'+'a'.repeat(56),externalId:editPoint.id,point:editPoint,sources:[],topicKeys:['97F40'],ref:{id:'k-'+'a'.repeat(56),contentSha256:'a'.repeat(64),sourceKind:'managed'},published:true,deleted:false,editToken:'51390b7d-a8e9-4e98-a3ae-22101c20b309',updatedAt:'2026-10-10T00:00:00Z'} as Knowledge;
 const html=renderToString(<EditKnowledge initial={initial}/>);const host=document.createElement('div');host.innerHTML=html;
 expect(host.querySelector('fieldset')).toHaveAttribute('disabled');
 render(<EditKnowledge initial={initial}/>);expect(screen.getByRole('textbox',{name:'managed.statement'})).toBeEnabled();
});
it('exposes topic and difficulty filtering with current query values',()=>{render(<KnowledgeAdminList initial={{items:[],total:0,limit:20,offset:0}}/>);expect(document.querySelector('input[name=topicKey]')).toHaveValue('97F40');expect(document.querySelector('select[name=difficulty]')).toHaveValue('2');expect(document.querySelector('input[name=q]')).toHaveValue('fractions')});
