'use client';
import {useRef,useState,useEffect} from 'react';import {useUiI18n} from '@/lib/i18n/provider';import {previewSource,applyImport,readImport} from '@/lib/knowledge-admin/client';import {KnowledgeError,type Preview,type Receipt,type ApplyInput} from '@/lib/knowledge-admin/types';
type Pending={file:File;previewKey:string;applyKey:string;preview?:Preview;input?:ApplyInput};
export function UploadKnowledge({onComplete}:{onComplete:()=>void}){const{t}=useUiI18n(),[ready,setReady]=useState(false),[files,setFiles]=useState<File[]>([]),[publish,setPublish]=useState(true),[busy,setBusy]=useState(false),[preview,setPreview]=useState<Preview|null>(null),[receipt,setReceipt]=useState<Receipt|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState<number[]>([]),[recovery,setRecovery]=useState<string|null>(null);const pending=useRef<Pending|null>(null),queue=useRef<File[]>([]);
useEffect(()=>{setReady(true);setRecovery(sessionStorage.getItem('managed-import-operation'));const reset=()=>{sessionStorage.removeItem('managed-import-operation');setRecovery(null);pending.current=null;setPreview(null);setReceipt(null)};window.addEventListener('math-master:auth-change',reset);return()=>window.removeEventListener('math-master:auth-change',reset)},[]);
function remember(id:string){sessionStorage.setItem('managed-import-operation',id);setRecovery(id)}
async function finish(r:Receipt){setReceipt(r);setPreview(null);pending.current=null;sessionStorage.removeItem('managed-import-operation');setRecovery(null);onComplete();const next=queue.current.shift();if(next)await inspect(next)}
async function recover(){if(!recovery)return;setBusy(true);try{const status=await readImport(recovery);if(status.receipt)await finish(status.receipt);else setError(t('managed.pendingImport',{}))}catch(e){setError(t(e instanceof KnowledgeError&&e.status<500?'managed.invalidInput':'managed.uncertain',{}))}finally{setBusy(false)}}
async function inspect(file:File){if(file.size>64*1024*1024){setError(t('managed.files',{}));return};const job=pending.current??{file,previewKey:crypto.randomUUID(),applyKey:crypto.randomUUID()};pending.current=job;setBusy(true);setError('');try{if(job.input&&job.preview){const status=await readImport(job.preview.importId);if(status.receipt){await finish(status.receipt);return}};const p=await previewSource(job.file,job.previewKey);job.preview=p;remember(p.importId);setPreview(p);setSelected(p.items.filter(i=>i.action==='create'||i.action==='link').map(i=>i.index))}catch(e){setError(t(e instanceof KnowledgeError&&e.status<500?'managed.invalidInput':'managed.uncertain',{}))}finally{setBusy(false)}}
async function apply(){const job=pending.current;if(!job?.preview)return;job.input??={selectedIndexes:selected,publish,previewToken:job.preview.previewToken};setBusy(true);setError('');try{const r=await applyImport(job.preview.importId,job.input,job.applyKey);await finish(r)}catch(e){setError(t(e instanceof KnowledgeError&&e.status<500?'managed.invalidInput':'managed.uncertain',{}))}finally{setBusy(false)}}
return <section className="panel">{recovery&&!pending.current&&<><p>{t('managed.pendingImport',{})}</p><button className="button secondary" disabled={busy} onClick={()=>void recover()}>{t('managed.recoverImport',{})}</button></>}<h2>{t('managed.upload',{})}</h2><label>{t('managed.files',{})}<input type="file" accept="application/json,.json" multiple disabled={!ready||busy||!!pending.current} onChange={e=>{setFiles(Array.from(e.target.files??[]));pending.current=null;setReceipt(null)}}/></label><label><input type="checkbox" checked={publish} disabled={busy||!!pending.current?.input} onChange={e=>setPublish(e.target.checked)}/>{t('managed.uploadPublish',{})}</label><button className="button" disabled={busy||files.length===0||!!preview} onClick={()=>{queue.current=files.slice(1);void inspect(files[0])}}>{t(publish?'managed.uploadPublish':'managed.saveOnly',{})}</button>{error&&<><p role="alert">{error}</p><button className="button secondary" disabled={busy} onClick={()=>{if(pending.current?.input)void apply();else if(pending.current)void inspect(pending.current.file)}}>{t('managed.retry',{})}</button></>}{preview&&<><h3>{t('managed.preview',{})}</h3><p>{t('managed.new',{})}: {preview.counts.createdKnowledge} · {t('managed.linked',{})}: {preview.counts.linkedTopics} · {t('managed.skipped',{})}: {preview.counts.skippedItems} · {t('managed.conflicts',{})}: {preview.counts.conflicts} · {t('managed.invalid',{})}: {preview.counts.invalidItems}</p><ul>{preview.items.map(i=><li key={i.index}><label><input type="checkbox" disabled={busy||!['create','link'].includes(i.action)} checked={selected.includes(i.index)} onChange={e=>setSelected(e.target.checked?[...selected,i.index]:selected.filter(x=>x!==i.index))}/>{i.externalId} · {i.topicKeys.join(', ')} · {i.action}{i.errorPath&&' · '+i.errorPath}</label></li>)}</ul><button className="button" disabled={busy} onClick={()=>void apply()}>{t('managed.apply',{})}</button></>}{receipt&&<p role="status">{t('managed.new',{})}: {receipt.counts.createdKnowledge} · {t('managed.linked',{})}: {receipt.counts.linkedTopics} · {t('managed.skipped',{})}: {receipt.counts.skippedItems} · {t('managed.conflicts',{})}: {receipt.counts.conflicts}</p>}</section>}
