"use client";
import {UiEnum,formatUiEnum} from "@/lib/i18n/enums";
import {UiText} from "@/lib/i18n/ui-text";
import {uiMessage,uiValue} from "@/lib/i18n/format";
import {useUiI18n} from "@/lib/i18n/provider";
import {EvidenceLink} from "../correction/evidence-link";
import Link from "next/link";
import type {HistoryEntry,LearningPage} from "@/lib/learning/types";
import styles from "@/styles/learning.module.css";
export function HistoryList({page,archived=false}:{page:LearningPage<HistoryEntry>;archived?:boolean}){
 const {t,locale}=useUiI18n();
return <section className={styles.panel} aria-label={t("page.learning-history",{})}><h2><UiText notice={uiMessage("page.learning-history",{})}/></h2>{page.items.length===0?<p><UiText notice={uiMessage("history-list.no.personal.learning.records.yet.b85eae",{})}/></p>:<ol className={styles.history}>{page.items.map(entry=>{const attempt=entry.attemptId?(archived?"/learning-history?archive=legacy&module="+(entry.kind==="practice"?"practice":"assessment")+"&attempt="+entry.attemptId:(entry.kind==="practice"?"/practice/":"/assessments/")+entry.attemptId+(entry.kind==="assessment"&&entry.state==="submitted"?"/result":"")):null;return <li key={entry.id}><div><strong>{entry.knowledge.id.replaceAll("-"," ")}</strong><span><UiText notice={uiMessage("history-list.version.value.value.value.ea7ec3",{v0:uiValue(entry.knowledge.version),v1:formatUiEnum(locale,"learning.attempt",entry.state),v2:uiValue(entry.validity)})}/></span><time dateTime={entry.occurredAt}><UiText notice={uiMessage("history-list.value.utc.c16e72",{v0:uiValue(new Date(entry.occurredAt).toISOString().slice(0,16).replace("T"," "))})}/></time></div>{attempt&&<Link prefetch={false} href={attempt}><UiText notice={uiMessage("history-list.view.attempt.b17a6b",{})}/></Link>}<Link prefetch={false} href={`/learning-history?${archived?"archive=legacy&":""}knowledge=${entry.knowledge.id}&version=${entry.knowledge.version}`}><UiText notice={uiMessage("history-list.view.learning.record.95f5a9",{})}/></Link>{entry.attemptId&&["submitted","answered","revealed","abandoned","expired"].includes(entry.state)&&(entry.kind==="assessment"||entry.kind==="practice")&&<EvidenceLink evidence={{kind:entry.kind,id:entry.attemptId}}/>}{(entry.kind==="started"||entry.kind==="completed")&&<EvidenceLink evidence={{kind:"learning-event",id:entry.id}}/>}{entry.kind==="enrollment"&&<EvidenceLink evidence={{kind:"enrollment",id:entry.id}}/>}</li>})}</ol>}<nav aria-label={t("history-list.history.pages.714bf6",{})} className={styles.actions}>{page.offset>0&&<Link prefetch={false} href={"/learning-history?"+(archived?"archive=legacy&":"")+"offset="+Math.max(0,page.offset-page.limit)}><UiText notice={uiMessage("admin-users.previous.a57b08",{})}/></Link>}{page.offset+page.limit<page.total&&<Link prefetch={false} href={"/learning-history?"+(archived?"archive=legacy&":"")+"offset="+(page.offset+page.limit)}><UiText notice={uiMessage("admin-users.next.1ff57a",{})}/></Link>}</nav></section>}
