"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import type {KnowledgeDetail,KnowledgeState,PracticeView,AttemptView} from "@/lib/learning/types";
import {useLearningCommand} from "./pending-command";
import {LearningStatus,CommandFeedback} from "./learning-status";
import styles from "@/styles/learning.module.css";
export function KnowledgeControls({detail,children}:{detail:KnowledgeDetail;children?:React.ReactNode}){const[state,setState]=useState(detail.state),router=useRouter();useEffect(()=>setState(detail.state),[detail.state]);const command=useLearningCommand<KnowledgeState>(v=>{setState(v);router.refresh()});const input={knowledge:state.knowledge,expectedKnowledgeHead:detail.knowledgeHead};const historical=detail.objectives.length===0&&detail.questionHead===null;
 return <section className={styles.panel} aria-label="Personal knowledge record"><h2>{historical?"Historical learning record":"Your learning record"}</h2><LearningStatus state={state}/>{historical?<p>This is a saved version. <Link prefetch={false} href={"/knowledge/"+state.knowledge.id}>Review the current explanation</Link>.</p>:<><p>Read freely. Your learning record changes when you choose an action below.</p>{state.canEnter?<div className={styles.actions}>{state.startedAt===null?<button className="button" disabled={command.busy} onClick={()=>void command.run({kind:"startKnowledge",id:state.knowledge.id},input)}>Start learning</button>:!state.completionValid?<button className="button" disabled={command.busy} onClick={()=>void command.run({kind:"completeKnowledge",id:state.knowledge.id},input)}>Mark as learned</button>:<span>Reading completion recorded.</span>}</div>:<p>Work through the prerequisites, or use a diagnostic assessment to check your understanding.</p>}{state.prerequisites.length>0&&<ul>{state.prerequisites.map(p=><li key={p.knowledge.id}><Link prefetch={false} href={"/knowledge/"+p.knowledge.id}>{p.knowledge.id.replaceAll("-"," ")}</Link> · {p.qualified?"Ready":"Needs assessment"}</li>)}</ul>}{children}<LearningLaunch detail={{...detail,state}}/></>}
 <Link prefetch={false} href={`/learning-history?knowledge=${state.knowledge.id}&version=${state.knowledge.version}`}>View learning history</Link><CommandFeedback command={command}/></section>
}

function LearningLaunch({detail:d}:{detail:KnowledgeDetail}){const router=useRouter(),[selected,setSelected]=useState(d.blueprints[0]?.blueprint.id??""),[mode,setMode]=useState<"node"|"diagnostic"|"review">(d.state.canEnter&&d.state.completionValid?"node":"diagnostic");const practice=useLearningCommand<PracticeView>(v=>router.push("/practice/"+v.summary.id)),assessment=useLearningCommand<AttemptView>(v=>router.push("/assessments/"+v.summary.id));const bp=d.blueprints.find(b=>b.blueprint.id===selected),busy=practice.busy||assessment.busy;const input={knowledge:d.state.knowledge,expectedKnowledgeHead:d.knowledgeHead,expectedQuestionHead:d.questionHead};return <section aria-label="Practice and assessment"><h3>Build understanding</h3><button className="button secondary" disabled={busy||d.questionHead===null||!!practice.pending} onClick={()=>void practice.run({kind:"createPractice"},input)}>Start single-question practice</button><CommandFeedback command={practice}/><h3>Check your understanding</h3>{d.activeAssessment?<Link prefetch={false} href={"/assessments/"+d.activeAssessment.id}>Continue current assessment</Link>:null}{d.blueprints.length===0?<p>A reviewed five-question assessment is not available for this knowledge point yet. You can still practise.</p>:<><label>Assessment goals<select value={selected} disabled={busy} onChange={e=>{assessment.clear();setSelected(e.target.value)}}>{d.blueprints.map((b,i)=><option key={b.blueprint.id} value={b.blueprint.id}>Set {i+1}: {b.coreObjectiveIndices.map(n=>d.objectives[n]).join("; ")}</option>)}</select></label><label>Assessment mode<select value={mode} disabled={busy} onChange={e=>{assessment.clear();setMode(e.target.value as typeof mode)}}><option value="node" disabled={!d.state.canEnter||!d.state.completionValid}>Learning check</option><option value="diagnostic">Diagnostic assessment</option><option value="review">Review assessment</option></select></label>{bp&&!bp.ready&&<p>Five eligible questions are not available. {bp.reasons.includes("exposure-cooldown")?"Previously viewed answers need time before they can be used in an assessment.":"Additional reviewed questions are needed for these goals."}{bp.retryAt&&<> Try after {new Date(bp.retryAt).toLocaleString("en")}.</>}</p>}<button className="button" disabled={busy||!bp?.ready||d.questionHead===null||!!assessment.pending||(mode==="node"&&(!d.state.canEnter||!d.state.completionValid))} onClick={()=>bp&&void assessment.run({kind:"createAssessment"},{...input,blueprint:bp.blueprint,mode})}>Start five-question assessment</button></>}<CommandFeedback command={assessment}/></section>}
