"use client";
import {UiText} from "@/lib/i18n/ui-text";
import {uiMessage,uiValue} from "@/lib/i18n/format";
import {useUiI18n} from "@/lib/i18n/provider";
import Link from "next/link";
import type {Overview} from "@/lib/learning/types";
import {HistoryList} from "./history-list";
import styles from "@/styles/learning.module.css";
export function OverviewPanel({overview}:{overview:Overview}){
 const {t}=useUiI18n();
const attempts=[overview.activePractice,overview.activeAssessment].filter(v=>v!==null);return <><section className={styles.panel} aria-label={t("overview-panel.learning.overview.f9c4ad",{})}><h2><UiText notice={uiMessage("overview-panel.your.progress.433a72",{})}/></h2><div className={styles.metrics}><span><UiText notice={uiMessage("overview-panel.value.read.0fdd28",{v0:uiValue(overview.completedCount)})}/></span><span><UiText notice={uiMessage("overview-panel.value.passed.70be87",{v0:uiValue(overview.effectivePassedCount)})}/></span><span><UiText notice={uiMessage("overview-panel.value.historically.unlocked.16f06c",{v0:uiValue(overview.historicalUnlockedCount)})}/></span></div><p><UiText notice={uiMessage("overview-panel.value.knowledge.points.started.79dd20",{v0:uiValue(overview.startedCount)})}/></p>{overview.knowledgeHead===null&&<p><UiText notice={uiMessage("overview-panel.reviewed.learning.content.will.appear.as.it.becomes.available.fdce83",{})}/></p>}{attempts.map(a=><Link prefetch={false} className="button secondary" key={a.id} href={(a.kind==="practice"?"/practice/":"/assessments/")+a.id}><UiText notice={uiMessage("overview-panel.continue.value.5d2b50",{v0:uiValue(a.kind==="practice"?t("audit.practice",{}):t("audit.assessment",{}))})}/></Link>)}<Link prefetch={false} href="/learning-history"><UiText notice={uiMessage("overview-panel.view.all.learning.history.7a7600",{})}/></Link></section><section className={styles.panel}><h2><UiText notice={uiMessage("overview-panel.learning.routes.13f0bd",{})}/></h2>{overview.availablePaths.length?overview.availablePaths.map(p=><p key={p.path.id}><Link prefetch={false} href={"/paths/"+p.path.id}>{p.title}</Link> · {p.totalNodes}<UiText notice={uiMessage("overview-panel.knowledge.points.4c5586",{})}/></p>):<p><UiText notice={uiMessage("overview-panel.no.reviewed.routes.are.available.yet.f42dab",{})}/></p>}</section><HistoryList page={{items:overview.recent,total:overview.recent.length,limit:20,offset:0}}/></>}
