"use client";
import {QualificationLink} from "../correction/qualification-link";
import Link from "next/link";
import {useRouter} from "next/navigation";
import type {PathSummary,PathNode,PathView,PublishedPathSummary} from "@/lib/learning/types";
import {LearningStatus,CommandFeedback} from "./learning-status";
import {useLearningCommand} from "./pending-command";
import styles from "@/styles/learning.module.css";
export function PathProgress({path,nodes}:{path:PathSummary;nodes:PathNode[]}){return <section className={styles.panel} aria-label="Fixed route progress"><h2>{path.title}</h2><p lang="zh-CN">{path.titleZh}</p><p>Saved route · Version {path.path.version}</p><div className={styles.metrics}><span>{path.completedNodes} / {path.totalNodes} read</span><span>{path.passedNodes} / {path.totalNodes} passed</span><span>{path.unlockedNodes} / {path.totalNodes} historically unlocked</span></div>{path.newVersionAvailable&&<aside><strong>New route version available</strong><p>Your saved version is unchanged. <Link prefetch={false} href={"/paths/"+path.path.id}>Explore the current route</Link>.</p></aside>}<ol className={styles.nodes} start={(nodes[0]?.position??0)+1}>{nodes.map(node=><li key={node.position} data-learning-node={node.state.knowledge.id}><h3>{node.available?<Link prefetch={false} href={"/knowledge/"+node.state.knowledge.id}>{node.title}</Link>:node.title}</h3><LearningStatus state={node.state} available={node.available}/>{node.state.qualification&&<QualificationLink qualification={node.state.qualification}/>}{node.reasons.length>0&&<p>Saved evidence needs a current review.</p>}<Link prefetch={false} href={`/learning-history?knowledge=${node.state.knowledge.id}&version=${node.state.knowledge.version}`}>View saved learning record</Link></li>)}</ol></section>}
export function JoinRoute({path,knowledgeHead}:{path:PublishedPathSummary;knowledgeHead:string}){const router=useRouter(),command=useLearningCommand<PathView>(v=>router.push("/learn?enrollment="+v.summary.id));return <section className={styles.panel} aria-label="Join learning route"><h2>Keep your route progress</h2><p>Save this route version with {path.totalNodes} knowledge points. Reading it does not join it.</p><button className="button" disabled={command.busy} onClick={()=>void command.run({kind:"enrollPath",id:path.path.id},{path:path.path,expectedKnowledgeHead:knowledgeHead})}>Join route</button><CommandFeedback command={command}/></section>}
