"use client";
import {UiText} from "@/lib/i18n/ui-text";
import {uiMessage,uiValue} from "@/lib/i18n/format";
import {useUiI18n} from "@/lib/i18n/provider";
import {QualificationLink} from "../correction/qualification-link";
import Link from "next/link";
import {useRouter} from "next/navigation";
import type {PathSummary,PathNode,PathView,PublishedPathSummary} from "@/lib/learning/types";
import {LearningStatus,CommandFeedback} from "./learning-status";
import {useLearningCommand} from "./pending-command";
import styles from "@/styles/learning.module.css";
export function PathProgress({path,nodes}:{path:PathSummary;nodes:PathNode[]}){
 const {t}=useUiI18n();
return <section className={styles.panel} aria-label={t("path-progress.fixed.route.progress.367920",{})}><h2>{path.title}</h2><p lang="zh-CN">{path.titleZh}</p><p><UiText notice={uiMessage("path-progress.saved.route.version.value.555a99",{v0:uiValue(path.path.version)})}/></p><div className={styles.metrics}><span><UiText notice={uiMessage("path-progress.value.value.read.8ae4d9",{v0:uiValue(path.completedNodes),v1:uiValue(path.totalNodes)})}/></span><span><UiText notice={uiMessage("path-progress.value.value.passed.bb2e62",{v0:uiValue(path.passedNodes),v1:uiValue(path.totalNodes)})}/></span><span><UiText notice={uiMessage("path-progress.value.value.historically.unlocked.abdc56",{v0:uiValue(path.unlockedNodes),v1:uiValue(path.totalNodes)})}/></span></div>{path.newVersionAvailable&&<aside><strong><UiText notice={uiMessage("path-progress.new.route.version.available.67ae0e",{})}/></strong><p><UiText notice={uiMessage("path-progress.your.saved.version.is.unchanged.b5be92",{})}/><Link prefetch={false} href={"/paths/"+path.path.id}><UiText notice={uiMessage("path-progress.explore.the.current.route.eec21f",{})}/></Link>.</p></aside>}<ol className={styles.nodes} start={(nodes[0]?.position??0)+1}>{nodes.map(node=><li key={node.position} data-learning-node={node.state.knowledge.id}><h3>{node.available?<Link prefetch={false} href={"/knowledge/"+node.state.knowledge.id}>{node.title}</Link>:node.title}</h3><LearningStatus state={node.state} available={node.available}/>{node.state.qualification&&<QualificationLink qualification={node.state.qualification}/>}{node.reasons.length>0&&<p><UiText notice={uiMessage("path-progress.saved.evidence.needs.a.current.review.8dbbf3",{})}/></p>}<Link prefetch={false} href={`/learning-history?knowledge=${node.state.knowledge.id}&version=${node.state.knowledge.version}`}><UiText notice={uiMessage("path-progress.view.saved.learning.record.3badde",{})}/></Link></li>)}</ol></section>}
export function JoinRoute({path,knowledgeHead}:{path:PublishedPathSummary;knowledgeHead:string}){
 const {t}=useUiI18n();
const router=useRouter(),command=useLearningCommand<PathView>(v=>router.push("/learn?enrollment="+v.summary.id));return <section className={styles.panel} aria-label={t("path-progress.join.learning.route.d8d3be",{})}><h2><UiText notice={uiMessage("path-progress.keep.your.route.progress.a80a0c",{})}/></h2><p><UiText notice={uiMessage("path-progress.save.this.route.version.with.value.knowledge.points.reading.it.do.96b512",{v0:uiValue(path.totalNodes)})}/></p><button className="button" disabled={command.busy} onClick={()=>void command.run({kind:"enrollPath",id:path.path.id},{path:path.path,expectedKnowledgeHead:knowledgeHead})}><UiText notice={uiMessage("path-progress.join.route.5560fe",{})}/></button><CommandFeedback command={command}/></section>}
